### ISSUE TITLE
Add MessageProperties attribute in org.springframework.amqp.core.AmqpTemplate#convertAndSend

### ISSUE THREAD

**Issue by StefanoGuerrini** [spring-projects/spring-amqp#1000]
### ### Enhancement

**Problem:** When I send a object using method convertAndSend I'm unable to insert in it some properties directly so I have to use MessageConverter, like:
```
MessageProperties properties = new MessageProperties();
properties.setHeader("key", "value");

MessageConverter converter = new SimpleMessageConverter();
Message message = converter.toMessage(objectToSend, properties);

rabbitTemplate.convertAndSend("exchange_name", "routing_key", message);
```

In my opinion should be possible to pass MessageProperties by attribute.
So the **solution** could be more compact, like: 
```
MessageProperties properties = new MessageProperties();
properties.setHeader("key", "value");

rabbitTemplate.convertAndSend("exchange_name", "routing_key", message, properties);
```

**Comment by garyrussell** [comment]
There is a MessagePostProcessor for this purpose...

```java
    rabbitTemplate.convertAndSend(exchange, rk, someObject, message -> {
        message.getMessageProperties().setHeader("key", "value");
        return m;
    });
```

**Comment by StefanoGuerrini** [comment]
That is perfect! Thanks.

**Comment by artembilan** [comment]
Can we close a PR on the matter and this issue as `Invalid` in favor of existing functionality?

In addition: when you use `send(Message)`, that's already your responsibility to populate `MessageProperties` properly into that `Message`.
