### ISSUE TITLE
RabbitListener's returning ListenableFuture<X> doesn't ack the message

### ISSUE THREAD

**Issue by rjbaucells** [spring-projects/spring-amqp#1009]
RabbitListener returning ListenableFuture<X> will not ack the message.

```java
@RabbitListener
public ListenableFuture<X> myListener(MyMessage myMessage) {
    ...
}
```

The `asyncSuccess()` implementation does not check the `InvocationResult` `returnType` (`null` value) throwing an exception at [AbstractAdaptableMessageListener  line 349](https://github.com/spring-projects/spring-amqp/blob/f4b653006dff8e5a28efc1c89656d7481408161d/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/AbstractAdaptableMessageListener.java#L349):

```java
Type returnType = ((ParameterizedType) resultArg.getReturnType()).getActualTypeArguments()[0];
```

The `(ParameterizedType) resultArg.getReturnType()` will always return `null` since `ParameterizedType` instance is created at [MessageListenerAdapter  line 294](https://github.com/spring-projects/spring-amqp/blob/f4b653006dff8e5a28efc1c89656d7481408161d/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/MessageListenerAdapter.java#L294):

```java
handleResult(new InvocationResult(result, null, null), message, channel);
```

Note that `InvocationResult` constructor declares `returnType` parameter as`@Nullable`

```java
InvocationResult(Object result, Expression sendTo, @Nullable Type returnType)
```

**Comment by garyrussell** [comment]
Can you provide an actual example of this failure?

The`MessageListenerAdapter` is not used by `@RabbitListener`s, `MessagingMessageListenerAdapter` is used instead.

It does look like there is an issue if a legacy POJO method (using the old adapter) returns a future, though. but that was never anticipated.

**Comment by artembilan** [comment]
Sounds like this is the same problem we have in the https://github.com/spring-projects/spring-amqp/issues/1006.

The PR https://github.com/spring-projects/spring-amqp/pull/1007 should address this one as well.

**Comment by artembilan** [comment]
I wonder why do we need that:
```
Type returnType = ((ParameterizedType) resultArg.getReturnType()).getActualTypeArguments()[0]; // NOSONAR
```
at all, since we are here in the `else` only when `deferredResult` is not `null` and can just use `deferredResult.getClass()`.
Or is it about something like this to cover: `ListenableFuture<List<MyPojo>>` ?

**Comment by artembilan** [comment]
Don't we have an NPE here:
```
Type returnType = ((ParameterizedType) resultArg.getReturnType()).getActualTypeArguments()[0]; // NOSONAR
```
when we use a raw types: `public ListenableFuture myListener(MyMessage myMessage)` ?

**Comment by garyrussell** [comment]
Yes, it is there to handle complex return types. Yes, we should protect for that case.

**Comment by rjbaucells** [comment]
@garyrussell Yes, the issue is related to a POJO method returning a `ListenableFuture<X>` value.

@artembilan Yes the code is throwing a NPE since `resultArg.getReturnType()` returns `null` in this case.

As a note, the issue is not present in version `2.1.4.RELEASE`.

**Comment by artembilan** [comment]
OK. We give up.

Please, share a simple code we need to have on our side to reproduce.
The `handler.getMethod().getGenericReturnType()` does not return null from the `HandlerAdapter`.

**Comment by rjbaucells** [comment]
This is a sample scenario were the bug is present. I have some code that returns a `CompletableFuture<>` (code that I cannot modify at the moment) and I have created a `@RabbitListener` method that invokes it, something like:

```java
@RabbitListener
public ListenableFuture<OutputMessage> listenerWrapper(InputMessage input) {
    // convert CompletableFuture<> to ListenableFuture<>
    return new CompletableToListenableFutureAdapter<>(existingImplementation(input));
}

private CompletableFuture<OutputMessage> existingImplementation(InputMessage input) {
    // existing code
}
```

The code works as expected using version 2.1.4.RELEASE, it fails on version 2.1.6.RELEASE.

The listener method is invoked at [MessageListenerAdapter.java line 292](https://github.com/spring-projects/spring-amqp/blob/f4b653006dff8e5a28efc1c89656d7481408161d/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/MessageListenerAdapter.java#L292) and the return value is processed as:

```java
Object result = invokeListenerMethod(methodName, listenerArguments, message);
if (result != null) {
    handleResult(new InvocationResult(result, null, null), message, channel);
}
else {
    logger.trace("No result object given - no result to handle");
}
```

As you can see the `handleResult()` is invoked with an `InvocationResult` having `null` value for the `returnType` field (third parameter) [line 294](https://github.com/spring-projects/spring-amqp/blob/f4b653006dff8e5a28efc1c89656d7481408161d/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/MessageListenerAdapter.java#L294).

`handleResult()` checks return value is an instance of `ListenableFuture` [AbstractAdaptableMessageListener line 320](https://github.com/spring-projects/spring-amqp/blob/f4b653006dff8e5a28efc1c89656d7481408161d/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/AbstractAdaptableMessageListener.java#L320) and adds a callback calling `asyncSuccess()` and `asyncFailure()` methods.

`asyncSuccess()` assumes the `InvocationResult` instance has a `returnType` set without checking the value. Note that `returnType` parameter is marked as `@Nullable` in constructor definition:

```java
public InvocationResult(Object result, Expression sendTo, @Nullable Type returnType) {
    this.returnValue = result;
    this.sendTo = sendTo;
    this.returnType = returnType;
}
```
`asyncSuccess()` implementation is throwing a NPE at [line 349](https://github.com/spring-projects/spring-amqp/blob/f4b653006dff8e5a28efc1c89656d7481408161d/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/AbstractAdaptableMessageListener.java#L349) exiting the method and failing to ACK the message:

```java
Type returnType = ((ParameterizedType) resultArg.getReturnType()).getActualTypeArguments()[0];
```

Let me know if you need more information about it.

**Comment by garyrussell** [comment]
I am still a bit confused - your original post says...

>The (ParameterizedType) resultArg.getReturnType() will always return null since ParameterizedType instance is created at MessageListenerAdapter line 294:

...but the MLA is not involved with `@RabbitListener`.

**Comment by rjbaucells** [comment]
@garyrussell my specific scenario is not exactly the one I described, I tried to put an example where a `ListenableFuture` return value is used but as you mentioned the `MessageListenerAdapter` is not used in that case. Sorry, I just though that the scenario I put as an example would trigger the same problem.

I have a custom listener method discovery mechanism not using `@RabbitListener` annotations, for those listener methods I create a `DirectMessageListenerContainer` or `SimpleMessageListenerContainer` container instance (based on custom criteria). For the message listener adapter I have an implementation that inherits from `MessageListenerAdapter` that invokes the the actual bean listener method (returning a `CompletableFuture<?>`) and converts the result value to a `ListenableFuture<>` instance using the `CompletableToListenableFutureAdapter<>` wrapper. That's why my code returning a `ListenableFuture<>` instance gets invoked from the `MessageListenerAdapter` code:

```java
Object result = invokeListenerMethod(methodName, listenerArguments, message);
if (result != null) {
    handleResult(new InvocationResult(result, null, null), message, channel);
}
else {
    logger.trace("No result object given - no result to handle");
}
``` 

And the above described issue is triggered.

**Comment by rjbaucells** [comment]
Just a question...

Is there any reason why listener methods do not support `CompletableFuture<>` as a return value?

**Comment by artembilan** [comment]
Because the `ListenableFuture` has been introduced before Java 8 and even it is good for Java 6 compatibility as it stay for Spring 4.x line.

As you noticed it is not so hard to adapt `CompletableFuture` into the `ListenableFuture` via `CompletableToListenableFutureAdapter`. Therefore it doesn't worth to pursue support for so easy wrapping functionality.
