### ISSUE TITLE
Update MDC handling in the AmqpAppender

### ISSUE THREAD

**Issue by egusev** [spring-projects/spring-amqp#1014]
For proper logging additional information of calling paramenters/context is required. The best option to do that is MDC. 
The current implementation copies MDC into the message's headers.
The main problem with it that Rabbit has limited size for header and default size is pretty small - 131072 bytes (128 kb). unlike of message body it can't be fragmented https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit/issues/159

so the proposals are:
1. remove (or make it optional) serializating MDC into headers
2. add possibility to add MDC into the message body
3. make AmqpAppender.sendEvent protected (instead of private) to allow override it to do custom stuff

**Comment by egusev** [comment]
I mean this class org.springframework.amqp.rabbit.log4j2.AmqpAppender

**Comment by egusev** [comment]
update: JsonLayout already serializes MDC into the body. so only points 1 and 3 are actual

**Comment by garyrussell** [comment]
Sounds reasonable; contributions are welcome: https://github.com/spring-projects/spring-amqp/blob/master/CONTRIBUTING.adoc
