### ISSUE TITLE
support any number of the cluster node config

### ISSUE THREAD

**Issue by lmx1989219** [spring-projects/spring-amqp#1022]
due to my apps is already running online and the rabbitmq server is running in single node.
now i want rabbitmq server is running in cluster,but i wan't restart my apps.

## currently right conf
````
spring.rabbitmq.addresses=192.168.103.34:5672,192.168.73.129:5672,192.168.73.130:5672
````

## i needed conf
````
spring.rabbitmq.host=192.168.103.34
spring.rabbitmq.port=5672
````

currently,the client could't auto detect other nodes in cluster and when network failure it can't auto swithing to health node.
if can did,i wannot to rewrite my conf and restart my apps.

thanks.

**Comment by garyrussell** [comment]
This is a limitation of the RabbitMQ Java amqp-client; it has nothing to do with Spring.

You should ask such questions on the rabbitmq-users Google group.

**Comment by lmx1989219** [comment]
@garyrussell  thanks
