### ISSUE TITLE
Automatic reconnection when RMQ is not available when sending the first message.

### ISSUE THREAD

**Issue by dmkost** [spring-projects/spring-amqp#1038]
Hello. Please help me with the problem.

The problem is related to automatic reconnection.
I use Spring Boot 2.1.3, but it happens in version 2.1.6 and RabbitMQ with spring-boot-starter-amqp

Bin RabbitTemplate looks like this:
```java
public final class ExtendedRabbitTemplate extends RabbitTemplate {

    public ExtendedRabbitTemplate(final ConnectionFactory connectionFactory) {
        super(connectionFactory);
    }

    @Override
    protected final void replyTimedOut(final String correlationId) {
        throw new RpcTimeoutException(String.format("Timeout on receiving reply to message with correlation id = %s", correlationId));
    }

}
```
```java
    @Bean
    public RabbitTemplate rabbitTemplate(ConnectionFactory connectionFactory) {
        RabbitTemplate template = new ExtendedRabbitTemplate(connectionFactory);
        template.setMessageConverter(producerJackson2MessageConverter());
        template.setReplyTimeout(properties.getRpcMessagesReplyTimeout());
        return template;
    }
```

We use the following method to support rpc:
![Снимок экрана 2019-06-28 в 15 32 09](https://user-images.githubusercontent.com/25726407/60342382-fe8a8080-99b9-11e9-90e2-a604f8100d8a.png)
We want to use Direct ReplyTo with pseudo queues.

The scenario in which the normal behavior RabbitTemplate
1. Initial state: Internet is available (access to the RMQ), the application is not running.
2. Run the application.
3. We send several messages and get answers. All is well.
4. Turning off the Internet (access to the RMQ).
5. We send several messages and get an exception after a timeout. Everything is also OK.

Scenario in which abnormal behavior is detected:
1. Initial state: the Internet is not available(access to the RMQ), the application is not running
2. Run the application.
3. We send several messages and get exceptions org.springframework.amqp.AmqpConnectException: java.net.ConnectException: Connection refused.
4. Turn on the Internet (access to the RMQ)
5. We send several messages and receive exceptions after a timeout. Therefore, no reconnection occurs.

The error is as follows:
![Снимок экрана 2019-06-28 в 15 15 38](https://user-images.githubusercontent.com/25726407/60343845-ddc42a00-99bd-11e9-9e19-248246d361a2.png)

I tried to figure out what was happening and found the following. The selected code block is executed 1 time at the first call. If the access was to the rabbit, then the first condition in the chain is satisfied. If we get an exception, then we get into the second condition block. Everything happens because at the first message(RQM is not available) we get replyAddress = null and usingFastReplyTo = false.
![Снимок экрана 2019-06-28 в 15 10 40](https://user-images.githubusercontent.com/25726407/60343595-05ff5900-99bd-11e9-9f16-1c1dd495f36d.png)

I hope this is enough.

**Comment by garyrussell** [comment]
You are correct - thanks for the analysis.

**Comment by OctoSenya** [comment]
Hi!
It seem's like the cause of problem is SocketException wrapped in AmqpIOException, not AmqpConnectException.

**Comment by garyrussell** [comment]
What operating system/JDK? For me it gets a 

`Caused by: java.net.ConnectException: Connection refused (Connection refused)`

**Comment by garyrussell** [comment]
The problem with using `AmqpIOException` is that a queue declaration failure gives that exception; we will have to dig down to the root cause.

**Comment by OctoSenya** [comment]
Ubuntu 18.04
openjdk version "1.8.0_212"
I'm getting this exception when trying to send message with internet disabled.
![image](https://user-images.githubusercontent.com/47979440/60446054-30554e80-9c29-11e9-8783-4c884f9d0581.png)

**Comment by garyrussell** [comment]
OK
