### ISSUE TITLE
[BUG] Many listening threads that cannot be closed.Because there are too many threads open, causing crash

### ISSUE THREAD

**Issue by kitsrc** [spring-projects/spring-amqp#1044]
**Affects Version(s):** \<Spring AMQP version> 2.1.2.RELEASE
## Bug report
Many listening threads that cannot be closed.
Causes the application to take up too many system resources.
These processes are generated every time rabbitTemplate.convertSendAndReceive(...) but never closed.
Therefore, I need your support, thank you.

![image](https://user-images.githubusercontent.com/23493090/60791924-461dc300-a197-11e9-9719-2edd895cdf60.png)
::
名称: rabbitTemplate#0-consumerMonitor-1
状态: java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@13fd3c0e上的TIMED_WAITING
总阻止数: 2, 总等待数: 63

堆栈跟踪: 
sun.misc.Unsafe.park(Native Method)
java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

::
---

**Comment by garyrussell** [comment]
Your issue is not clear; please provide much more information together with a small application that clearly shows what the issue is.

**Comment by kitsrc** [comment]
I have already targeted the specific reason, there is a problem with the configuration between the connection pool and the virtual host.

**Comment by rafihap** [comment]
@tpxn do you remember what configuration you changed? I've the same problem
