### ISSUE TITLE
Async @RabbitListener does not handle AmqpRejectAndDontRequeueException

### ISSUE THREAD

**Issue by peterlgh7** [spring-projects/spring-amqp#1058]
## Bug report

spring-amqp version: 2.1.7-RELEASE

The documentation for asynchronous @RabbitListener states:

> If the async result is completed with an AmqpRejectAndDontRequeueException, the message will not be requeued.

The following example listener instead requeues the message and loops indefinitely:

```java
import org.springframework.amqp.rabbit.annotation.RabbitListener;
import org.springframework.stereotype.Component;
import org.springframework.util.concurrent.ListenableFuture;
import org.springframework.util.concurrent.SettableListenableFuture;

@Component
public class Listener {

  @RabbitListener(queues = "example")
  public ListenableFuture<Void> receive(User user) {
    System.out.println(user);
    SettableListenableFuture<Void> future = new SettableListenableFuture<>();
    future.setException(new RuntimeException());
    return future;
  }
}
```

The problem seems to lie on the `AbstractAdaptableMessageListener`. The requeue flag is true regardless of the exception type:
https://github.com/spring-projects/spring-amqp/blob/8336d4ed3f86519d2a9870217b6bb84a9b99bf3f/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/AbstractAdaptableMessageListener.java#L380-L388

Moreover, not an issue for me now, but the documentation also states:

> By default, the message will be requeued, unless the container’s defaultRequeueRejected property is set to false

And from the snippet above, it doesn't seem to be true either.

**Comment by peterlgh7** [comment]
That was a really quick fix! I was actually interested in contributing here. In the future, should I clearly state it in the bug report?

**Comment by artembilan** [comment]
Right, typically we are very open for Contribution, but right now it is a rush to make as much fixes as possible for upcoming release on Monday. Thank you for proposal anyway: there are still some issues you can pick up for Contribution!

**Comment by peterlgh7** [comment]
Ok, I will take a look at those soon. This one just looked like such an easy one for my first contribution :) ...

**Comment by garyrussell** [comment]
>In the future, should I clearly state it in the bug report?

Thanks; yes, in general, it's best to note that you intend to contribute a fix.

As Artem said, though, this time we are so close to the next release I picked it up right away.

**Comment by peterlgh7** [comment]
I understand, it was better that way for me too, I needed this fix ASAP for a few projects using spring-amqp.

**Comment by garyrussell** [comment]
I released it today; 2.1.8 is in maven central.

**Comment by xetra11** [comment]
@garyrussell 
Can you point out how to configure this? Within `.properties` file? I googled everywhere but was not able to find the point where I can set it to `false`

**Comment by artembilan** [comment]
Does this work for you: `spring.rabbitmq.listener.simple.default-requeue-rejected = false`?

See https://docs.spring.io/spring-boot/docs/2.2.0.M6/reference/html/appendix.html#integration-properties
