### ISSUE TITLE
Async @RabbitListener does not handle MessageConverter exceptions

### ISSUE THREAD

**Issue by peterlgh7** [spring-projects/spring-amqp#1065]
## Bug report

spring-amqp version: 2.1.8-RELEASE

I'm using `spring.rabbitmq.listener.simple.acknowledge-mode: MANUAL` as per the documentation:

> The listener container factory must be configured with AcknowledgeMode.MANUAL so that the consumer thread will not ack the message; instead, the asynchronous completion will ack or nack the message when the async operation completes.

Using the following simple example. If I publish an invalid JSON string, the message is never acked/nacked.

```java
import org.springframework.amqp.rabbit.annotation.RabbitListener;
import org.springframework.stereotype.Component;
import org.springframework.util.concurrent.ListenableFuture;
import org.springframework.util.concurrent.SettableListenableFuture;

@Component
public class Listener {

  @RabbitListener(queues = "example")
  public ListenableFuture<Void> receive(User user) {
    System.out.println(user);
    SettableListenableFuture<Void> future = new SettableListenableFuture<>();
    future.set(null);
    return future;
  }
}
```

After a bit of debugging I get to:
https://github.com/spring-projects/spring-amqp/blob/2bf1117a7b305d7a0dc9e18c8118cad9ae6ae43d/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/MessagingMessageListenerAdapter.java#L130-L133

Where, in the case of an exception being thrown by the `toMessagingMessage`, the `invokeHandlerAndProcessResult`(which is the one to correctly handle acks/nacks for async listeners) never gets called. Afterwards, the message is simply not acked/nacked because the container's acknowledge mode is MANUAL.

**Comment by garyrussell** [comment]
Hmmm - this is not just limited to async reply types - any manual-ack listener behaves this way.

We have an error handler (default) that treats message conversion (and some others) as fatal, but we only NACK if the ackmode is AUTO.

These exceptions must always be considered fatal because they occur before the listener ever gets them.

**Comment by peterlgh7** [comment]
You are right that it happens also without for non-async listeners. My project is currently using manual acks and suffering from the same problem. I passes to async in part because I thought the problem may not exist(since async listeners actually handle acks for me).

**Comment by garyrussell** [comment]
I find it rather intriguing that nobody else has reported this over the years; there are a lot of people using MANUAL acks, but I guess conversion exceptions must be rare.

Anyway, thanks for reporting it. I issued a PR and 2.1.9 is scheduled for early September, but I can do a release sooner than that if you are desperate to get a fix.

**Comment by peterlgh7** [comment]
Not really desperate, conversion exceptions are indeed rare. We haven't had these exceptions in normal operation, but it does happen during development, when the publisher side(embedded devices that don't share our messaging POJO libraries) is defining new messages. It is rather annoying cause the messages remain unacked and the only way to clean the queue is stopping the client and then deleting.

I wonder why so many people are still using MANUAL acks. My personal use case for manual acks was that I needed to process the messages and ack only after successful processing(I need at-least-once-delivery). Synchronously doing so proved slow and the only way to increase throughput was increasing the listener concurrency. With not so fast processing times, we needed too much concurrency and Rabbit wasn't liking so many open channels. A few months ago, the async listener was already available, but it didn't support ListenableFuture<Void>, it only supported sending a reply to some exchange, so I stuck to MANUAL acks.

All of this to say that maybe it would be good to explain in the documentation how async listeners can solve some of the use cases for MANUAL acks and make life easier for developers. Manual acks can get tricky for developers non familiar with RabbitMQ. At least from documentation, it looks like acks on a channel should be done in single-threaded fashion, which I imagine not everyone is aware of.

**Comment by garyrussell** [comment]
I agree; I probably shouldn't have said "a lot of people". In most cases, auto ack is sufficient - except for when you need concurrency within a single listener thread (and, of course, with the new async return types).

Actually, while the Rabbit team generally warn about thread-safety in a channel basicAck/Nack/Reject operations are thread-safe; they are protected by `_channelMutex` in `ChannelN.transmit()`.

**Comment by peterlgh7** [comment]
Hmm, interesting. Looking at ChannelN code it looks like basicPublish is also protected by the `_channelMutex`. Does it mean there are no real concerns about thread-safety then? Even if that was the case, it would feel weird for me to assume thread-safety by looking at the implementation, when the documentation warns against it. Maybe I'll see if there is some issue in their repo regarding this. Thank you for the tip, and for the quick fix again.
