### ISSUE TITLE
Add an enum to select the type of publisher confirms

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-amqp#1067]
Simplify Boot auto-configuration.

`SIMPLE` and `CORRELATED`.

See https://github.com/spring-projects/spring-boot/pull/17848#discussion_r313381228

**Comment by snicoll** [comment]
Thanks Gary. If none is a valid value, we probably need an option in the enum for that as well.

**Comment by garyrussell** [comment]
Good point!

**Comment by snicoll** [comment]
Can we please reopen this issue? I think deprecated methods that take a boolean are ignoring the boolean value and set the enum to enable the feature. If you call those methods with `false` they'll actually enable the behaviour.

**Comment by garyrussell** [comment]
Doh
