### ISSUE TITLE
'concurrentConsumers' cannot be more than 'maxConcurrentConsumers'

### ISSUE THREAD

**Issue by gaecfov** [spring-projects/spring-amqp#1080]
the system throw IllegalArgumentException "'concurrentConsumers' cannot be more than 'maxConcurrentConsumers'" when i call the "setConcurrency" in "SimpleMessageListenerContainer".

bacause call the method "setConcurrentConsumers" before the method "setMaxConcurrentConsumers" in "setConcurrency"

for example:

setp 1:
set concurrentConsumer:1
set maxConcurrentConsumer:1

setp 2:
call setConcurrency("2-5")

**Comment by artembilan** [comment]
OK. I think we need to change order of method:
```
if (separatorIndex != -1) {
	setConcurrentConsumers(Integer.parseInt(concurrency.substring(0, separatorIndex)));
	setMaxConcurrentConsumers(
			Integer.parseInt(concurrency.substring(separatorIndex + 1, concurrency.length())));
}
```

To stabilize the API.

**Comment by gaecfov** [comment]
thanks for your response.
