### ISSUE TITLE
improvement debug logging 

### ISSUE THREAD

**Issue by ksaker** [spring-projects/spring-amqp#1087]
Now messages logs here: 

https://github.com/spring-projects/spring-amqp/blob/ccd177cbb86aa85dc22baae6294624292663906b/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitTemplate.java#L2293

But, it would be more correct to log the message after applying postprocessors 

here 
https://github.com/spring-projects/spring-amqp/blob/ccd177cbb86aa85dc22baae6294624292663906b/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitTemplate.java#L2315

**Comment by artembilan** [comment]
Confirmed.

Please, consider to contribute that fix.

Thanks

**Comment by ksaker** [comment]
Shure. How I can do it?

**Comment by artembilan** [comment]
Something like this: https://github.com/spring-projects/spring-amqp/blob/master/CONTRIBUTING.adoc#fork-the-repository

Thank you for your offer!

**Comment by garyrussell** [comment]
I disagree with moving it, but I wouldn't be averse to a second log after the MPPs are applied (only if there are MPPs).
