### ISSUE TITLE
Support RabbitTemplate.invoke using publisher connection.

### ISSUE THREAD

**Issue by jimmy384** [spring-projects/spring-amqp#1106]
I configure the RabbitTemplate use publisher connection.
```
RabbitTemplate.setUsePublisherConnection(true);
```
When I using RabbitTemplate.convertAndSend, the publisher connection is used. It works.

But when I using invoke like below, the publisher connection is not use.
```
rabbitTemplate.invoke(operations -> {
    operations.convertAndSend("exchange", "queue", message);
    return operations.waitForConfirms(1000);
});
```

rabbitTemplate.invoke always not use the publisher connection, I think rabbitTemplate should provide a overload method invoke(OperationsCallback<T> action, boolean usePublisherConnection) to indicate use the publisher connection.

**Comment by garyrussell** [comment]
Thanks for reporting; it's a bug.

**Comment by jimmy384** [comment]
> Thanks for reporting; it's a bug.

I want to know if this bug fixed. What's the behavior of below code.
```
rabbitTemplate.invoke(operations -> {
    operations.convertAndSend("exchange", "queue", message);
    return operations.waitForConfirms(1000);
});
```
Is invoke method always use publisher connection if RabbitTemplate's usePublisherConnection is true? @garyrussell

**Comment by jimmy384** [comment]
OK, thanks.

**Comment by garyrussell** [comment]
As a workaround; you can set that flag to false and inject the publisher factory directly.

```java
RabbitTempalte template = new RabbitTemplate(cachingConnectionFactory.getPublisherConnectionFactory());
```
