### ISSUE TITLE
Missing setAdmin and setMessageConverter in SimpleMessageListenerContainer

### ISSUE THREAD

**Issue by bojanv55** [spring-projects/spring-amqp#1110]
Just upgraded to 2.2.0 version, and I'm missing now this methods in class `SimpleMessageListenerContainer` that I used before:

`setMessageConverter` and `setRabbitAdmin`.

Why they got removed? What to use instead?

**Comment by garyrussell** [comment]
`setMessageConverter` was deprecated in 2.1 and removed in 2.2 - it should never have been part of the public API. See the 2.1 javadocs

	/**
	 * Set the {@link MessageConverter} strategy for converting AMQP Messages.
	 * @param messageConverter the message converter to use
	 * @deprecated - this converter is not used by the container; it was only
	 * used to configure the converter for a {@code @RabbitListener} adapter.
	 * That is now handled differently. If you are manually creating a listener
	 * container, the converter must be configured in a listener adapter (if
	 * present).
	 */
	@Deprecated
	public void setMessageConverter(MessageConverter messageConverter) {

Again, see the 2.1 javadoc for `setRabbitAdmin`

	/**
	 * Set the {@link AmqpAdmin}, used to declare any auto-delete queues, bindings
	 * etc when the container is started. Only needed if those queues use conditional
	 * declaration (have a 'declared-by' attribute). If not specified, an internal
	 * admin will be used which will attempt to declare all elements not having a
	 * 'declared-by' attribute.
	 * @param amqpAdmin The admin.
	 * @deprecated in favor of {@link #setAmqpAdmin(AmqpAdmin)}
	 */
	@Deprecated
	public final void setRabbitAdmin(AmqpAdmin amqpAdmin) {
		setAmqpAdmin(amqpAdmin);
	}

Generally, when you get deprecation warnings, you should address them in the version where the warning is presented.

If you need help with where to set the converter, please show your configuration.

**Comment by bojanv55** [comment]
OK. Thanks for explanations. I will try to do this according to javadoc above.

I just used standard setters on `SimpleMessageListenerContainer` here.
