### ISSUE TITLE
RabbitMq message getting lost

### ISSUE THREAD

**Issue by MkJha** [spring-projects/spring-amqp#1119]
Environment :
spring-boot-starter-amqp : 2.1.4
Platform : Windows 10
Java : 11

I am using RabbitTemplate.convertAndSend , it does not throw any exception or error but message is not published to the exchange (direct exchange in this case). There is no error in rabbitMq server log as well. Any Help would be appreciated.

Sample metrics ::

No of message sent ------------------>Found in Queue
25--------------------------- ----------->19
100-------------------------------------->69
100--------------------------------------->80

Note: Metrics is just to show that, there is no pattern for number of missing messages.

**Comment by garyrussell** [comment]
You need to show your code and configuration (queues, exchanges, bindings).

**Comment by MkJha** [comment]
I had two different message producer sending notification to their respective exchange queue(bound with routing key) while having a single rabbitTemplate instantiated. Both the producer were setting the default exchange using rabbitTemplate.setExchange(), hence leading to default exchange inconsistency.
Before ,
Producer 1,
rabbitTemplate.setExchange("EXCH1");
rabbitTemplate.setRoutingKey(routingKey1);
rabbitTemplate.convertAndSend(notificationObj);

Producer 2,
rabbitTemplate.setExchange("EXCH2");
rabbitTemplate.setRoutingKey(routingKey2);
rabbitTemplate.convertAndSend(notificationObj);

Now on, directly using rabbitTemplate.convertAndSend(exchangeName, routingKey, resourceNotificationTypeObj) and as expected, it resolved the issue. 

Appreciate your quick reply.
