### ISSUE TITLE
Jackson2JsonMessageConverter should give similar result to Spring MVC

### ISSUE THREAD

**Issue by ryandanielspmc** [spring-projects/spring-amqp#1123]
Spring AMQP 2.2.0.RELEASE

## Bug report

Given the following Kotlin class:

```kotlin
data class SomeData(
    val foo: String,
    val abc: String
) : Serializable {
    companion object {
        private const val serialVersionUID = 1L
    }
}
```
Spring MVC, via `AbstractJackson2HttpMessageConverter`, is able to properly deserialize the object and give an instance of `SomeData` to REST controller methods.

`Jackson2JsonMessageConverter`, on the other hand is not able to properly deserialize this object into an instance and pass it to `@RabbitListener` methods as a parameter.

As a workaround, I have to do the following in order for `Jackson2JsonMessageConverter` to properly deserialize `SomeData`:
```kotlin
data class SomeData(
    val foo: String,
    val abc: String
) : Serializable {
    companion object {
        private const val serialVersionUID = 1L

        @JsonCreator
        @JvmStatic
        fun fromJson(json: String) = ObjectMapper().readValue<SomeData>(json)
    }
}
```
The expectation is that if `AbstractJackson2HttpMessageConverter` does not require a `@JsonCreator`, then `Jackson2JsonMessageConverter` should not require it either.

**Comment by artembilan** [comment]
Another workaround is just inject the same `ObjectMapper` into that `Jackson2JsonMessageConverter` which you have in the mentioned Spring MVC configuration.

The point is that an internally created `ObjectMapper`  doesn't come with well-known module, one of which is a `KotlinModule` for those `data` classes conversion.

**Comment by ryandanielspmc** [comment]
@artembilan Even with the `ObjectMapper` having the Kotlin module loaded into the `Jackson2JsonMessageConverter`, it still does not work without the `@JsonCreator`.

**Comment by artembilan** [comment]
Hm... somehow does not make sense to me. If some `ObjectMapper` works in Spring MVC, the same instance should work here as well

**Comment by ryandanielspmc** [comment]
I spent a lot of time stepping through the code of what gets executed in `ObjectMapper` from Spring MVC and Spring AMQP. The code (in `ObjectMapper`) is a bit convoluted, but a different path seems to get taken when called by Spring AMQP, thought I did not determine why. When called from Spring AMQP it ends up (obviously) taking the last resort of looking for a creator method.

**Comment by artembilan** [comment]
Right. But anyway. Can you really confirm that the same `ObjectMapper` provided for Spring MVC doesn't work for Spring AMQP?
Would you mind to share some simple project to let us to reproduce and play with?

**Comment by ryandanielspmc** [comment]
The code I posted above looks like it should go into an endless recursive loop due to again calling the deserializer that called the creator function, but seems not to due to how a different method of deserialization gets chosen:
```kotlin
        @JsonCreator
        @JvmStatic
        fun fromJson(json: String) = ObjectMapper().readValue<SomeData>(json)
```

**Comment by ryandanielspmc** [comment]
@artembilan I tried the following configuration, and **without** the `@JsonCreator`:
```kotlin
@Autowired
private lateinit var objectMapper: ObjectMapper

@Bean
fun messageConverter(): MessageConverter = Jackson2JsonMessageConverter(objectMapper)
```
It does not work, I get the same kind of error that I get above without `@JsonCreator`:
```
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `package.SomeData` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('{
  "foo" : "ABC",
  "abc" : "xyz"
}')
```

**Comment by ryandanielspmc** [comment]
@artembilan Unfortunately, as I am currently very busy with the project around where this issue is happening, I don't have time to create a sample project, but ...I have narrowed it down to where the decision on which kind of deserialization takes place:

File:
`com.fasterxml.jackson.databind.deser.BeanDeserializer`

Method:
```java
@Override
public Object deserialize(JsonParser p, DeserializationContext ctxt) throws IOException
{
    // common case first
    if (p.isExpectedStartObjectToken()) {
        if (_vanillaProcessing) {
            return vanillaDeserialize(p, ctxt, p.nextToken());
        }
        // 23-Sep-2015, tatu: This is wrong at some many levels, but for now... it is
        //    what it is, including "expected behavior".
        p.nextToken();
        if (_objectIdReader != null) {
            return deserializeWithObjectId(p, ctxt);
        }
        return deserializeFromObject(p, ctxt);
    }
    return _deserializeOther(p, ctxt, p.getCurrentToken());
}
```
The condition `if (p.isExpectedStartObjectToken())` is false when execution originates from `AbstractJackson2HttpMessageConverter` before the `@JsonCreator` is executed, but the condition is true when it is executed because of the `@JsonCreator`.

It seems that `p.isExpectedStartObjectToken()` should be true when executed the first time.

**Comment by artembilan** [comment]
>  no String-argument constructor/factory method to deserialize from String value `('{
  "foo" : "ABC",
  "abc" : "xyz"
}')`


It sounds like the body of incoming AMQP message not a serialized JSON, but encoded String....

Unfortunately without anything to reproduce we have nothing to do here.
And this sounds more like a StackOverflow question then problem in the framework...

**Comment by ryandanielspmc** [comment]
I don't believe this to be a simple configuration problem. `Jackson2JsonMessageConverter` is supposed to work out of the box based on the type of the method parameter. So, if I have the following two things configured, my understanding is that it should simply just work:

```kotlin
@RabbitListener(queues = ["some-queue"])
fun processScanRequest(s: SomeData): String {
```
```kotlin
@Bean
fun messageConverter(): MessageConverter = Jackson2JsonMessageConverter(defaultObjectMapper)
```
And, as I pointed out, Spring MVC is able to do exactly this scenario without any special configuration.

I can attempt to create a sample project in the next few days.

**Comment by artembilan** [comment]
That's all right. but what is a producer side for that `some-queue`?
How do you send your data over the network for AMQP?

Yes, time still permits. 

Thank you for your effort so far!

And also I believe your Kotlin project would be great candidate for contributing into Spring AMQP Samples project ! 😄

**Comment by ryandanielspmc** [comment]
We are sending the message with `AmqpTemplate.convertAndSend()` with the message body being an object serialized into a JSON string, and we set the `MessageProperties.contentType` to `MessageProperties.CONTENT_TYPE_JSON`.

**Comment by ryandanielspmc** [comment]
An additional note:

On the receiving end, when debugging, the Type ID header is `String`, but the inferred type message property is `package.SomeData` (as it should be), and I stepped through the default type mapper in debug mode to verify that it returns a type for `package.SomeData` and not `String`, verifying that the returned value is as expected, a type for `package.SomeData`.

**Comment by artembilan** [comment]
> with the message body being an object serialized into a JSON string

Well, sounds like you do it yourself: you don't rely on the converter injected into the mentioned `AmqpTemplate`. And it fills like you use there similar `Jackson2JsonMessageConverter`, which sees that string and encode it when it does its own stuff before building `byte[]`.
So, this way on the consumer side we indeed have that plain string to deserialize. And this already has nothing to compare with Spring MVC.


Would you mind to check what `MessageConverter` is used over there on producer side?

Thanks

**Comment by ryandanielspmc** [comment]
According to the Spring AMQP docs:

https://docs.spring.io/spring-amqp/docs/current/reference/html/

> By default, the inferred type information will override the inbound TypeId and related headers created by the sending system. This lets the receiving system automatically convert to a different domain object.

Therefore, even though the Type ID header is `String`, the inferred type in the properties should take precedence. And in my case the inferred type in the properties is `SomeData`, so this is what converted should be trying to convert to.

In my case the `MessageConvertor` is `Jackson2JsonMessageConverter` on the producer side.

**Comment by artembilan** [comment]
Ok! So, we are close!

The problem is on the producer side. You send a string, not a POJO. And that string is serialized as JSON into bytes, not your POJO. Since you say that you serialize by yourself, consider don’t use that Jackson converter, but Simple one instead which is default one in the `RabbitTemplate` Anyway. Right now you send a string for JSON serializer and guess what you get from it: an encoded string. Since it is just a string, there is no way to deserialize it into a POJO back. It can be deserialized only to A String.

**Comment by ryandanielspmc** [comment]
@artembilan Turns out that you were right. What I was not expecting was that the message converter was going to wrap `"abc"` to `"\"abc\""`. What I was expecting was that the `String` value would get passed as-is to the body and not be modified. But this is not the case.

Sorry for this mix-up.
