### ISSUE TITLE
Feature: add the ability to recover messages when using batching using Retry Interceptors

### ISSUE THREAD

**Issue by andrebrait** [spring-projects/spring-amqp#1127]
**Affects Version(s):** 2.2.1.RELEASE
---

## Enhancement

When using batching in listeners with a `List` parameter, if an exception is thrown, there's no way to recover from it using a retry interceptor since 

https://github.com/spring-projects/spring-amqp/blob/e6e659afeb4906414fb7e3a4b2add902ae928220/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/StatelessRetryOperationsInterceptorFactoryBean.java#L59 

throws a `ClassCastException`.

What I think could be done is to have either some other way to use a retry recoverer or detect the proper argument type (i.e. List of messages instead of a single message) and loop over them, although I'm not sure what would be the best approach

**Comment by garyrussell** [comment]
Yes, we should fix this, but bear in mind that "recovering" from a failed delivery of batch is difficult because the framework (and hence the recoverer) has no inherent knowledge which record in the batch failed.

**Comment by andrebrait** [comment]
Thanks for this, guys!
