### ISSUE TITLE
Missing maxFrameHeadroom check on cause.getMessage()

### ISSUE THREAD

**Issue by thpeng** [spring-projects/spring-amqp#1130]
https://github.com/spring-projects/spring-amqp/blob/c57fd6434ffbba00a9f14afb4ce25135330e8437/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/retry/RepublishMessageRecoverer.java#L155

The RepublishMessageRecoverer truncates the stacktrace if its length exceeds the maxFrameHeadroom configured. This behavior should also apply with cause.getMessage() to allow republishing a failed message with a long message.

**Comment by garyrussell** [comment]
Interesting; it's rather unusual to have a large message but I agree.

I wonder, though, which is more important - keeping as much message as possible or as much stack trace? i.e. what to do if both are too big.

**Comment by thpeng** [comment]
I would suggest prioritizing the stacktrace. The cause was calling toString on a big object graph and inserting it in the cause message, which is not optimal.
