### ISSUE TITLE
Enhancement: Configurer for RabbitTemplate similar to SimpleRabbitListenerContainerFactoryConfigurer

### ISSUE THREAD

**Issue by ryandanielspmc** [spring-projects/spring-amqp#1135]
## Enhancement

Often, you might want multiple `RabbitTemplate` instances with slight variations on the default properties. `RabbitAutoConfiguration` configures a default `RabbitTemplate` with settings pre-populated from `RabbitProperties.Template` and `RabbitProperties.Retry`.  But, as far as I know, you cannot get multiple unique instances from `RabbitAutoConfiguration`. It would be great to have something similar to `SimpleRabbitListenerContainerFactoryConfigurer` that would allow applying the default settings to custom-made `RabbitTemplate` instances.

**Comment by garyrussell** [comment]
Auto configuration is a [spring boot](https://github.com/spring-projects/spring-boot) feature and not part of the projects it auto configures.
