### ISSUE TITLE
PluginBuilderFactory instead of PluginFactory for Log4j2 Appender

### ISSUE THREAD

**Issue by Scip88** [spring-projects/spring-amqp#1142]
**Affects Version(s):** v2.2.2.RELEASE

---

## Use of PluginBuilderFactory instead of PluginFactory for Log4j2 AmqpAppender 

I'm tryin to extends **AmqpAppender** to customize method **postProcessMessageBeforeSend**.
I'm tryin to avoid **copy & paste** of static method **createAppender** (annotated with **PluginFactory**) but it's not possibile.

Is there another solution or simple code to create a method annotated with **PluginFactory** ?

I suggest to use **Builder** and Annotation **PluginBuilderFactory**

[Extend Log4j2 Appenders](https://logging.apache.org/log4j/log4j-2.2/manual/extending.html#Appenders)
[Log4j2 Plugin Builder](https://logging.apache.org/log4j/2.x/manual/extending.html#Plugin_Builders)

**Comment by garyrussell** [comment]
Sounds reasonable. Contributions are welcome.

**Comment by Scip88** [comment]
I hope to work on that enhancement as soon as possible

**Comment by artembilan** [comment]
Reopened. Closed by mistaken issue link in other commit.
