### ISSUE TITLE
Missing instanceOf BigInteger

### ISSUE THREAD

**Issue by stefsp7** [spring-projects/spring-amqp#1147]
https://github.com/spring-projects/spring-amqp/blob/fb32210e50bde73b0edc3d60f2c6463eba2f75a5/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/support/DefaultMessagePropertiesConverter.java#L186

**Comment by stefsp7** [comment]
Is there any specific reason for not including instanceOf BigInteger?

**Comment by garyrussell** [comment]
The [`amqp-client` (`ValueWriter.writeFieldValue()`)](https://github.com/rabbitmq/rabbitmq-java-client/blob/12c085b7f549835a67590496de1ad5e8b24a2842/src/main/java/com/rabbitmq/client/impl/ValueWriter.java#L128-L218) doesn't support it - it **does** support `BigDecimal` by writing the `scale` in a byte and the `unscaledValue.intValue()`.
