### ISSUE TITLE
Incorrect content encoding in Message's toString

### ISSUE THREAD

**Issue by shark300** [spring-projects/spring-amqp#1152]
Version Spring AMQP 2.2.2.RELEASE

I would like to log incoming JSON type message but Message's toString() uses default charset. It causes an encoding issue in the log messages in a dockerized environment. 

In my humble opinion it should use the contentEncoding of the message in this (and similar) cases.

To reproduce: https://github.com/shark300/amqpMessageToStringBug

**Comment by garyrussell** [comment]
I agree it should be changed, but why can't you do your own `byte[] -> String` when logging?

**Comment by shark300** [comment]
Hi @garyrussell, yes, I did it, but to log the whole message is the most elegant way instead of logging messageProperties and payload separately.

```java
@RabbitListener(queues = INCOMING_QUEUE)
public void receive(Message message, @Payload Content content) {
  logger.info("Received message {}", message);
  messageProcessorStuff.process(content);
}
```
