### ISSUE TITLE
RabbitTestHarness on proxied Beans

### ISSUE THREAD

**Issue by Iggle** [spring-projects/spring-amqp#1157]
Currently, if a Listener Bean contains transactional methods it is wrapped in a cglib proxy, as expected, to ensure transactionality. RabbitTestHarness can thus not produce functioning spies of the Listener as all the proxy's methods are final.

Possible solutions would be to either:

* Return a Mock with AdditionalAnswers.delegatesTo() instead of spy()
* Unwrapping the proxy before spying with Advised.getTargetSource().getTarget()

While only functionally a spy in behaviour, having a look at [SpyDefinition.createSpy](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-test/src/main/java/org/springframework/boot/test/mock/mockito/SpyDefinition.java#L88) for @SpyBean, the first option seems to be an effective way to go.

If desired, I could draft up a merge request.

**Comment by garyrussell** [comment]
>If desired, I could draft up a merge request.

Yes, please; thanks in advance.
