### ISSUE TITLE
executeListener method in AbstractMessageListenerContainer now too generic

### ISSUE THREAD

**Issue by huehnerlady** [spring-projects/spring-amqp#1161]
## Bug report

Version: 2.2.3.RELEASE

Hi,
We have a problem when using the executeListener Method in `AbstractMessageListenerContainer.java`
Before with 2.1.10, it was a nice signature with signature `protected void executeListener(Channel channel, Message messageIn)`
Now with 2.2.3 it is [`protected void executeListener(Channel channel, Object data)`.](https://github.com/spring-projects/spring-amqp/pull/1033/files/bd7eeb623fc23b233478ce1d60de165084932257#diff-22d665a9e03fe5324a13e998b57ed24dR1343)

With looking into the code it seems that the `data` can be a List of Messages or a Message.

We have loads of problems with that, as we have to change all the methods of the Listeners extending from that Container and now have to add an additional check as we cannot be certain anymore that this is what we expect it to be.

Suggestion: Have 2 methods, one with signature `protected void executeListener(Channel channel, Message messageIn)` and one with signature `protected void executeListener(Channel channel, List<Message> messages)`

**Comment by garyrussell** [comment]
It was not anticipated that users would override that low-level method. Please can you explain your use cases? There may be better solutions.

**Comment by huehnerlady** [comment]
The code has been there for quite some time, we did not create the functionality recently but keep it and maintain the Spring version.

We basically use it to get to the messageProperties as early as possible and put some properties into the MDC for logging purposes. We need it as early as possible to be able to e.g. include spring logging in our tracing.

The adaption of the executeListeners Method was doing that job fine. But now we ran into problems as the override did not work anymore due to signature changes.

**Comment by garyrussell** [comment]
You should not have subclassed the container for such a trivial task; the proper place for such logic is in an after receive `MessagePostProcessor`.

	/**
	 * Set {@link MessagePostProcessor}s that will be applied after message reception, before
	 * invoking the {@link MessageListener}. Often used to decompress data.  Processors are invoked in order,
	 * depending on {@code PriorityOrder}, {@code Order} and finally unordered.
	 * @param afterReceivePostProcessors the post processor.
	 * @since 1.4.2
	 * @see #addAfterReceivePostProcessors(MessagePostProcessor...)
	 */
	public void setAfterReceivePostProcessors(MessagePostProcessor... afterReceivePostProcessors) {

**Comment by huehnerlady** [comment]
@garyrussell Many thanks. We adapted our code now.
