### ISSUE TITLE
Feature: Option for @RabbitListener to Not Retry on Fatal Exception

### ISSUE THREAD

**Issue by ryandanielspmc** [spring-projects/spring-amqp#1168]
Based on my understanding, and what I saw, the `@RabbitListener` will retry even if a thrown exception is fatal per `ConditionalRejectingErrorHandler.DefaultExceptionStrategy`.  There are many cases where it does not make sense to retry, like when the JSON in the message is not valid. There is no reason to try again, in this case. Therefore, it would be great for there to be an option, or some other way, out-of-the-box, to not reprocess the incoming message if the `@RabbitListener` errored in a way that does not make sense to retry.

The current workaround I came up with was to implement a `RabbitRetryTemplateCustomizer` which has an injected `FatalExceptionStrategy`, and customize the retry policy to check if the exception is fatal.

**Comment by artembilan** [comment]
I would say we can't make such an unconditioanl decision in the framework and some customized `RetryPolicy` is the way to go.
We definitely may provide some out-of-the-box `RetryPolicy` based on your condition, but it won't make it as a default one anyway.

Does it make sense?

Thank you!

**Comment by ryandanielspmc** [comment]
> Does it make sense?

Yes, absolutely that makes sense. I am not suggesting that no-retry be the default.

**Comment by artembilan** [comment]
Good. So, feel free to contribute such a custom `RetryPolicy`!

**Comment by marcussatelis** [comment]
https://stackoverflow.com/a/75652127

**Comment by marcusvoltolim** [comment]
https://stackoverflow.com/a/75652127

**Comment by artembilan** [comment]
@marcusvoltolim ,

Do you suggest that `SimpleRetryPolicy` covers such a use-case?

**Comment by marcusvoltolim** [comment]
From what I understand, yes!  Just add a Map with the exceptions and false so that they are not retried.

```
@param retryableExceptions the map of exceptions that are retryable based on the * map value (true/false).
```

**Comment by artembilan** [comment]
Good. Closing as `Not Planned`.

**Comment by marcusvoltolim** [comment]
Other option:

```
public class IgnoreFatalErrorSimpleRetryPolicy extends SimpleRetryPolicy {
  private static final FatalExceptionStrategy exceptionStrategy =
      new ConditionalRejectingErrorHandler.DefaultExceptionStrategy();

  public IgnoreFatalErrorSimpleRetryPolicy(int maxAttempts) {
    super(maxAttempts);
  }

  @Override
  public boolean canRetry(RetryContext context) {
    return !exceptionStrategy.isFatal(context.getLastThrowable()) && super.canRetry(context);
  }

}
```
