### ISSUE TITLE
Enable TLS v.1.2.

### ISSUE THREAD

**Issue by johanrhodin** [spring-projects/spring-amqp#1169]
No reason to force users to use v.1.1 anymore: https://github.com/spring-projects/spring-amqp/blob/f7b7bedefc3de6149d5d1222c3c30d6eac40d6e2/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/RabbitConnectionFactoryBean.java#L128

**Comment by garyrussell** [comment]
?

You can already set your own version.

https://github.com/spring-projects/spring-amqp/blob/f7b7bedefc3de6149d5d1222c3c30d6eac40d6e2/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/RabbitConnectionFactoryBean.java#L184-L191

If you mean change the default, we can do that in a future release.

**Comment by garyrussell** [comment]
We can simply remove the default and let the amqp-client select it's own preferred default.

https://github.com/spring-projects/spring-amqp/blob/f7b7bedefc3de6149d5d1222c3c30d6eac40d6e2/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/RabbitConnectionFactoryBean.java#L732-L737

**Comment by johanrhodin** [comment]
Letting the client select sounds good 👍 
I assume spring-amqp is by default using a newer than https://github.com/rabbitmq/rabbitmq-java-client/pull/145 client?

**Comment by garyrussell** [comment]
That is correct; but that logic is already in place due to the `sslAlgorithmSet` being true only if the user actually calls the setter - the default on the field in this class is never used.

**Comment by johanrhodin** [comment]
Thank you very much! 🙏
