### ISSUE TITLE
How to turn off RabbitAdmin to automatically create a queue?

### ISSUE THREAD

**Issue by ZShUn** [spring-projects/spring-amqp#1183]
How to turn off RabbitAdmin to automatically create a queue? I do n’t want the program to create these relationships

**Comment by garyrussell** [comment]
?

Just don't declare the `Queue` as a `@Bean`.

**Comment by ZShUn** [comment]
According to what you said, it will not be automatically created, but will there be other risks?

**Comment by ZShUn** [comment]
Because I am not particularly familiar with spring-rabbitmq source code

**Comment by garyrussell** [comment]
>but will there be other risks?

No; the only purpose of declaring a queue as a `@Bean` is so that the admin will automatically provision it on the broker.

**Comment by ZShUn** [comment]
Thank you
