### ISSUE TITLE
TestHarness listener key does not parse expression language

### ISSUE THREAD

**Issue by winster** [spring-projects/spring-amqp#1195]
There are 2 issues.

1. TestHarness listener key is not parsed

`@RabbitListener(id="${rabbitmq.myEventsListenerId}",queues="${rabbitmq.myEventsQueueName}") 
public void receive(String message) {
....`

above is my listener. In my spring boot integration test, when I tried to retrieve the listener with the actual value of configuration property, I get null. On troubleshoot, I noticed that the testharness has my listener but with the key `${rabbitmq.myEventsListenerId}`. 

Unfortunately it is not parsed. My guess is about order of annotation processing. 
My TestConfiguration is as follows.

@TestConfiguration
@RabbitListenerTest(capture = true)
public class RabbitTestConfiguration 

and in my integration test, I autowired TestHarness. 

2. If I hard code the "id" and "queues" name, I get listener successfully. But upon convertAndSend, I get error, "no listener for routing-key"

Sample application to simulate the issue is here 
https://github.com/winster/spring-rabbit-test

**Comment by garyrussell** [comment]
The `id` property cannot be set using a placeholder; it is similar to a bean name and not variable.

Please show your entire test case.

**Comment by winster** [comment]
@garyrussell thank-you. What do you think about second issue mentioned. 

`@Test
    public void receiver2() {
        listener2 = harness.getSpy(myConfigParameters.getReceiver2ListenerId());
        assertNotNull(listener2);
        String message = getMessage();
        testRabbitTemplate.convertAndSend(myConfigParameters.getReceiver2ExchangeName(),
                myConfigParameters.getReceiver2RoutingKey(), message);
        verify(listener2).receive(message);
    }`

Whole example is here https://github.com/winster/spring-rabbit-test

**Comment by garyrussell** [comment]
Please learn GitHub markdown.

**Comment by garyrussell** [comment]
In future; please don't provide examples using Lombok; we don't care for it and it takes me time to get the example to a state where I can test it.

**Comment by garyrussell** [comment]
As [the documentation](https://docs.spring.io/spring-amqp/docs/2.2.6.RELEASE/reference/html/#test-template) says

>It currently only supports routing by queue name. 

This works

```java
	@RabbitListener(id = "receiver2", queues = "${rabbitmq.receiver2QueueName}")
	public void receive(String message) {
		log.info("Listener2: receive :: {}", message);
	}
```

and

```java
	@Test
	public void receiver1() throws JsonProcessingException {
		listener1 = harness.getSpy(myConfigParameters.getReceiver1ListenerId());
		assertNotNull(listener1);
		String message = getMessage();
		testRabbitTemplate.convertAndSend(myConfigParameters.getReceiver1QueueName(), message);
		verify(listener1).receive(message);
	}

	@Test
	public void receiver2() throws JsonProcessingException {
		listener2 = harness.getSpy(myConfigParameters.getReceiver2ListenerId());
		assertNotNull(listener2);
		String message = getMessage();
		testRabbitTemplate.convertAndSend(myConfigParameters.getReceiver2QueueName(), message);
		verify(listener2).receive(message);
	}
```

**Comment by winster** [comment]
Thank you for the input. I agree that it works as given in documentation. Hence closing the issue.
