### ISSUE TITLE
No connection recovery on broker restart

### ISSUE THREAD

**Issue by patkovskyi** [spring-projects/spring-amqp#1197]
**Affects Version(s):** 2.2.0

We've encountered a production outage that was triggered by a restart of a broker.

The sequence of events:
1. Broker restarted.
2. Log from producer: `Channel shutdown: connection error; protocol method: #method<connection.close>(reply-code=320, reply-text=CONNECTION_FORCED - broker forced connection closure with reason 'shutdown', class-id=0, method-id=0)`
3. Log from producer: `org.springframework.amqp.AmqpIOException: java.net.SocketTimeoutException: connect timed out`

It's interesting that one of our producer hosts actually did reconnect automatically. I can see `Created new connection: SpringAMQP#34e35055:2/SimpleConnection@14fc7b94 [delegate=amqp://ge@10.12.24.110:5672/ge, localPort= 48358]` log from that host right after `Channel shutdown`. However, other hosts did not reconnect and recovered only after we redeployed the application.

This was our RabbitTemplate configuration:

            CachingConnectionFactory connectionFactory =
                    new CachingConnectionFactory();
            connectionFactory.setAddresses(AWSUtils.resolveDnsName(dnsName));
            connectionFactory.setUsername(user);
            connectionFactory.setPassword(password);
            connectionFactory.setVirtualHost(virtualHost);
            connectionFactory.setPublisherConfirms(true);
            connectionFactory.setRequestedHeartBeat(30);

            RabbitTemplate template = new RabbitTemplate(connectionFactory);
            template.setExchange(exchange);
            return template;

And we only use the `send` method in RabbitTemplate.

The question is: is there anything we can change in our client configuration to avoid such a problem in the future?

We consider adding `connectionFactory.getRabbitConnectionFactory().setAutomaticRecoveryEnabled(true);` but I see that documentation discourages this: https://docs.spring.io/spring-amqp/reference/html/#_connection_factory_changes 
Would this help us? And what are the downsides exactly?

**Comment by garyrussell** [comment]
>recovered only after we redeployed the application.

This is most likely an application problem.

If these are producer only applications, we won't try to reconnect until the next `RabbitTemplate.send()` operation.

If it didn't reconnect, it means your app didn't perform any more publishing operations after the failure.

If your application stops sending, using an auto-recovered connection won't help; you'll just have an idle connection.

Applications with consumers will reconnect automatically.

**Comment by patkovskyi** [comment]
@garyrussell wow, thanks for your swift reply!

I can see that we were attempting to send messages after `Channel shutdown` and this is when we encountered timeouts.

But I feel like I figured out why it happened: broker instances weren't just restarted, they were terminated and then respawned (AWS ECS). Their IPs changed, and producer could not know about the new IP addresses, because this is how it discovered brokers: `connectionFactory.setAddresses(AWSUtils.resolveDnsName(dnsName));`

You may close the issue. Now I'm wondering if Rabbit provides any dynamic broker discovery capabilities (Rabbit newbie here). 🙇‍♂️

**Comment by garyrussell** [comment]
Best place to ask questions like that is on the `rabbitmq-users` Google group.
