### ISSUE TITLE
RabbitMQ Listener Issue: Consumer received fatal exception on startup and com.rabbitmq.client.ShutdownSignalException: channel error

### ISSUE THREAD

**Issue by ramki434** [spring-projects/spring-amqp#1205]
**Affects Version(s):** \<Spring AMQP version>

---

**Comment by garyrussell** [comment]
You need to provide much more information, logs etc; so wee can tell what happened.

**Comment by ramki434** [comment]
[Logs.txt](https://github.com/spring-projects/spring-amqp/files/4692667/Logs.txt)
Thank you for responding to the issue. I've attached more logs on the issue. Please let me know, if anything is required.

**Comment by garyrussell** [comment]
>no queue 'springCloudBus.anonymous.dyryxaHMSgKLbkRwYI8uIA' in vhost 'b3ba3b9c-385e-4d81-85b2-cda09d691387'

What version of spring-cloud-bus are you using?

This was a problem with early versions with auto-delete anonymous queues; this was fixed in recent spring-cloud-stream versions.

With older versions, you need a policy on the RabbitMQ server to make sure that queues matching these names have the `queue_master_locator` argument set to `client_local`.

See https://www.rabbitmq.com/ha.html#queue-master-location

**Comment by ramki434** [comment]
Thank you for details. We've this version in our POM file for spring cloud bus version.
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.5.2.RELEASE</version>
		
		  <dependency>
			<groupId>com.rabbitmq</groupId>
			<artifactId>amqp-client</artifactId>
			<version>4.1.1</version>
		</dependency>

**Comment by garyrussell** [comment]
Spring Boot 1.5.x is no longer supported; the last 1.5.x version was 1.5.22 released August 2019. 1.5.2 is over 3 years old.

In any case; whatever version of spring-cloud supported by that boot version certainly doesn't have the fix. You need to set the master locator policy on the broker as I described, to avoid this issue.

But you really need to upgrade to supported software versions.

**Comment by ramki434** [comment]
Sure, will do. Thank you so much for help!
