### ISSUE TITLE
Make listener acknowledge-mode: auto with retries work with Future

### ISSUE THREAD

**Issue by IvanKaloyanov** [spring-projects/spring-amqp#1206]
#### Enhancement

Currently, I have a listener of type 'simple' with a retry policy and `acknowledge-mode: auto` that listens for messages from multiple queues. The `onMessage` handler simply submits a task into a ForJoinPool that does the heavy lifting and leaves the listener's thread free so that it can consume a new message. Example:
```
public void onMessage(Message message) {
    ...
    MyForkJoinPool.pool().submit(
        () -> {
            CompletableFuture<Work> future = worker.doTheWork(message);
        }
    );
    ...
}
```
The problem here is that when the task is submitted to the pool and `onMessage` is executed then the message is acknowledged no matter if the `future` is completed exceptionally or not in fact it could be `acknowledged` before even the `future` is completed one way or another since it's executed somewhere within the ForkJoin thread pool.

My solution for this currently is to switch to `acknowledge-mode: manual` and do something like:
```
public void onMessage(Message message, Channel channel, @Header(AmqpHeaders.DELIVERY_TAG) {
    ...
    MyForkJoinPool.pool().submit(
        () -> {
            CompletableFuture<Work> future = worker.doTheWork(message);
            future.whenCompleteAsync((work, exception) -> {
                try {
                    if (exception == null) {
                        channel.basicAck(tag, true);
                    } else {
                        // Handle the N retry before the negative acknowledgement 
                        channel.basicNack(tag, false,true);
                    }
                } catch (IOException e) {
                    // Handle IO exception
                }
            });
        }
    );
    ...
}
```
Which is an okay solution but then the N retry logic in case of the `future` being completed exceptionally should also be applied manually which at this point moves a lot of the logic into the `custom space` which I think may lead to more 1 off solutions like this being applied and making it a mess for no reason. In the meantime is there a more reasonable solution and what's the suggested way to achieve the same retry logic when you deal with `acknowledge-mode: auto` without throwing an exception like in this case?

Spring version 2.1.X
Java version: 8

**Comment by garyrussell** [comment]
I don't think the container can help in this case; as soon as you go async in the listener, you are on your own.

You could make it a little easier to bear by using [spring-retry](https://github.com/spring-projects/spring-retry) (`RetryTemplate`) within your `doTheWork` and only complete the future after success, or the retries are exhausted.

**Comment by IvanKaloyanov** [comment]
Update:
The way I did it is by using `Failsafe` Example:
```
public void onMessage(Message message, Channel channel, @Header(AmqpHeaders.DELIVERY_TAG) {
...
    Failsafe.with(new RetryPolicy()
            .onRetriesExceeded(event -> {
                channel.basicReject(tag, false);
            })
            .withMaxRetries(maxAttempts)
            .withBackoff(initialInterval, maxInterval, ChronoUnit.MILLIS, multiplier))
        .with(MyForkJoinPool.pool())
            .onSuccess(event -> {
                channel.basicAck(tag, false);
            })
            .getStageAsync(() -> worker.doTheWork(message));
...
}
```

**Comment by garyrussell** [comment]
👍
