### ISSUE TITLE
Jackson Message Conversion - Allow Abstract Classes

### ISSUE THREAD

**Issue by ryandanielspmc** [spring-projects/spring-amqp#1215]
I am using Kotlin, and I have a sealed class as follows:
```kotlin
@JsonDeserialize(using = FooDeserializer::class)
sealed class Foo
data class FooA(val s: String) : Foo()
data class FooB(val l: Long) : Foo()
```
Then `FooDeserializer` handles determining whether to instantiate `FooA` or `FooB`. The Jackson `ObjectMapper` handles this situation no problem. But, the message conversion functionality around `Jackson2JsonMessageConverter` does not allow abstract classes, which is what `Foo` gets compiled to.

Please allow abstract classes and interfaces in the Jackson message conversion functionality. Let it be the responsibility of the Jackson `ObjectMapper` to handle this situation instead of preventing it.

**Comment by garyrussell** [comment]
We will have to give this some thought; simply relaxing the the check could break many applications; currently, if the `@RabbitListener` parameter is abstract, we fall back to using type information in headers. so we probably need some option.

**Comment by garyrussell** [comment]
Can you provide more information? I just tested it with this code and it worked fine...

```java
	@Test
	void customAbstractClass() {
		byte[] bytes = "{\"field\" : \"foo\" }".getBytes();
		MessageProperties messageProperties = new MessageProperties();
		messageProperties.setInferredArgumentType(Baz.class);
		Message message = new Message(bytes, messageProperties);
		ObjectMapper mapper = new ObjectMapper();
		mapper.registerModule(new BazModule());
		Jackson2JsonMessageConverter j2Converter = new Jackson2JsonMessageConverter(mapper);
		Baz baz = (Baz) j2Converter.fromMessage(message);
		assertThat(((Qux) baz).getField()).isEqualTo("foo");
	}

	public interface Baz {

	}

	public static class Qux implements Baz {

		private String field;

		public Qux(String field) {
			this.field = field;
		}

		public String getField() {
			return this.field;
		}

		public void setField(String field) {
			this.field = field;
		}

	}

	public static class BazDeserializer extends StdDeserializer {

		public BazDeserializer() {
			super(Baz.class);
		}

		@Override
		public Object deserialize(JsonParser p, DeserializationContext ctxt)
				throws IOException, JsonProcessingException {

			p.nextFieldName();
			return new Qux(p.nextTextValue());

		}

	}

	public static class BazModule extends SimpleModule {

		public BazModule() {
			addDeserializer(Baz.class, new BazDeserializer());
		}

	}

```

It works because of this logic...

```java
	@Override
	public JavaType toJavaType(MessageProperties properties) {
		JavaType inferredType = getInferredType(properties);
		if (inferredType != null
			 && ((!inferredType.isAbstract() && !inferredType.isInterface()
					|| inferredType.getRawClass().getPackage().getName().startsWith("java.util")))) {
			return inferredType; // we don't return here because Baz is abstract
		}

		String typeIdHeader = retrieveHeaderAsString(properties, getClassIdFieldName());

		if (typeIdHeader != null) {
			return fromTypeHeader(properties, typeIdHeader);
		}

		if (hasInferredTypeHeader(properties)) {
			return fromInferredTypeHeader(properties); // this is the result because there are no type headers
		}

		return TypeFactory.defaultInstance().constructType(Object.class);
	}
```

I can see it would no work if type headers exist with incorrect information. Is that your case?

**Comment by ryandanielspmc** [comment]
That is correct. My situation is that the message comes from a different application. And that application has its own domain classes that are used to serialize the message, then the fully qualified domain class from that application is in the header. Then, on the receiving application, when the `@RabbitListener` method parameter is an abstract class, it falls back to the type in the header, which is not in the receiving application, and give an error.

**Comment by garyrussell** [comment]
OK; thanks. I think we can handle it by adding `objectMapper.canDeserialize()` on the inferred method parameter type.

I just need to figure out the best place to do that test without breaking anything...
