### ISSUE TITLE
Use default Spring ResourceLoader ?

### ISSUE THREAD

**Issue by dnovitski** [spring-projects/spring-amqp#1217]
**Affects Version(s):** All versions

---

## Enhancement

In [RabbitConnectionFactoryBean.java](https://github.com/spring-projects/spring-amqp/blob/master/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/RabbitConnectionFactoryBean.java#L125) the `PathMatchingResourcePatternResolver` is used. This doesn't seem to work with a Spring Boot app that populates custom ResourceLoaders. 

As an example, we have a very simple custom `base64:` resource loader, and we'd like to use this to load the trust store and key store resources. Is it possible to change the resolver into Spring's default ResourceLoader so that it can use all of the application's currently populated resource loaders?

**Comment by garyrussell** [comment]
That would be a breaking change - would it be sufficient to allow you to inject a resource loader of your choice?

**Comment by dnovitski** [comment]
I think it can work. But this would be best discussed with the Spring Boot team that handles the RabbitMQ autoconfiguration to allow for this behavior of using the 'default' Spring ResourceLoader so that no application changes are needed besides updating the spring boot dependency.

**Comment by dnovitski** [comment]
The current workaround I am using is manually creating the RabbitConnectionFactoryBean and manually resolving the truststore and keystore resources.

**Comment by garyrussell** [comment]
I don't think Boot can auto configure it because existing users might be relying on the pattern matching features.

Perhaps it could in 2.4.

cc/ @snicoll WDYT?

**Comment by snicoll** [comment]
@garyrussell I am not sure I understood the problem. As far as I can tell the default is to use `PathMatchingResourcePatternResolver` so only a user that has customized the root `ResourceLoader` of the  context would be broken. 

IMO, it is more consistent to use the `ResourceLoader` of the context (unless I've missed something). I agree that we should only do that in a new feature release.

**Comment by garyrussell** [comment]
@snicoll 

>I am not sure I understood the problem. 

The problem is the some existing application might have `spring.rabbitmq.ssl.truststore=/foo/**/my.truststore` - unlikely, perhaps, but possible.

Changing the loader to one that doesn't match ant patterns would break this app.

I do not think this will be an issue, as long as the change is in 2.4; I'll add a setter.
