### ISSUE TITLE
Could not find batching properties in rabbit:listener-container schema

### ISSUE THREAD

**Issue by ShambuGIT** [spring-projects/spring-amqp#1218]
**Affects Version(s):** 2.2.8

---
## Question

I have upgraded the spring rabbit amqp version to 2.2.8 and could not find the batch properties in the latest schema definition http://www.springframework.org/schema/rabbit/spring-rabbit.xsd under rabbit:listener-container.

Please point me the correct URL schema to refer for defining batch properties under the rabbit:listener-container tag. Or Is this something deprecated and we have to create org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer bean manually instead of using rabbit:listener-container tag.

**Comment by garyrussell** [comment]
The schema was fixed in 2.3 (next release); we need to back-port those changes.

**Comment by garyrussell** [comment]
Merged as https://github.com/spring-projects/spring-amqp/commit/0d544f19638d42288011d59fcc94ae1b2d82523f

**Comment by ShambuGIT** [comment]
Thanks Gary. Should we need to wait for next release to consume this? Or is that schema available for 2.2.8 version. if yes, I could not see batch-enabled property.

**Comment by garyrussell** [comment]
It will be fixed in 2.2.9, which is not currently scheduled for release until July 22.

In the meantime you can just wire up the container as a `<bean/>` instead and set the properties that way.

**Comment by ShambuGIT** [comment]
Thank you Gary.
