### ISSUE TITLE
SMLC - addQueueNames calls queuesChanged() multiple times

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-amqp#1246]
See https://stackoverflow.com/questions/63669250/dynamic-add-queue-consumers-spring-issue

**Comment by rajat-g** [comment]
Hi @garyrussell Sir. Any updates when will it get fixed in older versions or it will be available only in the new version.

**Comment by garyrussell** [comment]
As you can see from the commits above, it is fixed on the master (2.3.x), 2.2.x, and 2.1.x branches. The next releases are currently sheduled for Sept 16: https://github.com/spring-projects/spring-amqp/milestones
