### ISSUE TITLE
AbstractJackson2MessageConverter.standardCharset is used inconsistently

### ISSUE THREAD

**Issue by bjmi** [spring-projects/spring-amqp#1253]
**Affects Version(s):** 2.2.11.RELEASE

---
`AbstractJackson2MessageConverter.standardCharset` should be initialized with `true` because default charset is used by default.
And corr. mutator https://github.com/spring-projects/spring-amqp/blob/4f76b2bc8dd44ac30209450ee19cd090f7ecb179/spring-amqp/src/main/java/org/springframework/amqp/support/converter/AbstractJackson2MessageConverter.java#L128-L130
should be replaced with
`this.standardCharset = this.defaultCharset.equals(DEFAULT_CHARSET);`

If there is another intent with current behavior then just close this issue.

**Comment by garyrussell** [comment]
It's not clear what you mean. Perhaps the variable name is misleading; it should be called `utf8Encoding` and it should be `true` by default since that is the default if users don't set it.

Jackson uses UTF-8 in `writeValueAsBytes`.

```java
    @SuppressWarnings("resource")
    public byte[] writeValueAsBytes(Object value)
        throws JsonProcessingException
    {
        ByteArrayBuilder bb = new ByteArrayBuilder(_jsonFactory._getBufferRecycler());
        try {
            _configAndWriteValue(_jsonFactory.createGenerator(bb, JsonEncoding.UTF8), value);
        } catch (JsonProcessingException e) { // to support [JACKSON-758]
            throw e;
        } catch (IOException e) { // shouldn't really happen, but is declared as possibility so:
            throw JsonMappingException.fromUnexpectedIOE(e);
        }
        byte[] result = bb.toByteArray();
        bb.release();
        return result;
    }
```

**Comment by bjmi** [comment]
We mean the same :)
Thank you again.
