### ISSUE TITLE
Which version of amqp is supported by spring 3.0.5 ?

### ISSUE THREAD

**Issue by sayeduzzamancuet** [spring-projects/spring-amqp#1255]
Hi,
I am struggling to find any reference to understand which version of amqp will fully work with spring 3.0.5. 
I have noticed I can use rabbit annotations in spring boot,  but in spring 3.0.5 annotations do not work.  So, how do you create listeners in case of spring 3.0.5 without annotation, and how they trigger a method call when a message arrives in the queue. Also, how do you start a listener in this version of spring? I am in a very critical situation since I can not migrate the project to spring 4+ or can not move to spring boot.

**Comment by garyrussell** [comment]
Spring 3.0 is has not been supported for several years; even Spring 4.3.x will not be supported after this year.

The last version of spring-amqp to use Spring 3.0.x (3.0.7) was the 1.1.4.RELEASE from 2013. There was no annotation support back then; you either had to implement `MesssageListener` or you could use the `MessageListenerAdapter` to invoke POJO methods with converted payloads.

https://docs.spring.io/spring-amqp/docs/1.1.4.RELEASE/reference/html/amqp.html#d4e258
