### ISSUE TITLE
@QueueBinding support multi-consumer profiling

### ISSUE THREAD

**Issue by fengshunli** [spring-projects/spring-amqp#1256]
![image](https://user-images.githubusercontent.com/18587688/95821539-b208b700-0d5c-11eb-95df-7b81b1d1d927.png)

queues support spel but  can not automatically create queues

**Comment by fengshunli** [comment]
If you let queues split() automatically create non-existent queues and listen

**Comment by fengshunli** [comment]
> It's not clear what you are asking for. `@QueueBinding` only supports one queue. So `split()` makes no sense there.
> 
> If `spring.profiles.active=foo`, I see queue `foo_sqliteQueueName` created with no problems.

  If you let queues split() automatically create non-existent queues and listen

**Comment by garyrussell** [comment]
See #1257
