### ISSUE TITLE
@QueueBinding  support multi-queue listening as queues does

### ISSUE THREAD

**Issue by fengshunli** [spring-projects/spring-amqp#1257]
@RabbitListener(queues =("#{'${spring.rabbitmq.queues}'.split(',')}")   QueueBinding does not support #{'${spring.rabbitmq.queues}'.split(',')  this approach

Current solutions
![image](https://user-images.githubusercontent.com/18587688/95841219-ad9dc780-0d77-11eb-952a-d1a7d4f388e2.png)

 QueueBinding or queuesToDeclare is there a better way to support multi-queue monitoring

**Comment by garyrussell** [comment]
Duplicate of https://github.com/spring-projects/spring-amqp/issues/1256

`@QueueBinding` is not intended for such sophisticated configuration, use a `Declarables`. bean instead.
