### ISSUE TITLE
Missing spring-rabbit 2.1.18.RELEASE

### ISSUE THREAD

**Issue by jirijanak** [spring-projects/spring-amqp#1266]
14 days ago there has been released Spring Boot 2.1.18.RELEASE https://github.com/spring-projects/spring-boot/releases/tag/v2.1.18.RELEASE

Until now there is no spring-rabbit 2.1.18.RELEASE in https://mvnrepository.com/artifact/org.springframework.amqp/spring-rabbit 

Can that be build and released, please?

**Comment by garyrussell** [comment]
You are confusing Spring Boot and Spring AMQP versions; the versions are not aligned.

Spring Boot 2.1.18 uses spring-rabbit 2.1.17

**Comment by garyrussell** [comment]
https://github.com/spring-projects/spring-boot/blob/fdf3b18697b171f4e184dbd8ced4461d0114cf22/spring-boot-project/spring-boot-dependencies/pom.xml#L169
