### ISSUE TITLE
"Foo" deserialized as "LinkedHashMap" if listener method argument is "List<Foo>"

### ISSUE THREAD

**Issue by andrebrait** [spring-projects/spring-amqp#1279]
**Affects Version(s):** 2.2.12 (but probably there since 2.2.9)

---

## Context

I have an application that publishes a list of objects (as a JSON array) into an exchange, and a service that consumes those lists of objects. This service has a method similar to this:

```java
@RabbitListener(queue="myqueue")
public void readList(List<Foo> foos) {
    doSomething(foo);
}
```

I attempted upgrading from Spring Boot 2.3.1 to 2.3.3 and then to 2.3.6. With both of them, I started seeing error messages related to the objects inside `List<Foo> foos` being instances of `LikedHashMap` instead of `Foo`. I confirmed that this is the case by remotely debugging. For some reason, I think the generic type is not being used correctly. Reverting back to Spring-AMQP 2.2.7 makes it work again and the objects are indeed instances of `Foo`.

**Comment by garyrussell** [comment]
Are these discrete messages containing a `List<Foo>`?

Or are using using batching (either producer- or consumer-created batches - the latter being added in 2.2)?

Can you show your application.yml/properties?

**Comment by garyrussell** [comment]
Also show your message converter bean - we did add support for deserializing Abstract classes, which had some side effects in the message converter if incorrectly configured.

**Comment by andrebrait** [comment]
Each message is a single `List<Foo>`. There's no batching involved in this particular listener.

I do have batching in another place and that is working fine (argument is a `List<Foo>` and each message is a `Foo`).
I do use a few different message listeners in this application, but the one used in this listener is the following bean:

```java
    public SimpleRabbitListenerContainerFactory defaultRabbitListenerContainerFactory(
            ConnectionFactory connectionFactory,
            SimpleRabbitListenerContainerFactoryConfigurer configurer,
            MessageRecoverer retryRecoverer) {
        var factory = new SimpleRabbitListenerContainerFactory();
        configurer.configure(factory, connectionFactory);
        factory.setErrorHandler(new LoggingConditionalRejectingErrorHandler());
        factory.setAdviceChain(RetryInterceptorBuilder.stateless()
                .recoverer(retryRecoverer)
                .maxAttempts(1)
                .build());
        return factory;
    }
```

Everything else is very boring (mostly Spring Boot autoconfiguration) :smile: 

```java
    @Bean
    public MessageConverter jsonMessageConverter(ObjectMapper objectMapper) {
        return new Jackson2JsonMessageConverter(objectMapper);
    }

    @Bean
    public Jackson2ObjectMapperBuilderCustomizer objectMapperBuilderCustomizer() {
        return builder -> builder.featuresToEnable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
    }
```

**Comment by andrebrait** [comment]
No idea if this changes anything, but the full annotation is:

```java
@RabbitListener(
            queues = "myqueue",
            containerFactory = "defaultRabbitListenerContainerFactory",
            concurrency = "1-${some.property:2}")
    public void readList(List<Foo> foos) {
}```

I checked to see if that's the container factory being used, just in case, and it is.

**Comment by andrebrait** [comment]
The messages are published as the list of objects, raw, like:

```json
[{"prop1":1,"prop2":"avocado"},{"prop1":2,"prop2":"bananas"}]
```

**Comment by garyrussell** [comment]
Let me investigate; it might be an unintended side effect of adding support for abstract classes (in 2.2.8, so suspicious).

**Comment by garyrussell** [comment]
Confirmed it's a bug - since `List` is abstract, the new code doesn't think it can be deserialized.

The workaround is
```java
converter.setAlwaysConvertToInferredType(true);
```

**Comment by andrebrait** [comment]
> Confirmed it's a bug - since `List` is abstract, the new code doesn't think it can be deserialized.
> 
> The workaround is
> 
> ```java
> converter.setAlwaysConvertToInferredType(true);
> ```

Just to be clean, it does deserialize it to a `List`, but a `List<LinkedHashMap>`, not `List<Foo>`.

**Comment by garyrussell** [comment]
Understood; the new code just looks at the top level class and, since `List` is abstract it thinks it can't be deserialized.

I tested with this

```java
@SpringBootApplication
public class Rgh1279Application {

	public static void main(String[] args) {
		SpringApplication.run(Rgh1279Application.class, args);
	}

	@RabbitListener(queues = "foo")
	void listen(List<Foo> in) {
		System.out.println(in);
		System.out.println(in.get(0).getClass());
	}

	@Bean
	MessageConverter converter() {
		Jackson2JsonMessageConverter converter = new Jackson2JsonMessageConverter();
		converter.setAlwaysConvertToInferredType(true);
		return converter;
	}

	@Bean
	public ApplicationRunner runner(RabbitTemplate template) {
		return args -> {
			template.convertAndSend("foo", new ArrayList<>(List.of(new Foo("baz"), new Foo("qux"))));
		};
	}

	public static class Foo {

		private String bar;

		public Foo() {
		}

		public Foo(String bar) {
			this.bar = bar;
		}

		public String getBar() {
			return this.bar;
		}

		public void setBar(String bar) {
			this.bar = bar;
		}

		@Override
		public String toString() {
			return "Foo [bar=" + this.bar + "]";
		}

	}

}
```

and got the list of linked has maps; setting the boolean corrects the problem.

**Comment by andrebrait** [comment]
Thanks for the quick fix. Looking forward to the next minor release.

**Comment by garyrussell** [comment]
Wednesday with Boot to follow Thursday: https://calendar.spring.io/
