### ISSUE TITLE
Starting DirectMessageListenerContainer does not addConsumerToRestart when consumer failed to start

### ISSUE THREAD

**Issue by davsclaus** [spring-projects/spring-amqp#1296]
**Affects Version(s):** 2.3.2

## Bug report

I am using a `DirectMessageListenerContainer` to consume from RabbitMQ via spring-rabbit. 

When I start the listener container via its `start` method, and the consumer fail to start due to for example queue does not exists. The spring-rabbit logs at DEBUG level 

    Queue not present, scheduling consumer SimpleConsumer [queue=myqueue, consumerTag=null identity=68fe1f37] for restart`

But unfortunately the consumer is not added to be restarted as the error happens during startup, and the `started` flag is not yet set to true, as this happens AFTER the consumer is attempted to be started.

See the 3 screenshots from source code debugging.

**Comment by davsclaus** [comment]
<img width="1030" alt="rabbit-start-3" src="https://user-images.githubusercontent.com/477100/104298566-6a610b00-54c4-11eb-8447-083095c819bd.png">
<img width="1100" alt="rabbit-start-2" src="https://user-images.githubusercontent.com/477100/104298569-6af9a180-54c4-11eb-8a67-2681fec953cd.png">
<img width="1022" alt="rabbit-start-1" src="https://user-images.githubusercontent.com/477100/104298571-6b923800-54c4-11eb-87d8-eec3fe0d47ed.png">

**Comment by davsclaus** [comment]
Maybe add `starting` flag to the listener

boolean starting = false

And then set 

`DirectMessageListenerContainer.this.starting = true;` in the top of the `startConsumers` method, so we can check for both starting and started flag in the `addConsumerToRestart` method

```
	private void addConsumerToRestart(SimpleConsumer consumer) {
		if (this.starting || this.started) {
			this.consumersToRestart.add(consumer);
			if (this.logger.isTraceEnabled()) {
				this.logger.trace("Consumers to restart now: " + this.consumersToRestart);
			}
		}
	}
```

**Comment by artembilan** [comment]
Thank you for reporting this, Claus!
This is a good catch: how we have missed it with our tests...

With a quick look into the code I would say that we don't need to check that `this.started` in the `addConsumerToRestart()` and add consumer into that list unconditionally.

Then we need just to adjust a task in the `startMonitor(long idleEventInterval, final Map<String, Queue> namesToQueues)` method to not clean `this.consumersToRestart`  if we are not started yet.

WDYT?

/CC @garyrussell

**Comment by garyrussell** [comment]
@davsclaus Thanks for the detailed analysis.

Caused by https://github.com/spring-projects/spring-amqp/pull/642 so it's a little more involved.
