### ISSUE TITLE
can add something to ensure queue consume ordering while consumes to hundreds of queues

### ISSUE THREAD

**Issue by bthulu** [spring-projects/spring-amqp#1328]
**Affects Version(s):** \<Spring AMQP version>
<=2.2.x, 2.3.x not tested.

## Enhancement
if setMaxConcurrentConsumers to ListenerContainer, each queue may increase to more than 1 consumers, break the queue ordering.
if not set, all queues consumes with one thread one channel, if a queue consumer blocks , all blocks.
so, may be ConcurrentConsumers semantics should contains two:
1. how many consumers per queue
2. how many threads can be used by container
then if set fetsize=1 and one consumer per queue and 50(max) threads on container, the queue consuming can satisfies ordering and concurrent.

**Comment by garyrussell** [comment]
Have you tried using a `DirectMessageListenerContainer` instead?

See https://docs.spring.io/spring-amqp/docs/current/reference/html/#choose-container

**Comment by bthulu** [comment]
> Have you tried using a `DirectMessageListenerContainer` instead?
> 
> See https://docs.spring.io/spring-amqp/docs/current/reference/html/#choose-container

it solves, thanks a lot.
