### ISSUE TITLE
MessagingMessageListenerAdapter Skips Error Handler with MessageConversionException

### ISSUE THREAD

**Issue by nkvaratskhelia** [spring-projects/spring-amqp#1339]
I'm using spring-amqp's (v 2.3.6) `rabbitTemplate.sendAndReceive(exchange, routingKey, message)` method for sending messages. `RabbitTemplate` is configured with `Jackson2JsonMessageConverter`.

If I send a malformed json in the message body, I can see from the log that message conversion fails with `org.springframework.amqp.support.converter.MessageConversionException: Failed to convert Message content`, as expected. However, the `sendAndReceive` method doesn't abort and continues execution until a `replyTimeout` is hit. This exception occurs before execution reaches my `@RabbitListener` annotated method. It seems that `sendAndReceive` doesn't react to this exception and continues waiting for a reply from the consumer, which never arrives, so it just keeps on waiting until replyTimeout passes and then returns null.

As a comparison, if there is an exception inside my `@RabbitListener` annotated method, then `sendAndReceive` aborts instantly and returns.

I have the same situation as described in [this issue](https://github.com/spring-projects/spring-amqp-samples/issues/58). But in my case, I'm using rpc pattern and I need to somehow signal `sendAndReceive` to return immediately if an exception occurs and not wait for the full replyTimeout duration to elapse.

Is there any way to abort `sendAndReceive` in case of the `MessageConversionException` scenario described above?

Here's a [minimal reproducer](https://github.com/nkvaratskhelia/rabbit-demo) of the issue.

**Comment by nkvaratskhelia** [comment]
I first asked this as a [question on stackoverflow](https://stackoverflow.com/questions/67590935/how-to-abort-sendandreceive-on-messageconversionexception) and Artem suggested to move it here as an issue. As a possible solution he also suggested implementing a custom `ConditionalRejectingErrorHandler` and overriding it's `protected void handleDiscarded(Message failed)` method to send back a reply with an error message. I'm not quite sure how this can be done, so any suggestions are welcome.

**Comment by garyrussell** [comment]
The problem is we only catch LEFEs

https://github.com/spring-projects/spring-amqp/blob/cc0323a8c40509986f1d3a182fdefe98c40756e5/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/MessagingMessageListenerAdapter.java#L158-L164

We should catch all exceptions and allow the user to configure an error handler to return some kind of error result.

**Comment by artembilan** [comment]
Thanks, Gary, for the pointer!

We will then have to revise this method logic in that adapter class:
```
@Override
public void onMessage(org.springframework.amqp.core.Message amqpMessage, Channel channel) throws Exception { // NOSONAR
	Message<?> message = toMessagingMessage(amqpMessage);
	invokeHandlerAndProcessResult(amqpMessage, channel, message);
}
```
It fails exactly on that `toMessagingMessage()` which is not included into an error handling and therefore reply producing.

**Comment by artembilan** [comment]
Looks like same problem we have in Spring for Apache Kafka in its `RecordMessagingMessageListenerAdapter`...

**Comment by garyrussell** [comment]
Ah, right; we can also get a message conversion exception in `invokeHandler()`, but I see that will be wrapped in an LEFE there (which is why that catch block only looks for LEFE).

I guess we should move the error handler code to `onMessage()`.

**Comment by nkvaratskhelia** [comment]
Was this supposed to be fixed in `2.3.8`? I updated to `spring boot 2.5.1` (which includes `2.3.8`) but I still have the same issue. Please check the minimal reproducer (I updated it to `spring boot 2.5.1`).

**Comment by nkvaratskhelia** [comment]
I added an error handler, which returns a simple `ErrorResponse` object to the caller and it works well in case of regular client business exceptions. But there seems to be a problem in case of `MessageConversion` exceptions.

I added 3 cases in the demo. Case 1 is the normal flow withouth any exceptions. Case 2 is when the client throws a business exception. Case 3 is when an invalid json is sent and message conversion fails. Cases 1 & 2 work as expected, but in Case 3, the message is reprocessed over and over again and I can also see these exceptions being logged: 

![image](https://user-images.githubusercontent.com/16168235/121712917-efd4ff80-cae4-11eb-96c7-98fe2e080e60.png)

P.S. Case 3 is commented out in the demo.

**Comment by garyrussell** [comment]
I will take a look at your reproducer; there is a test in the PR that asserts that the error handler is called: https://github.com/spring-projects/spring-amqp/pull/1346/files#diff-a30c214ad2486f9601ff53c8ed0eaeef284a313b97f2f05ec1727cd55feebaa7

**Comment by garyrussell** [comment]
`returnExceptions` doesn't work either 😦

**Comment by garyrussell** [comment]
@nkvaratskhelia Thanks for your patience. I tested the new PR with your demo...

```
(Body:'"bar"' MessageProperties ...
(Body:'{"message":"throwing back foo"}' MessageProperties ...
(Body:'{"message":"Failed to convert Message content"}' MessageProperties ...
```

**Comment by garyrussell** [comment]
@nkvaratskhelia If you want to try it, you can override Boot's prescribed version of spring-rabbit to 2.3.9-SNAPSHOT - it is available in https://repo.spring.io/snapshot

**Comment by nkvaratskhelia** [comment]
Thanks for the fix. 👍
