### ISSUE TITLE
Broken documentation link

### ISSUE THREAD

**Issue by mikeholler** [spring-projects/spring-amqp#1340]
**Affects Version(s):** \Current

---

On the spring-amqp main page:

https://spring.io/projects/spring-amqp

There is a link titled "Spring Boot Autoconfiguration for Spring AMQP (RabbitMQ)" and it directs me to the following URL:

https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-messaging.html#boot-features-amqp

When I visit this URL, I get a message saying:

    Not Found
    
    The requested URL /spring-boot/docs/current/reference/html/spring-boot-features.html was not found on this server.

I tried to find a better place to put this, but ended up here. If you can't help here, please point me in the right direction so I can file this in the correct place.

Thanks!

**Comment by mikeholler** [comment]
This appears to be the correct link now, after playing around with the URL:

https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.messaging

**Comment by garyrussell** [comment]
Thanks, fixed - Boot has reworked its documentation in 2.5; the link worked when the current version was 2.4.x.

**Comment by garyrussell** [comment]
See https://github.com/spring-projects/spring-boot/issues/26683

**Comment by snicoll** [comment]
FTR the original link now works again.

**Comment by garyrussell** [comment]
@snicoll Not quite

https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-messaging.html#boot-features-amqp

gets redirected to

https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.messaging

instead of

https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.messaging.amqp

**Comment by snicoll** [comment]
paging @philwebb

**Comment by philwebb** [comment]
That's annoying. I'm not sure we can fix it. The httpd rewrite rules are changing `boot-features-messaging.html` -> `features.html#features.messaging` so the `#boot-features-amqp` anchor gets lost. The following link will work with 2.3.x, 2.4.x and master: https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-amqp
