### ISSUE TITLE
Add Support for RabbitMQ Stream Java Client

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-amqp#1352]
New listener container for the stream API to support invoking `@RabbitListener` etc.

https://github.com/rabbitmq/rabbitmq-stream-java-client

**Comment by welsh** [comment]
Is there a tentative date for 2.4 being release with this being present? I see the last Milestone was 25 days ago.

**Comment by garyrussell** [comment]
Next milestone is Sept 20; with release candidate in October and GA in November, aligned with the Boot 2.6 RC and GA.

https://calendar.spring.io/
