### ISSUE TITLE
Callback handling in case of exception in Spring Transaction (synchronization).

### ISSUE THREAD

**Issue by kuldeepkalassts** [spring-projects/spring-amqp#1362]
## Enhancement

This is in continuation of https://github.com/spring-projects/spring-amqp/issues/1341,

We have seen that in case exception occurs in Spring Transaction After Completion Phase, the exception is thrown back to the caller method of Spring transaction . So is there some callback handling available to caller code in case the error is thrown ?

Also we have seen that in this case the resource is left over from previous transaction in case of exception thrown while commit and this corrupts the thread for subsequent flows. Can this be handled?

**Comment by garyrussell** [comment]
Errors in `TransactionSynchronization.afterCompletion()` are simply logged in `TransactionSynchronizationUtils`. There is no way to throw an exception to the calling thread. I don't see an easy way to add a callback; that code is all in core spring-transaction.

As discussed on that issue; I can't see any way that a resource can be "left over" from one operation to another; this code has been around for over a decade.  Please provide a [MCRE](https://stackoverflow.com/help/minimal-reproducible-example) that exhibits this behavior.

**Comment by garyrussell** [comment]
On second thought - I **do** see a way to provide a callback, we could add it to the `RabbitResourceSynchronization`,
