### ISSUE TITLE
AmqpAdmin bean not found if defined in parent context

### ISSUE THREAD

**Issue by hjohn** [spring-projects/spring-amqp#1370]
## Bug report

Spring Amqp does not find the AmqpAdmin bean if it is defined in a parent context but is not present in the current (child) context.

In this code below in `AbstractMessageListenerContainer` the method `getBeansOfType` is used:

	protected void configureAdminIfNeeded() {
		if (this.amqpAdmin == null && this.getApplicationContext() != null) {
			Map<String, AmqpAdmin> admins = this.getApplicationContext().getBeansOfType(AmqpAdmin.class);
			if (admins.size() == 1) {
				this.amqpAdmin = admins.values().iterator().next();
			}
			else {
				if ((isAutoDeclare() || isMismatchedQueuesFatal()) && this.logger.isDebugEnabled()) {
					logger.debug("For 'autoDeclare' and 'mismatchedQueuesFatal' to work, there must be exactly one "
							+ "AmqpAdmin in the context or you must inject one into this container; found: "
							+ admins.size() + " for container " + toString());
				}
				if (isMismatchedQueuesFatal()) {
					throw new IllegalStateException("When 'mismatchedQueuesFatal' is 'true', there must be exactly "
							+ "one AmqpAdmin in the context or you must inject one into this container; found: "
							+ admins.size() + " for container " + toString());
				}
			}
		}
	}

This method does not check parent contexts (`getBeansOfType` is documented as such), however I think it should.  In an application with several contexts, the AmqpAdmin bean is defined in a parent context.  Child contexts however don't see the AmqpAdmin bean because this method does not check the parent contexts.

Contrast this with the regular `getBean` method on application context, which does check the parent and in our testing does find the AmqpAdmin bean in this case.  It seems that in order to support the logic in the `else` clause here `getBeansOfType` was used over the normal `getBean` call.

**Comment by artembilan** [comment]
Looks like `BeanFactoryUtils.beansOfTypeIncludingAncestors(ListableBeanFactory lbf, Class<T> type)` must be used instead.

**Comment by garyrussell** [comment]
I don't believe we can backport this because it could cause a behavior change, if there is an admin in both the parent and child context it could throw an `IllegalStateException`.

```java
	if (admins.size() == 1) {
		this.amqpAdmin = admins.values().iterator().next();
	}
	else {
		if ((isAutoDeclare() || isMismatchedQueuesFatal()) && this.logger.isDebugEnabled()) {
			logger.debug("For 'autoDeclare' and 'mismatchedQueuesFatal' to work, there must be exactly one "
					+ "AmqpAdmin in the context or you must inject one into this container; found: "
					+ admins.size() + " for container " + toString());
		}
		if (isMismatchedQueuesFatal()) {
			throw new IllegalStateException("When 'mismatchedQueuesFatal' is 'true', there must be exactly "
					+ "one AmqpAdmin in the context or you must inject one into this container; found: "
					+ admins.size() + " for container " + toString());
		}
	}
```

The work around for 2.2.x, 2.3.x is to explicitly set the desired admin on the container.
