### ISSUE TITLE
Add property like useAutoStartUpAfterRefresh to disable listeners start on ContextRefresh event

### ISSUE THREAD

**Issue by KiriaUA** [spring-projects/spring-amqp#1376]
Following discussion on stackoverflow: [Spring AMQP Listener starts when autoStartup = false](https://stackoverflow.com/questions/69463507/spring-amqp-listener-starts-when-autostartup-false)

Recently faced a weird issue with Spring AMQP `@RabbitListener`.
Listener was declared like this, so autostartup was set to `false`

    @RabbitListener(id = "MqMessageHandler", queues = "${rabbitMQ.in-queue-name}", autoStartup = "false")
	public void receiveMessage(Message message) {

After application is fully initialized and i get a response from some other service, i'm manually starting the listener like this
```
MessageListenerContainer mqMessageHandler = registry.getListenerContainer(HANDLER_ID);
mqMessageHandler.start();
```
But it appears that listener is still starting on context initialization. 
Digging a bit in the code i found this piece of code inside `RabbitListenerEndpointRegistry`

```
	/**
	 * Start the specified {@link MessageListenerContainer} if it should be started
	 * on startup or when start is called explicitly after startup.
	 * @param listenerContainer the container.
	 * @see MessageListenerContainer#isAutoStartup()
	 */
	private void startIfNecessary(MessageListenerContainer listenerContainer) {
		if (this.contextRefreshed || listenerContainer.isAutoStartup()) {
			listenerContainer.start();
		}
	}
```

That means that listener will be started once `ContextRefreshed` event is fired.
I'd expect the condition to be 
`this.contextRefreshed && listenerContainer.isAutoStartup()`
so `&&` instead of `||` and then it should work as expected. 

Does anybody knows if the condition is correct, and my assumptions are wrong? 
Spring AMQP version is `2.3.1` but the same i saw in `2.3.10`

As a workaround for now i'm registering listener manually like this
```
		MessageListenerContainer mqMessageHandler = registry.getListenerContainer(HANDLER_ID);
		if (Objects.isNull(mqMessageHandler)) {
			SimpleRabbitListenerEndpoint endpoint = new SimpleRabbitListenerEndpoint();
			endpoint.setQueueNames(inQueueName);
			endpoint.setMessageListener(this.mqMessageHandler);
			endpoint.setId(HANDLER_ID);

			registry.registerListenerContainer(endpoint, factory);
			mqMessageHandler = registry.getListenerContainer(HANDLER_ID);
		}
		mqMessageHandler.start();
```

**Comment by garyrussell** [comment]
After further review; it's still not clear what's happening.

`startImmediately()` is only called (after the context is refreshed) if you register a new endpoint, and set the `startImmediately` registration parameter to true; endpoints registered before the refresh are not started.

Can you provide a complete example that exhibits the behavior you are seeing?

**Comment by KiriaUA** [comment]
initially endpoint was defined like this 
```
@RabbitListener(id = "MqMessageHandler", queues = "${rabbitMQ.in-queue-name}", autoStartup = "false")
public void receiveMessage(Message message) {
```

With this definition and `autoStartup  = false` i expected that listener will not be started until i will explicitly call `start()` on it. 
But it is not the case, as after context is refreshed it starts to consume messages.

If it is correct behavior then no question from my side.

But maybe you can suggest if there is another way to achieve this. 
I mean, register listener with `@EventListener` and make it not active (not consuming messages) until i will call start explicitly

**Comment by KiriaUA** [comment]
Indeed, it is fine in your example. I'll will try to debug a bit more to find the root cause of my issue, and will update the description.

**Comment by garyrussell** [comment]
Correct; it is called from `start()` (which is called by the application context `SmartLifecycle` processing before the refreshed event is published).

If you are seeing it being called twice, please get a stack trace for the second call, so we can see what is calling it.
