### ISSUE TITLE
Declarables constructor is too strict

### ISSUE THREAD

**Issue by bjmi** [spring-projects/spring-amqp#1396]
## Little enhancement / convenience
Following constructor
```
public Declarables(Collection<Declarable> declarables) {
    Assert.notNull(declarables, "declarables cannot be null");
    this.declarables.addAll(declarables);
}
```
could be widen by upper bounded wildcard. `public Declarables(Collection<? extends Declarable> declarables)`
Then it would be possible pass subtypes of `Declarable` as type parameter like following
```
Collection<Binding> bindings = createBindings();
return new Declarables(bindings);
```
It is also safe because `bindings` is copied to `declarables` field.

**Comment by garyrussell** [comment]
While this is a valid request, why not just change createBindings to return a `Collection<Declarable>` - this works fine...

```java
@Bean
public Declarables qs() {
	return new Declarables(queues());
}

private List<Declarable> queues() {
	return List.of(
			new Queue("q2", false, false, true),
			new Queue("q3", false, false, true));
}
```

**Comment by bjmi** [comment]
Of course I could redeclare `queues()` to return `List<Declarable>` in this example.

Not everybody knows that `Binding`, `Exchange`, `Queue` etc. are subtypes of `Declarable` and wonder why they can't pass e.g. `List<Queue>` to `Declarables` constructor.

From effective Java 3rd ed. Item 31: Use bounded wildcards to increase API flexibility

> In summary, using wildcard types in your APIs, while tricky, makes the APIs
far more flexible. If you write a library that will be widely used, the proper use of
wildcard types should be considered mandatory.
