### ISSUE TITLE
Typo in EnableRabbit class description

### ISSUE THREAD

**Issue by bjmi** [spring-projects/spring-amqp#1397]
https://github.com/spring-projects/spring-amqp/blob/57596c6a26be2697273cd97912049b92e81d3f1a/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/annotation/EnableRabbit.java#L178

should be 
`*         registrar.setMessageHandlerMethodFactory(myMessageHandlerMethodFactory());`

**Comment by artembilan** [comment]
Confirmed. 
Please, see if you can come up with a contribution on the matter: https://github.com/spring-projects/spring-amqp/blob/main/CONTRIBUTING.adoc

Thank you!
