### ISSUE TITLE
spring.rabbitmq.listener.simple.missing-queues-and-exchanges-fatal-during-startup

### ISSUE THREAD

**Issue by bastiat** [spring-projects/spring-amqp#1400]
## Enhancement
Please see
[Make Spring RabbitMQ fail on missing exchange](https://stackoverflow.com/questions/70184352/make-spring-rabbitmq-fail-on-missing-exchange) here is a problem with solution/workaroun [RabbitMQ CachingConnectionFactory and publisherReturns configuration](https://stackoverflow.com/questions/25201931/check-if-the-exchange-with-a-specified-name-exist-in-rabbitmq/25204215#25204215). This is also in topic [Check if the Exchange with a specified name exist in rabbitmq](https://stackoverflow.com/questions/25201931/check-if-the-exchange-with-a-specified-name-exist-in-rabbitmq/25204215#25204215).

My problem is: I would like application to fail to start when it can't create a @ Bean Binding on startup.

There is nice property
spring.rabbitmq.listener.simple.missing-queues-fatal=true

Wouldn't it be usefull to allow user to configure Rabbit and Spring Context in a way to stop whole application when exception containing "reply-code=404, reply-text=NOT_FOUND" in regard to missing queue or exchange appears?

I would like to make binding do such check (as an option). I just don't want application to start when it can't create a binding. On the other hand possibly I would't like it to stop later, after it starts when an Exchange is not available during running (maybe it was removed and will be recreated in a moment - but I don't know if it's a good reason).

Do you see any sens in what I wrote? Is my problem really a problem? Is there a scope for enhancement in this area, or I just should do all validations manually before creation of Binding as described in [Check if the Exchange with a specified name exist in rabbitmq](https://stackoverflow.com/questions/25201931/check-if-the-exchange-with-a-specified-name-exist-in-rabbitmq/25204215#25204215)?

**Comment by garyrussell** [comment]
Unlike queues configured for containers, the framework has no knowledge of which exchange(s) might be used by the application so it can't impose a check like this.

Use a passive declaration in your startup code instead.

**Comment by jakub-wzim** [comment]
Thx, I did it as described here https://stackoverflow.com/questions/25201931/check-if-the-exchange-with-a-specified-name-exist-in-rabbitmq/25204215#25204215.
Thx for help.

**Comment by bastiat** [comment]
Yes, I did it as described in https://stackoverflow.com/questions/25201931/check-if-the-exchange-with-a-specified-name-exist-in-rabbitmq/25204215#25204215.
Thx for help.
