### ISSUE TITLE
SimpleMessageListenerContainer handle multiple queues

### ISSUE THREAD

**Issue by zysaaa** [spring-projects/spring-amqp#1402]
If I use SMLC and bind multiple queues, capacity of ```BlockingQueueConsumer#queue``` will be set to ```prefetchCount```. Is it more reasonable to set it to ```queue.length * prefetchCount```?

For example, use the following code test:

```
public static void main(String[] args) throws InterruptedException {
	AtomicInteger count = new AtomicInteger();
	CachingConnectionFactory ccf = new CachingConnectionFactory();
	ccf.setHost("127.0.0.1");
	SimpleMessageListenerContainer simpleMessageListenerContainer = new SimpleMessageListenerContainer(ccf);
	simpleMessageListenerContainer.setQueueNames("testq", "testq1", "testq2", "testq3");
	simpleMessageListenerContainer.setAcknowledgeMode(AcknowledgeMode.AUTO);
	simpleMessageListenerContainer.setMessageListener(new ChannelAwareMessageListener() {
		@Override
		public void onMessage(Message message, Channel channel) throws Exception {
			int incrementAndGet = count.incrementAndGet();
			/*try {
				channel.basicAck(message.getMessageProperties().getDeliveryTag(), false);
			} catch (Exception e) {
				System.out.println(e.getMessage());
			}*/
			if (incrementAndGet > 10000) {
				// should not happen
				System.out.println(incrementAndGet);
			}
		}
	});
	simpleMessageListenerContainer.start();
	Thread.sleep(1000);
	AmqpTemplate amqpTemplate = new RabbitTemplate(ccf);
	new Thread(() -> {
		int k = 2500;
		while (k-- > 0) {
			// teste is a topic exchange
			// teste has four bindings, routingkey key are all '*.*' with these four queues: "testq", "testq1", "testq2", "testq3"
			amqpTemplate.send("teste", "a.a", MessageBuilder.withBody("he".getBytes(StandardCharsets.UTF_8)).build());
		}
	}).start();
	new Thread(() -> {
		try {
			int i = 5;
			while (i-- > 0) {
				Thread.sleep(30);
				simpleMessageListenerContainer.removeQueueNames("testq", "testq1");
				Thread.sleep(30);
				simpleMessageListenerContainer.addQueueNames("testq", "testq1");
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
	}).start();
}
```
There will be some ```java.lang.IllegalStateException: Channel closed; cannot ack/nack``` exceptions. And value of ```count``` will exceed 10000(Maybe 10010).  If set to ```MANUAL``` ACK, value of ```count``` will far exceed 10000, reaching 10200 on my computer. This means a lot of repeated consumption?

I did a simple debug, it seems ```BlockingQueueConsumer#line 941``` will be executed:```BlockingQueueConsumer.this.queue.offer``` will return ```false```, beacuse blocking queue is full beacuse of messages from other queues.

If I set the capacity of the blocking queue to ```queue.length * prefetchCount``` in ```BlockingQueueConsumer```:

```
this.queue = new LinkedBlockingQueue<Delivery>(queues.length == 0 ? prefetchCount : prefetchCount * queues.length);
```
Above problems will be fixed.

If messages have arrived at the application side, then these messages should stay in the ```SMLC#BlockingQueueConsumer#BlockingQueue```   instead of the ```amqp-client``` side. Is this more reasonable?

**Comment by garyrussell** [comment]
It is not clear what you mean; `offer` is only used when the consumer has been cancelled; normally a blocking `put()` is called.

Also, setting the prefetch like that does not necessarily mean you will get messages from all 3 queues.

**Comment by zysaaa** [comment]
For a ```SMLC```, if multiple queues are bound, the client will receive a total of  ```prefetchCount* queue.length``` messages before  messages are acked. But capacity of ```SimpleMessageListenerContainer#BlockingQueueConsumer#BlockingQueue``` is only set to ```prefetchCount```.

One ```BlockingQueueConsumer``` -> one ```channel``` -> one ```BlockinQueue```  -> x ```queues```.

Is it more reasonable to set the capacity of the ```BlockinQueue```  to ```prefetchCount*queue.length```?

**Comment by garyrussell** [comment]
Oh; sorry, I see what you mean; I guess the assumption was that the qos is for the channel but it is for each consumer.

Feel free to submit another PR.

Thanks.
