### ISSUE TITLE
MessageConversionException causes all unacked messages to be nacked

### ISSUE THREAD

**Issue by peterlgh7** [spring-projects/spring-amqp#1409]
## Bug report

When using asynchronous `@RabbitListener`(with a `ListenableFuture` as return type), a `MessageConversionException` causes all unacked messages to be nacked.

It can be reproduced with the following:
<details>
<summary>Listener.java</summary>

```java
package com.example.demo;

import org.springframework.amqp.core.MessageBuilder;
import org.springframework.amqp.core.QueueBuilder;
import org.springframework.amqp.rabbit.annotation.RabbitListener;
import org.springframework.amqp.rabbit.connection.CachingConnectionFactory;
import org.springframework.amqp.rabbit.core.RabbitAdmin;
import org.springframework.amqp.rabbit.core.RabbitTemplate;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.ConfigurableApplicationContext;
import org.springframework.stereotype.Component;
import org.springframework.util.concurrent.ListenableFuture;
import org.springframework.util.concurrent.SettableListenableFuture;

import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;

import javax.annotation.PostConstruct;

@Component
public class Listener implements CommandLineRunner {
  
  @Autowired
  private CachingConnectionFactory connectionFactory;
  
  @Autowired
  private RabbitTemplate rabbitTemplate;
  
  @Autowired
  private ConfigurableApplicationContext context;
  
  private ScheduledExecutorService scheduler = Executors.newSingleThreadScheduledExecutor();
  
  @PostConstruct
  public void init() {
    RabbitAdmin rabbitAdmin = new RabbitAdmin(connectionFactory);
    connectionFactory.addConnectionListener(connection -> {
      rabbitAdmin.declareQueue(QueueBuilder.durable("test.dlq").build());
      rabbitAdmin.declareQueue(QueueBuilder.durable("test")
          .withArgument("x-dead-letter-exchange", "")
          .withArgument("x-dead-letter-routing-key", "test.dlq")
          .build());
    });
  }

  @Override
  public void run(String... args) throws Exception {
    rabbitTemplate.send("", "test", MessageBuilder.withBody("{\"text\": \"Test1\"}".getBytes()).build());
    rabbitTemplate.send("", "test", MessageBuilder.withBody("invalidJson".getBytes()).build());
    
    Thread.sleep(10000);
    context.close();
    scheduler.shutdown();
  }

  @RabbitListener(queues = "test")
  public ListenableFuture<Void> listen(TestMessage message) {
    SettableListenableFuture<Void> future = new SettableListenableFuture<Void>();
    scheduler.schedule(() -> future.set(null), 5, TimeUnit.SECONDS);
    
    return future;
  }
  
  public static class TestMessage {
    public String text;
  }
}
```
</details>

<details>
<summary>Config.java</summary>

```java
package com.example.demo;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.amqp.support.converter.Jackson2JsonMessageConverter;
import org.springframework.amqp.support.converter.MessageConverter;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
public class Config {
  
  @Bean
  public MessageConverter messageConverter() {
    return new Jackson2JsonMessageConverter(new ObjectMapper());
  }
}
```
</details>

<details>
<summary>Main.java</summary>

```java
package com.example.demo;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class Main {

  public static void main(String[] args) {
    SpringApplication.run(Main.class, args);
  }

}
```
</details>

<details>
<summary>application.yml</summary>

```yaml
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: MANUAL
        default-requeue-rejected: false
```
</details>

<details>
<summary>pom.xml</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.6.1</version>
		<relativePath /> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.example</groupId>
	<artifactId>demo</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>demo</name>
	<description>Rabbit bug</description>
	<properties>
		<java.version>11</java.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-amqp</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.amqp</groupId>
			<artifactId>spring-rabbit-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>
```
</details>

The code in Listener sends two messages to the queue. The first one is valid JSON and the second one is not. The `@RabbitListener` simulates an asynchronous processing time of 5 seconds for the first message. The second message then arrives and causes a `MessageConversionException`. This in turn triggers a nack for both messages, instead of just the second message. Both messages can be found in _test.dlq_.

The incriminated code seems to  be:
https://github.com/spring-projects/spring-amqp/blob/83e57bb73132b121a22870901a86939ef17b7b5d/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/BlockingQueueConsumer.java#L793-L797
Where _basicNack_ is called with _multiple_ set to _true_.

Is this for some reason expected behavior? I would have expected only the invalid JSON to be nacked/sent to DLQ.

**Comment by garyrussell** [comment]
See [the documentation](https://docs.spring.io/spring-amqp/docs/current/reference/html/#async-returns).

Specifically:

>The listener container factory must be configured with AcknowledgeMode.MANUAL so that the consumer thread will not ack the message; instead, the asynchronous completion will ack or nack the message when the async operation completes. When the async result is completed with an error, whether the message is requeued or not depends on the exception type thrown, the container configuration, and the container error handler. By default, the message will be requeued, unless the container’s defaultRequeueRejected property is set to false (it is true by default). If the async result is completed with an AmqpRejectAndDontRequeueException, the message will not be requeued. If the container’s defaultRequeueRejected property is false, you can override that by setting the future’s exception to a ImmediateRequeueException and the message will be requeued. If some exception occurs within the listener method that prevents creation of the async result object, you MUST catch that exception and return an appropriate return object that will cause the message to be acknowledged or requeued.

Manual ack means the application is responsible for performing the acks; in this case the listener adapter handles the "manual" acks for you, when the future is completed...

https://github.com/spring-projects/spring-amqp/blob/83e57bb73132b121a22870901a86939ef17b7b5d/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/AbstractAdaptableMessageListener.java#L384-L389

and

https://github.com/spring-projects/spring-amqp/blob/83e57bb73132b121a22870901a86939ef17b7b5d/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/AbstractAdaptableMessageListener.java#L449-L458

**Comment by garyrussell** [comment]
Oh; I see the problem; even when properly set to manual.

https://github.com/spring-projects/spring-amqp/blob/83e57bb73132b121a22870901a86939ef17b7b5d/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/BlockingQueueConsumer.java#L783-L784

`ContainerUtils.isRejectManual(ex)` returns true, by default, for exceptions that are created due to conversion exceptions.

As a workaround, you can set rejectManual to false on a `ConditionalRejectingErrorHandler`.

https://github.com/spring-projects/spring-amqp/blob/83e57bb73132b121a22870901a86939ef17b7b5d/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/ConditionalRejectingErrorHandler.java#L112-L119

**Comment by garyrussell** [comment]
However, that will leave the message un-ack'd (but I guess that's better than acking the others).

**Comment by garyrussell** [comment]
I have a fix but it needs some tests (I tested it with a Boot app).

I am off tomorrow but will try to issue a PR over the weekend in time for Monday's releases.

**Comment by peterlgh7** [comment]
Great! I had tried with rejectManual=false, but having the message unacked in the queue was actually worse in my use case. Thanks for looking into this.

**Comment by garyrussell** [comment]
@peterlgh7 2.4.1, 2.3.13 and 2.2.21.RELEASE are now in Maven Central with the fix.

**Comment by peterlgh7** [comment]
I just tried and it works as expected now. Thanks a lot! That was a fast fix as usual :)
