### ISSUE TITLE
Remove HOP Dependency (2.4.x)

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-amqp#1419]
Hop will no longer support JDK 8 before the end of life of 2.4.x; there is only one hard dependency on Hop (in `LocalizedQueueConnectionFactory` to determine the hosting node of a classic mirrored queue).

**Comment by acogoluegnes** [comment]
`LocalizedQueueConnectionFactory` uses only the `/queues/{vhost}/{queue}` endpoint. The easiest would be to use the `RestTemplate` and Jackson, to keep the same dependencies as Hop.
