### ISSUE TITLE
Determine charset from contentType if any

### ISSUE THREAD

**Issue by bjmi** [spring-projects/spring-amqp#1420]
> There is no guarantee that the consumer uses Jackson to decode the content.
> 
> We can consider moving the charset to the contentType; please open a new issue for that.

_Originally posted by @garyrussell in https://github.com/spring-projects/spring-amqp/issues/1251#issuecomment-700028191_

Affected version: spring-amqp 2.4.2
Recently we were affected by this as the *charset* was provided in *contentType* header like e.g.  
`content-type: application/xml; charset=utf-16` and causes deserialization problems.
For the sending part: non spring-amqp consumers don't expect to find *charset* at *contentEncoding* header.

Please consider moving the *charset* to the *contentType*.

**Comment by garyrussell** [comment]
This might also impact the compression post processors, including the `DelegatingDecompressingPostProcessor`.
