### ISSUE TITLE
SimpleMessageListenerContainer takes a long time to shutdown

### ISSUE THREAD

**Issue by mjaggard** [spring-projects/spring-amqp#1436]
**In what version(s) of Spring AMQP are you seeing this issue?**
2.3.14

**Describe the bug**
When I have a lot of listeners, shutdown takes a long time because each listener is shut down and then awaited before starting the shutdown of the next one. These should be shut down asynchronously as `RabbitListenerEndpointRegistry` already implements `SmartLifecycle` to handle this style of working.

**To Reproduce**
Create a container with a large number of listeners which take some time to close, and then shut them down.

**Expected behavior**
The shutdown should be completed in the time taken for the longest wait.

A PR to fix this will be produced shortly.

**Comment by bjmi** [comment]
> **In what version(s) of Spring AMQP are you seeing this issue?**
>  2.4.8

Spring AMQP 2.4.**3** was released since a few days. Do you actually mean 2.**3**.8?

**Comment by mjaggard** [comment]
I have no clue where that version came from now. I've updated to the one we're using in our current project.
