### ISSUE TITLE
RabbitListener does not include inferrer value when injecting header object

### ISSUE THREAD

**Issue by nightknight77** [spring-projects/spring-amqp#1441]
Version:
Spring Boot 2.6 - spring starter

############

**Description:**

The documentation of the RabbitListener annotation suggests multiple ways on how to retrieve the message headers. If you use MessageHeaders and inject it as an argument for getting access to all headers, then the **inferrer** header (which in my understanding contains the consumer model) is **not** provided with a value anymore and message converter implementations like the Jackson2JsonMessageConverter are then using the __TYPE_ID__ property and convert it into the given domain model. That property is provided by the producer and usually contains the fully qualified package name, so the converter on the consumer side looks for the domain model of the producer. If the consumer has its model not in the exact same package structure, it throws an ClassNotFound exception. This is confusing because if you cut the MessageHeader object and instead inject a simple Map<String, Object> and annotate that with @Headers (also suggested in the docs) then it works again and the inferrer value is provided. So my guess is this behaviour is not intended. 

**Steps to reproduce the behavior:**
1.  Use two models for json conversion. The package structure must differ.
2.  Add next to your model an additional parameter of type MessageHeaders. 
3.  Receive a message on consumer side.

**Actual behavior**
ClassnotFound exception is thrown and converter cannot convert into inferrer type.

**Expected behavior**
Inferrer type is provided and converts successfully into consumers model.

**Sample**
A short sample will be provided soon.

**Comment by garyrussell** [comment]
Thanks for reporting; reproduced:

```java
@SpringBootApplication
public class Rgh1441Application {

	public static void main(String[] args) {
		SpringApplication.run(Rgh1441Application.class, args);
	}

	@RabbitListener(queues = "foo")
	public void listen1(Foo foo, @Headers Map<String, Object> headers) {
		System.out.println("1: " + foo);
	}

	@RabbitListener(queues = "bar")
	public void listen2(Foo foo, MessageHeaders headers) {
		System.out.println("2: " + foo);
	}

	@Bean
	ApplicationRunner runner(RabbitTemplate template, AbstractRabbitListenerContainerFactory<?> factory) {
		factory.setMessageConverter(converter());
		return args -> {
			template.convertAndSend("foo", "{\"bar\":\"baz\"}", msg -> {
				msg.getMessageProperties().setContentType("application/json");
				return msg;
			});
			template.convertAndSend("bar", "{\"bar\":\"baz\"}", msg -> {
				msg.getMessageProperties().setContentType("application/json");
				return msg;
			});
		};
	}

	Jackson2JsonMessageConverter converter() {
		return new Jackson2JsonMessageConverter();
	}

	public static class Foo {

		private String bar;

		public String getBar() {
			return this.bar;
		}

		public void setBar(String bar) {
			this.bar = bar;
		}

		@Override
		public String toString() {
			return "Foo [bar=" + this.bar + "]";
		}

	}

}
```
```
1: Foo [bar=baz]
...
org.springframework.amqp.rabbit.support.ListenerExecutionFailedException: Listener method could not be invoked with the incoming message
Endpoint handler details:
Method [public void com.example.demo.Rgh1441Application.listen2(com.example.demo.Rgh1441Application$Foo,org.springframework.messaging.MessageHeaders)]
...
Caused by: org.springframework.messaging.converter.MessageConversionException: Cannot convert from [java.util.LinkedHashMap] to [com.example.demo.Rgh1441Application$Foo] for GenericMessage [payload={bar=baz}, headers={amqp_receivedDeliveryMode=PERSISTENT, amqp_receivedRoutingKey=bar, amqp_contentEncoding=UTF-8, amqp_deliveryTag=1, amqp_consumerQueue=bar, amqp_redelivered=false, id=b0a6eec6-b59b-a887-7622-1e56818a6201, amqp_consumerTag=amq.ctag-0Op6ygNvKbB523G-2fjZyA, amqp_lastInBatch=false, contentType=application/json, timestamp=1648065323359}]
```

**Comment by garyrussell** [comment]
The issue is in the code that determines whether the parameter is a `payload` or not; since we have 2 non-annotated parameters (and there is no special logic for `MessageHeaders`, the code can't determine which one should be the payload.

The solution is to also add `@Headers` to the `MessageHeaders` parameter...

```java
@RabbitListener(queues = "foo")
public void listen1(Foo foo, @Headers Map<String, Object> headers) {
	System.out.println("1: " + foo);
}

@RabbitListener(queues = "bar")
public void listen2(@Payload Foo foo, @Headers MessageHeaders headers) {
	System.out.println("2: " + foo);
}
```
```
1: Foo [bar=baz]
2: Foo [bar=baz]
```

**Comment by garyrussell** [comment]
Right; I am going to fix it; I just wanted to tell you how to resolve it without any framework changes.
