### ISSUE TITLE
Custom RabbitTemplate bean to use spring.rabbitmq.template.exchange

### ISSUE THREAD

**Issue by esafzay** [spring-projects/spring-amqp#1446]
**In what version(s) of Spring AMQP are you seeing this issue?**

2.4.2

**Describe the bug**

Creating a custom RabbitTemplate bean does not use the default exchange configuration.

**To Reproduce**

    @Bean
    public RabbitTemplate jsonRabbitTemplate(ConnectionFactory connectionFactory, ObjectMapper mapper) {
        final var jsonRabbitTemplate = new RabbitTemplate(connectionFactory);
        jsonRabbitTemplate.setMessageConverter(new Jackson2JsonMessageConverter(mapper));
        return jsonRabbitTemplate;
    }

In the application.yml

    spring.rabbitmq.template.exchange: my-default-exchange

**Expected behavior**

Even when creating a custom RabbitTemplate should pick the default exchange from the configuration.

**Comment by garyrussell** [comment]
This has nothing to do with this project. Spring Boot auto configuration is handled by the spring-boot project, not this project.

In any case, Spring Boot auto configuration properties are only applied to beans declared by Spring Boot auto configuration.

When defining your own custom beans, you are totally responsible for configuring them.

```java
@Bean
public RabbitTemplate jsonRabbitTemplate(ConnectionFactory connectionFactory, ObjectMapper mapper,
		@Value("${spring.rabbitmq.template.exchange}") String exchange) {

	final var jsonRabbitTemplate = new RabbitTemplate(connectionFactory);
	jsonRabbitTemplate.setMessageConverter(new Jackson2JsonMessageConverter(mapper));
	jsonRabbitTemplate.setExchange(exchange);
	return jsonRabbitTemplate;
}
```

Also, if all you want to do is configure the message converter, just define the converter as a `@Bean` and Spring Boot will automatically wire it into the auto-configured template.

**Comment by garyrussell** [comment]
<img width="766" alt="Screen Shot 2022-04-03 at 7 35 49 AM" src="https://user-images.githubusercontent.com/483832/161426002-5cac70ce-47af-4489-8a94-3f50a6bcf289.png">

Looking at the video, this clearly has nothing to do with Spring; the root cause of the exception is thrown by the Avro deserializer; well before Spring is inolved.

You need to raise this issue with Avro, not here.
