### ISSUE TITLE
A queue is autodeclared when an unrelated java.util.function.Function @Bean is defined

### ISSUE THREAD

**Issue by mickaeltr** [spring-projects/spring-amqp#1462]
**In what version(s) of Spring AMQP are you seeing this issue?**

2.4.4

**Describe the bug**

⚠️ Disclaimer: that seems like a bug, but it's really not a topic that I master well, so I may be wrong!

We have a function bean in our code:

```java
@Bean
Function<String, Optional<String>> myFunction() {
  return …;
}
```

While this function is unrelated to RabbitMQ, I see the following (error) logs:

```
Auto-declaring a non-durable, auto-delete, or exclusive Queue (myFunction-in-0.anonymous.WluF2__RSYO7ycWVYlpjJw) durable:false, auto-delete:true, exclusive:true. It will be redeclared if the broker stops and is restarted while the connection factory is alive, but all messages will be lost.
```

```
Shutdown Signal: channel error; protocol method: #method<channel.close>(reply-code=405, reply-text=RESOURCE_LOCKED - cannot obtain exclusive access to locked queue 'myFunction-in-0.anonymous.WluF2__RSYO7ycWVYlpjJw' in vhost 'event'. It could be originally declared on another connection or the exclusive property value does not match that of the or..., class-id=50, method-id=10)
```

```
operation queue.declare caused a channel exception resource_locked: cannot obtain exclusive access to locked queue 'myFunction-in-0.anonymous.WluF2__RSYO7ycWVYlpjJw' in vhost 'event'. It could be originally declared on another connection or the exclusive property value does not match that of the original declaration.
```

**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**

**Sample**

A link to a GitHub repository with a [minimal, reproducible,  sample](https://stackoverflow.com/help/minimal-reproducible-example).

Reports that include a sample will take priority over reports that do not.
At times, we may require a sample, so it is good to try and include a sample up front.

**Comment by garyrussell** [comment]
This has nothing to do with this project; it is a spring-cloud-stream application. 

Your binding is anonymous (no `group`) so an exclusive auto-delete queue is created. It is not clear how your app would then try to access that queue over a different connection, because only one connection is generally created.

If you decide to open an issue over there; you will need to provide much more information, including your application.properties/yml.

**Comment by mickaeltr** [comment]
Thanks for your feedback

**Comment by mickaeltr** [comment]
FYI, it has to do with Spring Cloud Functions:

> In the nutshell Spring Cloud Function provides the following features: 1. Wrappers for @Beans of type Function, Consumer and Supplier, exposing them to the outside world as either HTTP endpoints and/or message stream listeners/publishers with RabbitMQ, Kafka etc.

Also see:
- https://github.com/spring-cloud/spring-cloud-function/issues/409
- https://github.com/spring-cloud/spring-cloud-function/issues/417
- https://github.com/spring-cloud/spring-cloud-function/issues/418
- https://github.com/spring-cloud/spring-cloud-stream/issues/1865
