### ISSUE TITLE
RabbitMQ Super Streams with Single Active Consumer

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-amqp#1465]
Add support for super streams.

**Comment by artembilan** [comment]
I'm reopening this one since it fails on CI https://build.spring.io/chain/result/viewChainResult.action?planKey=AMQP-MAIN&buildNumber=1656 and locally for me as well.
Somehow this super stream is not consumed at all.
When I make this change to the test:
```
			container.setQueueNames("ss.sac.test-0");
//			container.superStream("ss.sac.test", "test");
```
I got some interactivity:
```
(Body:'foo' MessageProperties [headers={}, contentType=text/plain, contentEncoding=UTF-8, contentLength=0, deliveryMode=PERSISTENT, expiration=0, priority=0, deliveryTag=0])
(Body:'foo' MessageProperties [headers={}, contentType=text/plain, contentEncoding=UTF-8, contentLength=0, deliveryMode=PERSISTENT, expiration=0, priority=0, deliveryTag=0])
(Body:'foo' MessageProperties [headers={}, contentType=text/plain, contentEncoding=UTF-8, contentLength=0, deliveryMode=PERSISTENT, expiration=0, priority=0, deliveryTag=0])
```
Which means that setup is OK, but super stream feature doesn't work.
Perhaps something else has to be configured in the environment...

I'm disabling `SuperStreamSACTests` for time being.

Thank you!

**Comment by acogoluegnes** [comment]
@artembilan The test passes on my machine with

```shell
./gradlew :spring-rabbit-stream:test --tests "org.springframework.rabbit.stream.listener.SuperStreamSACTests"
```

I suspect you're having an old Docker image in your cache, try to delete it and run the test again:

```shell
docker rmi pivotalrabbitmq/rabbitmq-stream
```

It may be the same on CI.

**Comment by artembilan** [comment]
Thank you, @acogoluegnes !

That really works.

I had to do it manually though:
```
docker rmi pivotalrabbitmq/rabbitmq-stream
docker logout
docker pull pivotalrabbitmq/rabbitmq-stream
```

Because Testcontainers somehow cannot pull the image for me - `invalid credentials` 😢 .

Will ask Trevor to remove that image from our CI Docker.

**Comment by eddumelendez** [comment]
@artembilan maybe time to upgrade from testcontainers `1.15.3` to `1.17.3`. IIRC the issue you are having should be solved by now.

**Comment by artembilan** [comment]
Thank you, @eddumelendez !

That really makes sense: I do use the latest Testcontainers in other projects.
Will update here shortly.

And will double check the anonymous image pull respectively 😉
