### ISSUE TITLE
Support `Optional<?>` Payloads in RabbitListener

### ISSUE THREAD

**Issue by daihuabin** [spring-projects/spring-amqp#1491]
**In what version(s) of Spring AMQP are you seeing this issue?**

since 2.1.0

**Describe the bug**

Do not create an issue to ask a question; see below.

**To Reproduce**

produce message

```java
        MessageProperties messageProperties = new MessageProperties();
        messageProperties.setContentType(MessageProperties.CONTENT_TYPE_JSON);
        Message message = null;
        try {
            message = new Message(new ObjectMapper().writeValueAsBytes(null), messageProperties);
        } catch (JsonProcessingException e) {
            throw new RuntimeException(e);
        }
```

consume message

```java
    @RabbitListener(queues = "queue.name")
    public void handleEvent(@Payload String text) throws JsonProcessingException {
        // expected text to be null, but it is the string "null"
    }
```

**Expected behavior**

expected text to be null

**Comment by garyrussell** [comment]
I reproduced it with this 

```java
@SpringBootApplication
public class Rgh1491Application {

	public static void main(String[] args) {
		SpringApplication.run(Rgh1491Application.class, args);
	}

	@Bean
	ApplicationRunner runner(RabbitTemplate template) {
		return args -> {
			MessageProperties messageProperties = new MessageProperties();
			messageProperties.setContentType(MessageProperties.CONTENT_TYPE_JSON);
			Message message = null;
			try {
				message = new Message(new ObjectMapper().writeValueAsBytes(null), messageProperties);
				template.send("foo", message);
			}
			catch (JsonProcessingException e) {
				throw new RuntimeException(e);
			}
		};
	}

	@RabbitListener(queues = "foo")
	void listen(String in) {
		System.out.println(in);
	}

	@Bean
	Jackson2JsonMessageConverter converter() {
		return new Jackson2JsonMessageConverter();
	}

}
```

However, it's Jackson that's returning "null" which has nothing to do with Spring.

However, even if jackson created a `null` it still wouldn't work because the spring-messaging `Message<?>` (used in the conversion) doesn't allow `null` payloads.

We could perhaps support `@Payload Optional<String> optional` and coerce `null` to that, but first, Jackson needs to produce a `null` before we can consider that.

**Comment by garyrussell** [comment]
Correction - it might not be Jackson's fault, we are inferring the `String` type from the method signature and telling Jackson to create a String; however, I would expect Jackson to complain because the encoded null is `null` instead of `"null"`.

**Comment by garyrussell** [comment]
Even when I configured the converter to return `null`, we end up falling back to the message body (as stated in the OP). I think we can add an option to the converter to allow null values; but, for the reasons I mentioned, the method signature will have to be `Optional<String>` (or `Optional<Foo>` etc).

**Comment by garyrussell** [comment]
Another thought
```java
public void handleEvent(@Payload(required = false) String text)
```
and the framework can coerce `Optional.EMPTY` to `null` - I think that's cleaner.

**Comment by artembilan** [comment]
I guess the `PayloadMethodArgumentResolver.isEmptyPayload()` could be improved to support `Optional` as well.

In Spring Integration I have a similar `NullAwarePayloadArgumentResolver` which I set into the `DefaultMessageHandlerMethodFactory`.
