### ISSUE TITLE
Delay in MessageProperties is using Integer when it should be using Long data type, not allowing max delay to be used

### ISSUE THREAD

**Issue by diegodss** [spring-projects/spring-amqp#1496]
The method setDelay and getDelay in MessageProperties use an integer as its data type. 

The integer data type will have a max value 2147483647

According to rabbitmq-delayed-message-exchange plugin documentation, x-delay supports up to (2^32)-1 milliseconds which is 4294967295 

(In Erlang a timer can be set up to (2^32)-1 milliseconds in the future).
https://github.com/rabbitmq/rabbitmq-delayed-message-exchange#performance-impact

The question is: Shouldn't setDelay and getDelay use Long as its data type?

Reference for setDelay and getDelay in here:
https://github.com/spring-projects/spring-amqp/blob/97644e95e014157ced925c2a8d8ec3cc689d425b/spring-amqp/src/main/java/org/springframework/amqp/core/MessageProperties.java#L442

**Comment by garyrussell** [comment]
Java doesn't have an unsigned integer.

It makes no sense to me to delay a message for 25 days, let alone 49 days.

If you really want to do that, use

```java
msg.getMessageProperties().setHeader(MessageProperties.X_DELAY, 0xffffffffL);
```

**Comment by diegodss** [comment]
Sounds good to me. Thank you Gary
