### ISSUE TITLE
queues-missing-fatal=true feature should change the actuator state to DOWN

### ISSUE THREAD

**Issue by llaros** [spring-projects/spring-amqp#1504]
Hello spring-amqp team!

Application which is starting or running and could not find a queue for the consumer should be marked unhealthy or other status than UP.

We have a problem with rabbitmq, because as a client connects we expect all the queues to be up and running. We encountered the known problem on production when one of the cluster rabbit nodes is restarted and we had queues-missing-fatal=true setting, the consumer was stopped "Stopping container from aborted consumer", but we were not aware of that, because after the start of the rabbit node the actuator shows the application is healthy again. 

If we set the queues-missing-fatal=false we achieved a better recoverable setting for a customer however we would like also to have some actuator health statuses that would notify our kubernetes orchiestrator that we have some consumer not working before they recovered.

Probably this could be achieved with some custom healthcheck indicator code.

**Comment by garyrussell** [comment]
This should be moved to spring-boot; this actuator is not part of this project.

Boot's actuator only examines the state of the rabbitmq connection, it does not look at the running state of all the listener containers.

**Comment by llaros** [comment]
@garyrussell thanks, I am able to achieve what we want leveraging AmqpEvent(s).
