### ISSUE TITLE
Add ability to set consumer priority with AmqpTemplate

### ISSUE THREAD

**Issue by nreinhardt** [spring-projects/spring-amqp#1533]
**Expected Behavior**

It should be possible to configure consumer arguments when consuming with RabbitTemplate. In my particular use case, I would like to set the [consumer priority](https://www.rabbitmq.com/consumer-priority.html) when consuming with an AmqpTemplate instance.

**Current Behavior**

Currently, it is [impossible](https://stackoverflow.com/a/74449092/12201478) to set the consumer arguments when consuming with AmqpTemplate.

**Context**

In my particular use case, I would like to:
- Set the consumer priority to a particular value
- Wait indefinitely until a message can be received.
- Process the message, which may take several minutes.
- Terminate the program

There is some documentation for [configuring](https://docs.spring.io/spring-amqp/reference/html/#consumer-priority) the consumer priority when performing asynchronous consumption. However, I haven't found a solution for synchronous consumption.

**Comment by nreinhardt** [comment]
Prompted by [Gary Russell](https://stackoverflow.com/questions/74448938/how-to-set-consumer-priority-with-amqptemplate/74449092#74449092). Thanks for the prompt response!

**Comment by garyrussell** [comment]
https://stackoverflow.com/questions/74448938/how-to-set-consumer-priority-with-amqptemplate/74449092?noredirect=1#comment131425664_74449092
