### ISSUE TITLE
Missing Javadocs for MessageProperties.expiration

### ISSUE THREAD

**Issue by german-komarov** [spring-projects/spring-amqp#1539]
https://github.com/spring-projects/spring-amqp/blob/3fa56c0d0cfdbf9c9b2da6fc216e604090ceb5d3/spring-amqp/src/main/java/org/springframework/amqp/core/MessageProperties.java#L318

Will this issue be solved, because neither in the code, nor in docs https://docs.spring.io/spring-amqp/api/org/springframework/amqp/core/MessageProperties.html#setExpiration(java.lang.String) , it is not clear in which format this "String expiration" parameter can be set. Can you clarify or fix it, please. 

P.S Anyway thank you for amazing amqp library, it is really powerful and useful.

**Comment by garyrussell** [comment]
This is just a reflection of the underlying AMQP 0.9.1 specification which, oddly, defines the property as a String.

https://www.rabbitmq.com/protocol.html

https://www.rabbitmq.com/resources/specs/amqp-xml-doc0-9-1.pdf

It, too, has no indication of the format.

This document indicates it is a String representing the time to live in milliseconds.

https://www.rabbitmq.com/ttl.html

We will update the javadocs to reflect that.
