### ISSUE TITLE
Extend the 'SimpleContainer' properties in the 'RabbitProperties' with 'receiveTimeout'

### ISSUE THREAD

**Issue by AndreasKuebl** [spring-projects/spring-amqp#1544]
As often mentioned in the documentation you should set a receive-timeout in the SMLC if you work with batched messages. 

Currently if you want to work with "batched - messages" you can configure this in the properties, but you can not configure the receive-timeout. Therefore you always have to define the SMLC bean yourself and you can't just use the auto configured bean.

My suggestion would be to extend the org.springframework.boot.autoconfigure.amqp.RabbitProperties.SimpleContainer with the property 'receiveTimeout', you have to consider the field in the org.springframework.boot.autoconfigure.amqp.SimpleRabbitListenerContainerFactoryConfigurer.

What do you think about this or did I miss the setting?

**Comment by artembilan** [comment]
What you are talking about is[ Spring Boot](https://github.com/spring-projects/spring-boot) responsibility.
Please, consider to raise this issue exactly over there.
Thanks.

**Comment by garyrussell** [comment]
As a work around, you can do something like this...
```java
@Bean
Object cust(SimpleRabbitListenerContainerFactory factory) {
	factory.setReceiveTimeout(5000L);
	factory.setBatchListener(true);
	return null;
}
```
