### ISSUE TITLE
Bad check for Mono return type in org.springframework.amqp.rabbit.listener.adapter.HandlerAdapter constructor

### ISSUE THREAD

**Issue by andruskutt** [spring-projects/spring-amqp#1550]
In class:
https://github.com/spring-projects/spring-amqp/blob/main/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/HandlerAdapter.java#L52

there seems to be check for Mono - MonoHandler.isMono(invokerHandlerMethod.getMethod().getReturnType()))
But MonoHandler.isMono contains "instanceof" check, not "isAssignableFrom", so this check will be always false, because check is done against Class<?>

**Comment by garyrussell** [comment]
Can you provide a concrete example? We have a test case:

https://github.com/spring-projects/spring-amqp/blob/c88a6580d9e0143ce9c84da346d4dc49fe4e2ebd/spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/AsyncListenerTests.java#L297-L305

**Comment by artembilan** [comment]
It looks like we need an overloaded:
```
	static boolean isMono(Class<?> result) {
		return Mono.class.isAssignableFrom(result);
	}
```
We still use an existing one in the `AbstractAdaptableMessageListener`.

I guess it works OK with the `Mono` processing, but that `isAsyncReplies()` has some effects on the acknowledges in some container implementations...
