### ISSUE TITLE
Irrelevant values in CachingConnectionFactory#toString

### ISSUE THREAD

**Issue by arn-rio** [spring-projects/spring-amqp#1560]
https://github.com/spring-projects/spring-amqp/blob/ccf202bdb27ed3090cc55e1359c4cb1ac1e9767a/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactory.java#L1044

Hello,

Host and port values should not be displayed when addresses attribute is defined (in AbstractConnectionFactory class) as connect method use addresses first.

Thanks.

**Comment by artembilan** [comment]
We also can set an `AddressResolver` instead of all those.
Therefore it looks like it is better just to remove `host/port` from this `CachingConnectionFactory.toString()`.

**Comment by arn-rio** [comment]
Thanks for the fix. The message misled me while debugging.
