### ISSUE TITLE
AbstractMessageListenerContainer.redeclareElementsIfNecessary does not take into account Declarables

### ISSUE THREAD

**Issue by mirkoluchi** [spring-projects/spring-amqp#2432]
**In what version(s) of Spring AMQP are you seeing this issue?**

2.4.7

**Describe the bug**

The message listener container, when restarted because of a consumer's failure, attempts to redeclare the queues. The code doing that - however - does not take into account queues that are declared using a bean of type Declarables.

**To Reproduce**

- Declare a Queue using a Declarables bean
- Declare a consumer on that queue
- While the application is running, delete the queue
- The consumer fails, attempts to restart and redeclare missing queues, but our queue is not redeclared (if the queue was instead declared as a bean of type Queue, the redeclaration would succeed).

**Expected behavior**

The consumer should redeclare also queues provided through beans of type Declarables.

**Example**

Here you can find 2 tests:
- QueueRedeclarationTest ==> succeeds showing that deleted queues are redeclared, if they are provided as Queue bean
- DeclarablesRedeclarationTest ==> fails showing that the same test described above fails if queues are declared using Declarables
https://github.com/mirkoluchi/springboot-rabbitmq-issue-2432

**Comment by garyrussell** [comment]
Queue deletion is not something that the framework can recover from.

Redeclaration occurs when a connection is lost; when the connection is re-established, queues are redeclared (in case they were auto delete queues).

When a queue is deleted via some other means (e.g. directly on the admin UI), there is no connection interruption, and therefore redeclaration cannot occur.

**Comment by mirkoluchi** [comment]
Actually the current behaviour is that a queue (declared using a Queue bean) is redeclared if deleted from the rabbit server.
So I would expect the same to happen for queues that are declared using Declarables bean.
I'm attaching a test soon.

**Comment by garyrussell** [comment]
Hmmm; reopened.

**Comment by garyrussell** [comment]
Thanks; will take a look.

**Comment by garyrussell** [comment]
Thanks for the repro; this (redeclaration) was an unintended side-effect of a fix but, since it has been there for 6+ years, I will change the code to deal with the newer `Declarables` beans.
