### ISSUE TITLE
Spring amqp doesnt support more than 1 server-named/anonymous queues

### ISSUE THREAD

**Issue by emoen** [spring-projects/spring-amqp#2439]
*In what version(s) of Spring AMQP?
2.3.10

*Describe the bug
2 anonymous queues - with different bindings - results in 1 queue with both bindings and 1 queue with no bindings

*To Reproduce
See stackexchange: https://stackoverflow.com/questions/75823022/spring-amqp-queuebuilder-should-hold-ref-to-queue-and-not-string-name

*Expected behavior
2 anonymous queues - with different bindings - should have a server-generated queue-name and each binding assign to it

**Comment by garyrussell** [comment]
Here is a workaround until the release is available:

```java
	@Bean
	Queue q1() {
		return QueueBuilder.nonDurable("").build();
	}

	@Bean
	Queue q2() {
		return QueueBuilder.nonDurable("").build();
	}

	@Bean
	Binding b1(Queue q1, DirectExchange ex) {
		return new Binding(q1.getName(), DestinationType.QUEUE, "ex", "foo", Collections.emptyMap()) {

			@Override
			public String getDestination() {
				return q1.getActualName();
			}

		};
	}

	@Bean
	Binding b2(Queue q2, DirectExchange ex) {
		return new Binding(q2.getName(), DestinationType.QUEUE, "ex", "bar", Collections.emptyMap()) {

			@Override
			public String getDestination() {
				return q2.getActualName();
			}

		};
	}

	@Bean
	DirectExchange ex() {
		return new DirectExchange("ex");
	}
```
