### ISSUE TITLE
Bindings are incorrect for multiple queues with empty name after recovering

### ISSUE THREAD

**Issue by Kilipurt** [spring-projects/spring-amqp#2441]
The spring boot 2.7.2 is used with spring-boot-starter-amqp.

Bindings are incorrect after recovery when multiple queues with an empty name (server-named) are used with the same RabbitAdmin.
The first queue has binding to exchange with the "#" routing key. The second queue has another binding to the same exchange, but differ routing key like "\*.\*.5". There are two queues as expected after losing and establishing a connection to rabbitmq. However, one of the queues has no bindings, but the second one has two bindings to exchange with both routing keys.

The expected result is two queues with the same bindings as before the lost connection.

I think the problem is in `org.springframework.amqp.rabbit.core.RabbitAdmin#initialize` that declares bindings by queue name. However, in this situation, both queues have the same name.

Steps to reproduce:

1. Make configuration as in the sample below.
2. Simulate losing connection with rabbitmq by disabling the internet or stopping rabbitmq service.
3. Restore connection with rabbitmq (enable internet or run rabbitmq service).
4. Check recovered queues and their bindings.

Configuration sample:

```
    @Bean
    public Queue queue1(RabbitAdmin rabbitAdmin) {
        Queue queue = new Queue("", false, true, true);
        queue.setAdminsThatShouldDeclare(rabbitAdmin);
        rabbitAdmin.declareQueue(queue);
        return queue;
    }
    
    @Bean
    public Binding binding1(RabbitAdmin rabbitAdmin, Queue queue1) {
        Binding binding = new Binding(queue1.getName(), Binding.DestinationType.QUEUE, "exchange", "*.*.5", new HashMap<>());
        binding.setAdminsThatShouldDeclare(rabbitAdmin);
        rabbitAdmin.declareBinding(binding);
        return binding;
    }
    
    @Bean
    public Queue queue2(RabbitAdmin rabbitAdmin) {
        Queue queue = new Queue("", false, true, true);
        queue.setAdminsThatShouldDeclare(rabbitAdmin);
        rabbitAdmin.declareBinding(binding);
        return queue;
    }

    @Bean
    public Binding binding2(RabbitAdmin rabbitAdmin, Queue queue2) {
        Binding binding = new Binding(queue2.getName(), DestinationType.QUEUE, "exchange", "#", new HashMap());
        binding.setAdminsThatShouldDeclare(rabbitAdmin);
        rabbitAdmin.declareBinding(binding);
        return binding;
    }
```

**Comment by artembilan** [comment]
Isn't this related somehow to this one: https://github.com/spring-projects/spring-amqp/issues/2439 ?

**Comment by garyrussell** [comment]
With the fix, you would use

```java
    @Bean
    public Binding binding2(RabbitAdmin rabbitAdmin, Queue queue2) {
        Binding binding = new Binding(queue2, DestinationType.QUEUE, "exchange", "#", new HashMap());
        binding.setAdminsThatShouldDeclare(rabbitAdmin);
//        rabbitAdmin.declareBinding(binding);
        return binding;
    }
```

By the way, you should NOT call the admin from a bean definition; the framework will do that for you at the correct time.

**Comment by artembilan** [comment]
And that one is probably wrong.
It feels like an error must be thrown from the broker to notify the client that there is no way to determine the target queue for binding...

**Comment by Kilipurt** [comment]
> With the fix, you would use
> 
> ```java
>     @Bean
>     public Binding binding2(RabbitAdmin rabbitAdmin, Queue queue2) {
>         Binding binding = new Binding(queue2, null, DestinationType.QUEUE, "exchange", "#", new HashMap());
>         binding.setAdminsThatShouldDeclare(rabbitAdmin);
> //        rabbitAdmin.declareBinding(binding);
>         return binding;
>     }
> ```
> 
> By the way, you should NOT call the admin from a bean definition; the framework will do that for you at the correct time.

What to do if there are multiple RabbitAdmin beans? Does it work correctly?

**Comment by garyrussell** [comment]
Work around here: https://github.com/spring-projects/spring-amqp/issues/2439#issuecomment-1481638789
