### ISSUE TITLE
Consider to add Rabbit Stream auto-creation hook

### ISSUE THREAD

**Issue by artembilan** [spring-projects/spring-amqp#2445]
Currently we have to use something like `Environment.streamCreator().stream("stream.stream").create()` which even is not mentioned in the docs: https://docs.spring.io/spring-amqp/reference/html/#super-streams.
We do have an auto-creation for `SuperStream` though, perhaps something similar could be achieved for regular stream.
Something like this:

```
@Bean
Stream myStream(Environment env) {
    return Stream.builder().environment(env).name(...).build();
}
```

Or something like `Map.of("x-queue-type", "stream")` for regular `Queue` declaration is enough so far?
Shouldn't this be mentioned in the doc then somehow?

Also there is no pointers in the doc about `spring-rabbit-stream` dependency.

We also need to present a sample application somewhere.

@joshlong also asked about Rabbit Stream checkbox on start.spring.io, similar to the Apache Kafka Streams, but that fully different story.

**Comment by garyrussell** [comment]
FYI, we already have support in the `QueueBuilder`:

https://github.com/spring-projects/spring-amqp/blob/976b3df760ef0458464cde5019ae5f523386298a/spring-amqp/src/main/java/org/springframework/amqp/core/QueueBuilder.java#L256-L263

But I agree it is missing from the docs.
