### ISSUE TITLE
Using AsyncRabbitTemplate. ConvertSendAndReceive return RabbitConverterFuture display Reply timed out, how to solve?

### ISSUE THREAD

**Issue by awen112** [spring-projects/spring-amqp#2478]
Using AsyncRabbitTemplate. ConvertSendAndReceive return RabbitConverterFuture display Reply timed out, how to solve?

future.whenComplete((result, ex) -> {
            if (ex == null) {
            } else {
            }
        });

**Comment by awen112** [comment]
org.springframework.amqp.core.AmqpReplyTimeoutException: Reply timed out
	at org.springframework.amqp.rabbit.TimeoutTask.run(TimeoutTask.java:56)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by garyrussell** [comment]
Yes, it simply means that no reply was received within the timeout.

**Comment by garyrussell** [comment]
Closing due to lack of response.

**Comment by BenEfrati** [comment]
If an exception is thrown by `messageConverter.fromMessage(message) `
https://github.com/spring-projects/spring-amqp/blob/1c49e579064152ad9730d24387336ccb32357f89/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/AsyncRabbitTemplate.java#L611, 
it results in an AmqpReplyTimeoutException.
 This happens because the directReplyToContainer in AsyncRabbitTemplate does not provide an option to set a custom ErrorHandler.

**Comment by artembilan** [comment]
@BenEfrati ,
I believe that is a default behavior.
However you an use different constructor with custom error handler:
```
	/**
	 * Construct an instance using the provided arguments. The first queue the container
	 * is configured to listen to will be used as the reply queue. Replies will be
	 * routed using the default exchange with that queue name as the routing key.
	 * @param template a {@link RabbitTemplate}
	 * @param container a {@link AbstractMessageListenerContainer}.
	 */
	public AsyncRabbitTemplate(RabbitTemplate template, AbstractMessageListenerContainer container) {
```
Same `DirectReplyToMessageListenerContainer` can be used here.

**Comment by BenEfrati** [comment]
@artembilan,
Tried that as well, it's not just the error handler, the rabbit future.exceptionally can't be called using the `AsyncRabbitTemplate ` message listener

```
	/**
	 * Construct an instance using the provided arguments. The first queue the container
	 * is configured to listen to will be used as the reply queue. If 'replyAddress' is
	 * null, replies will be routed using the default exchange with that queue name as the
	 * routing key. Otherwise it should have the form exchange/routingKey and must
	 * cause messages to be routed to the reply queue.
	 * @param template a {@link RabbitTemplate}.
	 * @param container a {@link AbstractMessageListenerContainer}.
	 * @param replyAddress the reply address.
	 */
	public AsyncRabbitTemplate(RabbitTemplate template, AbstractMessageListenerContainer container,
			String replyAddress) {
		Assert.notNull(template, "'template' cannot be null");
		Assert.notNull(container, "'container' cannot be null");
		this.template = template;
		this.container = container;
		this.container.setMessageListener(this); 
		this.directReplyToContainer = null;
		if (replyAddress == null) {
			this.replyAddress = container.getQueueNames()[0];
		}
		else {
			this.replyAddress = replyAddress;
		}
	}

...

@Override
	public void onMessage(Message message, Channel channel) {
		MessageProperties messageProperties = message.getMessageProperties();
		if (messageProperties != null) {
			String correlationId = messageProperties.getCorrelationId();
			if (StringUtils.hasText(correlationId)) {
				if (this.logger.isDebugEnabled()) {
					this.logger.debug("onMessage: " + message);
				}
				RabbitFuture<?> future = this.pending.remove(correlationId);
				if (future != null) {
					if (future instanceof RabbitConverterFuture) {
						MessageConverter messageConverter = this.template.getMessageConverter();
						RabbitConverterFuture<Object> rabbitFuture = (RabbitConverterFuture<Object>) future;
						Object converted = rabbitFuture.getReturnType() != null
								&& messageConverter instanceof SmartMessageConverter smart
								? smart.fromMessage(message,
								rabbitFuture.getReturnType())
								: messageConverter.fromMessage(message); //exception thrown here
						rabbitFuture.complete(converted);
					}
					else {
						((RabbitMessageFuture) future).complete(message);
					}
				}
				else {
					if (this.logger.isWarnEnabled()) {
						this.logger.warn("No pending reply - perhaps timed out: " + message);
					}
				}
			}
		}
	}
```
`AbstractMessageListenerContainer.executeListenerAndHandleException` doesn't call to rabbitFuture.completeExceptionally , leads to AmqpReplyTimeoutException

**Comment by artembilan** [comment]
OK. So, you mean we have to add a `try..catch` into that `onMessage()` method and call `rabbitFuture.completeExceptionally()` from there?
Feel free to contribute the fix: https://github.com/spring-projects/spring-amqp/blob/main/CONTRIBUTING.adoc !
