### ISSUE TITLE
Add Mechanism to set Container Thread Names

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-amqp#2479]
See https://github.com/spring-projects/spring-kafka/issues/2501

**Comment by bdshadow** [comment]
I would like to do this. Actually, I've already started, but it turned out to be a little more difficult than in Kafka. I will provide a merge request soon

**Comment by artembilan** [comment]
I'm closing this one in favor of `setTaskExecutor(new VirtualThreadTaskExecutor("my-virtual-threads-"))` option.
Otherwise you would have a paradox of choice and might lead yourself into some trap where you would inject a custom executor and that thread naming supplier.

Thanks for understanding.
