### ISSUE TITLE
Examine synchronized Block Usage

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-amqp#2481]
Possibly replace with reentrant locks to avoid pinning virtual threads.

**Comment by EddieChoCho** [comment]
This [article of Java 21 Virtual Thread](https://docs.oracle.com/en/java/javase/21/core/virtual-threads.html#GUID-704A716D-0662-4BC7-8C7F-66EE74B1EDAD) mentioned that:
```
A virtual thread cannot be unmounted during blocking operations when it is pinned to its carrier. A virtual thread is pinned in the following situations:

The virtual thread runs code inside a synchronized block or method
```
Do the usages of synchronized methods also need to be examined?

**Comment by garyrussell** [comment]
Yes, this includes those.

**Comment by garyrussell** [comment]
This needs to be fixed too. See the linked Boot issue.

https://github.com/spring-projects/spring-amqp/blob/c5489e291249d3da7b8c771b673441099ffcc84f/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainer.java#L174

**Comment by artembilan** [comment]
Raised separate issue: https://github.com/spring-projects/spring-amqp/issues/2568 since that one is not so trivial to fix.
Therefore better to tackle it in its own narrowed scope.
