### ISSUE TITLE
Jackson2JsonMessageConverter: New ObjectMapper instance not aware of jsr310 module

### ISSUE THREAD

**Issue by MichaelRisthausEviden** [spring-projects/spring-amqp#2516]
**In what version(s) of Spring AMQP are you seeing this issue?**

3.0.6

**Describe the bug**

We are transporting Pojos over AMQP. These Pojos also include Java8 Time objects like LocalDateTime. Our application ran in a ""java 8 date/time type `java.time.localdatetime` not supported by default" error although jackson-datatype-jsr310 was present in the classpath.

**To Reproduce**

Return a Pojo including Java8 Time objects in a @RabbitListener annotated method.

**Expected behavior**

The returned Pojo (including Java8 Time objects) should be converted to JSON without any error if  jackson-datatype-jsr310 is present in the classpath.

***Solution**

The problem itself was that we provied a Jackson2JsonMessageConverter in our project using its default constructor, see:

https://github.com/spring-projects/spring-amqp/blob/c845cb7cc5d8d39224e3ea219fb3b005f35963f4/spring-amqp/src/main/java/org/springframework/amqp/support/converter/Jackson2JsonMessageConverter.java#L45C9-L45C37

This calls the construcor which creates a new ObjectMapper instance, see:

https://github.com/spring-projects/spring-amqp/blob/c845cb7cc5d8d39224e3ea219fb3b005f35963f4/spring-amqp/src/main/java/org/springframework/amqp/support/converter/Jackson2JsonMessageConverter.java#L58

This new ObjectMapper is not aware of any additional Jackson modules in the classpath. Since the mapper receives already some configuration in this constructor, I suggest to add a this.objectMapper.findAndRegisterModules() there.

I'll provide a pull request for this.

**Comment by artembilan** [comment]
I'm converting this into an `Enhancement` since there is respective ctor you can use to mitigate expectations `Jackson2JsonMessageConverter(ObjectMapper jsonObjectMapper)`.
Will provide the fix shortly for `main` to make the target configuration easier.
