### ISSUE TITLE
Consumer failed to start in 60000 milliseconds

### ISSUE THREAD

**Issue by wade-bigdata** [spring-projects/spring-amqp#2518]
**In what version(s) of Spring AMQP are you seeing this issue?**

3.0.8

**Describe the bug**
I'm using SimpleMessageListenerContainer without setting queues before start, i want to set queues after spring boot application started, code as follow:
   ```
   @Qualifier("rabbitListenerContainerFactory")
    private AbstractRabbitListenerContainerFactory containerFactory;
    
    @PostConstruct
    void initialize() {
        listenerContainer = (SimpleMessageListenerContainer) containerFactory.createListenerContainer();
        listenerContainer.setupMessageListener(this);
        listenerContainer.start();
    }

    @Override
    public void subscriber(String topic, MessageConsumer listener) {
        String usingTopic = bindExchangeIfNeed(topic, listener);
        addConsumer(topic, listener);
        listenerContainer.addQueueNames(usingTopic);
    }

```
I startd spring boot application, it paused for one minute then print error log "Consumer failed to start in 60000 milliseconds; does the task executor have enough threads to support the container concurrency?", then i test the program, it can sending and receiving message normally，but when i set logging.level.org.springframework.amqp.rabbit.listener=debug for troubleshooting，i noticed the error and  pause disappeared, it's strange。

**Comment by garyrussell** [comment]
Please provide an [MCRE](https://stackoverflow.com/help/minimal-reproducible-example) that exhibits this behavior.

**Comment by garyrussell** [comment]
Ok; it looks like the issue is because you are starting the container with no queues initially

>`Consumer stopping; no queues for Consumer@2f04105: tags=[[]], channel=null, acknowledgeMode=AUTO local queue size=0`

Not sure why right now, because we still count the start latch down.

However; it still remains bad practice to start active components in `@PostConstruct` methods.

**Comment by garyrussell** [comment]
By the way, `DirectMessageListenerContainer`s are much more efficient when adding/removing queues at runtime.

https://docs.spring.io/spring-amqp/docs/current/reference/html/#choose-container

**Comment by garyrussell** [comment]
It is indeed caused by what I described (starting the container in `@PostConstruct`).

The problem is that the `RabbitMessageTemplate` is still in construction on the main thread, and holds the `singletonObjects` monitor (lock) for the  bean factory.

When we stop the container (due to no queues), we attempt to publish an event `new AsyncConsumerStoppedEvent(SimpleMessageListenerContainer.this, this.consumer))` and the event publisher needs the lock to find application listeners for the event; hence the deadlock for the default consumer start time of 60 seconds.

Deferring the `start()` to the first `subscribe()` solves the problem...

```java
    private final AtomicBoolean started = new AtomicBoolean();

    @PostConstruct
    void initialize() {
        listenerContainer = (AbstractMessageListenerContainer) containerFactory.createListenerContainer();
        listenerContainer.setupMessageListener(this);
    }
    
    public void subscribe(String topic){
        rabbitAdmin.declareExchange(new FanoutExchange(topic));
        Queue usingQueue = new Queue(topic + "_queue");
        rabbitAdmin.declareQueue(usingQueue);
        rabbitAdmin.declareBinding(BindingBuilder.bind(usingQueue)
                .to(new FanoutExchange(topic)));
        listenerContainer.addQueueNames(usingQueue.getName());
        if (!started.getAndSet(true)) {
            listenerContainer.start();
        }
    }
```

**Comment by wade-bigdata** [comment]
> It is indeed caused by what I described (starting the container in `@PostConstruct`).
> 
> The problem is that the `RabbitMessageTemplate` is still in construction on the main thread, and holds the `singletonObjects` monitor (lock) for the bean factory.
> 
> When we stop the container (due to no queues), we attempt to publish an event `new AsyncConsumerStoppedEvent(SimpleMessageListenerContainer.this, this.consumer))` and the event publisher needs the lock to find application listeners for the event; hence the deadlock for the default consumer start time of 60 seconds.
> 
> Deferring the `start()` to the first `subscribe()` solves the problem...
> 
> ```java
>     private final AtomicBoolean started = new AtomicBoolean();
> 
>     @PostConstruct
>     void initialize() {
>         listenerContainer = (AbstractMessageListenerContainer) containerFactory.createListenerContainer();
>         listenerContainer.setupMessageListener(this);
>     }
>     
>     public void subscribe(String topic){
>         rabbitAdmin.declareExchange(new FanoutExchange(topic));
>         Queue usingQueue = new Queue(topic + "_queue");
>         rabbitAdmin.declareQueue(usingQueue);
>         rabbitAdmin.declareBinding(BindingBuilder.bind(usingQueue)
>                 .to(new FanoutExchange(topic)));
>         listenerContainer.addQueueNames(usingQueue.getName());
>         if (!started.getAndSet(true)) {
>             listenerContainer.start();
>         }
>     }
> ```

I got it ,thank you!
