### ISSUE TITLE
Failed to check/redeclare auto-delete queue(s) - missing exception cause

### ISSUE THREAD

**Issue by dzoech** [spring-projects/spring-amqp#2523]
**In what version(s) of Spring AMQP are you seeing this issue?**

3.0.6

**Describe the bug**

We sporadically see the error log
`2023-08-07 14:32:34.768 UTC ERROR [deadLetterQueueListenerContainer-10] SimpleMessageListenerContainer: Failed to check/redeclare auto-delete queue(s).`
Unfortunately, the error log is missing the exception that caused it, which obviously makes it hard to debug in a larger system.

I suspect in our case this happens when the application starts. Looking at `AbstractMessageListenerContainer.java` below, `this.logDeclarationException` is always false when something fails already during startup. 

```java
protected synchronized void redeclareElementsIfNecessary() {
		AmqpAdmin admin = getAmqpAdmin();
		if (!this.lazyLoad && admin != null && isAutoDeclare()) {
			try {
				attemptDeclarations(admin);
				this.logDeclarationException.set(true);
			}
			catch (Exception e) {
				if (RabbitUtils.isMismatchedQueueArgs(e)) {
					throw new FatalListenerStartupException("Mismatched queues", e);
				}
				if (this.logDeclarationException.getAndSet(false)) {
					this.logger.error("Failed to check/redeclare auto-delete queue(s).", e);
				}
				else {
					this.logger.error("Failed to check/redeclare auto-delete queue(s).");
				}
			}
		}
	}
```

**To Reproduce**

Just connect to an non-existing host :-)

**Expected behavior**

I'd at least expect one exception logged before switching to logs without a full stack trace. 
According to https://github.com/spring-projects/spring-amqp/pull/1523 this was introduced to reduce log spam when the host is temporarily unavailable.

My suggestion would be to initialize `this.logDeclarationException` with true, so the first occurrence of an exception still logs the stack trace. I can prepare a PR if you like.

**Sample**
-

**Comment by artembilan** [comment]
Sorry, I'm not sure where is the problem.
According to the current `AbstractMessageListenerContainer` we have this logic:
```
private final AtomicBoolean logDeclarationException = new AtomicBoolean(true);
```
So, when `attemptDeclarations(admin);` throws an exception on a first attempt, we go to that `if (this.logDeclarationException.getAndSet(false)) {` which is `true` for this first case.

What do I miss? 
What kind of change are you anticipating?

Thanks

**Comment by dzoech** [comment]
Hey, sorry for bothering you yesterday. Apparently the long working day took a toll on my brain -- the current behavior is exactly as I suggested. My log monitoring tool simply didn't show the log line correctly hence my wrong assumption. I was now able to dig up the stack trace.

Thank you for responding so quickly and my apologies again for stealing your time :)
