### ISSUE TITLE
How about expand Builder for Queue Object like durable()

### ISSUE THREAD

**Issue by Gyuchool** [spring-projects/spring-amqp#2529]
**Expected Behavior**
I would like to add more `autoDelete` or `exclusive` option builders to QueueBuilder.

**Current Behavior**
Currently, when using QueueBuilder, only the durable option can be set to `durable` or `nonDurable`, and the remaining `exclusive` or `autoDelete` cannot be set to false. Therefore, `new Queue()` is used instead of QueueBuilder. However, when using `new Queue()`, settings such as `x-message-ttl` must be added as shown in the code below.
```java
HashMap<String, Object> args = new HashMap<>();
args.put("x-message-ttl", 300_000L);

return new Queue(queueName, true, false, false, args);
```
QueueBuilder has `ttl()`, which is convenient, but it seems to be difficult to use, so I suggest expanding Queue's Builder pattern further and adding `exclusive` or `autoDelete` settings. 

**Context**

I want to use a QueueBuilder. However, QueueBuilder can only set autoDelete or exclusive settings to true. This part is inconvenient and I want to improve it. It seems possible to set the builder pattern to receive boolean type excusive and autoDelete as parameters. or I think it can be applied like the `durable()` and `nonDurable()`.

**Comment by garyrussell** [comment]
It is not clear why you need this. `exclusive` and `autoDelete` are both `false` by default so

```java
QueueBuilder.durable(queueName)
    .ttl(300_000)
    .build();
```

Will create the queue with those properties set to `false`.

**Comment by Gyuchool** [comment]
oh..! It's my mistake during testing. You are right. thanks😅
