### ISSUE TITLE
build branch 2.3.x, cannot download io.spring.docresources:spring-doc-resources:0.2.1.RELEASE

### ISSUE THREAD

**Issue by ChildrenGreens** [spring-projects/spring-amqp#2558]
build branch 2.3.x, cannot download `io.spring.docresources:spring-doc-resources:0.2.1.RELEASE`，I tried looking for it in `Maven Central` but couldn't find it.

I noticed this link ([notice-of-permissions-changes-to-repo-spring-io-january-2023](https://spring.io/blog/2022/12/14/notice-of-permissions-changes-to-repo-spring-io-january-2023)), and also understood that the spring project team made Permissions changed, but can all previous versions be uploaded to` Maven Central`.

**Comment by garyrussell** [comment]
2.3.x is no longer supported; even commercially. 

https://spring.io/projects/spring-amqp#support

**Comment by ChildrenGreens** [comment]
@garyrussell I solved the problem myself by following these steps:

1. I downloaded the [spring-doc-resources](https://github.com/spring-io/spring-doc-resources) source code and switched to the branch `v0.2.1.RELEASE`
2. Execute the command `./gradlew publishToMavenLocal`
3. Add `mavenLocal()` in **build.gradle** to let gradlew load from the local maven repository first.

I hope this helps others with this problem.

**Comment by garyrussell** [comment]
I am glad you found a solution, but you should really upgrade to at least 2.4.17 which is the latest/last OSS supported version compatible with the ancient Java 8. 

Even better, upgrade to 3.1.0 and join the Java 17+ community.

Each release contains important bug fixes.

**Comment by ChildrenGreens** [comment]
@garyrussell I tried switching to 2.4.x, but still can't download `io.spring.docresources:spring-doc-resources:0.2.1.RELEASE`

**Comment by ChildrenGreens** [comment]
> @garyrussell I tried switching to 2.4.x, but still can't download `io.spring.docresources:spring-doc-resources:0.2.1.RELEASE`, and the official deadline is 2023-11-24.

@garyrussell  ???
