### ISSUE TITLE
MessageProperties setDelay maximum value problem

### ISSUE THREAD

**Issue by raylax** [spring-projects/spring-amqp#2602]
Integer maximum value `2147483647`
but the maximum value for [rabbitmq-delayed-message-exchange](https://github.com/rabbitmq/rabbitmq-delayed-message-exchange#performance-impact) is `(2^32)-1=4294967295`
Is it a bug or a feature?

https://github.com/spring-projects/spring-amqp/blob/7c945986f82329d6adc23ce8c9b7483ea0301145/spring-amqp/src/main/java/org/springframework/amqp/core/MessageProperties.java#L454

**Comment by artembilan** [comment]
So, you idea is to let this header to be set to that `4294967295` as maximum?
Since the `Integer` cannot be more than `2147483647`, we probably need to change it to the `Long` and validate respectively.

Is that what you think?

Thanks

**Comment by raylax** [comment]
Yeah, I think that's right.
But would it be better to change it to `Long`or add a method like `setDelayLong`?

My English is not good, Sorry.

**Comment by artembilan** [comment]
Yes, `setDelayLong()` is good compromise for the current version.
We may mark the integer one as `@Deprecated` and will consider to remove it in the next version.

Please, consider to contribute such a fix: https://github.com/spring-projects/spring-amqp/blob/main/CONTRIBUTING.adoc
