### ISSUE TITLE
Kotlin suspend functions return type is incorrect

### ISSUE THREAD

**Issue by abelmulq** [spring-projects/spring-amqp#2638]
**In what version(s) of Spring AMQP are you seeing this issue?**

3.0.9(for my project)  & 3.2.3(latest version for demo)

**Describe the bug**

It is known in #1210 this library added a kotlin coroutine support.  This is fine as long as the function doesn't return a value. But as soon as our function returns a value the return value type resolver in [`AbstractAdaptableMessageListener.asyncSuccess`](https://github.com/spring-projects/spring-amqp/blob/90a80af635de334359dd4a90549b8e2c704e59b1/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/AbstractAdaptableMessageListener.java#L422) throws an error because it gets the invocation result type of `java.lang.Object` which can't be cast to `ParameterizedType`. 

**To Reproduce**

A kotlin coroutine with a return value of `String?`  annotated with `@RabbitListener`

**Expected behavior**

The return type must be correctly set in InvocationResult

**Sample**
https://github.com/abelmulq/spring-amqp-2638-sample

**Comment by abelmulq** [comment]
Thank you @artembilan for the quick fix.

**Comment by PsyBrainy** [comment]
Hello @abelmulq and @artembilan,

I've been following the discussion on Kotlin suspend function return types and appreciate the fixes and updates made. I am curious if similar support or modifications have been considered for the KafkaListener in the context of handling Kafka messages with Kotlin coroutines? Specifically, is there any ongoing work or planned updates to ensure that KafkaListeners can handle return types correctly when used with Kotlin suspend functions?

Thank you for your efforts and any information you can provide on this matter.

**Comment by artembilan** [comment]
@PsyBrainy ,

It would be great if you ask such a question in Spring for Apache Kafka project by itself.

Yes, that work has been done for the `@KafkaListener` as well. See respective GH issue: https://github.com/spring-projects/spring-kafka/issues/1189.

And docs for upcoming `3.2` version: https://docs.spring.io/spring-kafka/reference/3.2/whats-new.html#x32-async-return
