### ISSUE TITLE
Document that micrometer observations aren't started for batch listeners

### ISSUE THREAD

**Issue by tacascer** [spring-projects/spring-amqp#2647]
**Expected Behavior**

Documentation should clearly state that for batch listeners, observations are not started.

**Current Behavior**

It is not stated in documentation that observations are not started for batch listeners

**Context**

I was trying to figure out why my application was not sending metrics in the observation convention's name documented [here](https://docs.spring.io/spring-amqp/reference/appendix/micrometer.html). After setting `observationEnabled`, as per [here](https://docs.spring.io/spring-amqp/reference/amqp/receiving-messages/micrometer-observation.html), I expected the observations to be created.

Turns out that observations are not started for any input which isn't a single element, as per [here](https://github.com/spring-projects/spring-amqp/blob/main/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/AbstractMessageListenerContainer.java#L1502-L1507).

**Comment by artembilan** [comment]
Yeah...
I don't think we can provide an observation for the whole batch to process, since it is a combination of several consumed messages.
Therefore such an observation is left up to target handler implementation when it might be done per item in that collection.

We will fix docs respectively.

Or feel free to contribute such a note into that `micrometer.adoc`.

Thank you!

**Comment by tacascer** [comment]
> I don't think we can provide an observation for the whole batch to process, since it is a combination of several consumed messages.
Therefore such an observation is left up to target handler implementation when it might be done per item in that collection.

This makes sense. I'll take a look at updating the Micrometer Documentation

**Comment by artembilan** [comment]
@tacascer ,

We have a release scheduled for the next Monday.

Any chances this can be addressed meanwhile?

Thanks

**Comment by tacascer** [comment]
I'll do it today. Thanks for the reminder!
