### ISSUE TITLE
DefaultMessagePropertiesConverter#toMessageProperties should handle x-delay in Short

### ISSUE THREAD

**Issue by seanliu-oss** [spring-projects/spring-amqp#2667]
**In what version(s) of Spring AMQP are you seeing this issue?**
3.0.4
![image](https://github.com/spring-projects/spring-amqp/assets/28421998/a49f855f-2118-4bb1-a791-d906693325d4)

**Describe the bug**
When sending a message via delayed-message-exchange,  and get the message via amqpTemplate, we get a null receivedDelay

**To Reproduce**
Send a message via delayed-message-exchange, with a delay of 5 seconds. The message will show up with x-delay of -5000 in the queue:
![image](https://github.com/spring-projects/spring-amqp/assets/28421998/716ff7f8-3591-4c04-a85d-115ab1eae15b)

When using amqpTemplate to receive the message, it reaches DefaultMessagePropertiesConverter#toMessageProperties, the header value shows up as type Short:
![image](https://github.com/spring-projects/spring-amqp/assets/28421998/79db927a-610f-4f73-a8c3-06911ed3de73)
![image](https://github.com/spring-projects/spring-amqp/assets/28421998/b100a05e-b664-4ec9-98c8-b4675c86acbc)

Therefore the message will show up with receivedDelay as null.
![image](https://github.com/spring-projects/spring-amqp/assets/28421998/373a7099-adf7-40df-82a1-1b5fdd06df58)

While we are at it, we should also ensure receivedDelay is a positive number here, therefore a Math.abs() should help.
I did observe negative receivedDelay, but have not been able to reproduce it yet.

**Expected behavior**

The message should show up with receivedDelay as 5000

**Sample**

@SpringBootApplication
public class RabbitTestApplication implements CommandLineRunner {
    @Autowired
    private  AmqpTemplate amqpTemplate;

    public static void main(String[] args) {

        SpringApplication.run(BunyipRabbitTestApplication.class, args);
    }

    @Override
    public void run(String... args) throws Exception {
        Message message = amqpTemplate.receive("test-delay");
    }
}

**Comment by artembilan** [comment]
The `-5000` is even explained in the respective RabbitMQ docs: https://www.rabbitmq.com/blog/2015/04/16/scheduling-messages-with-rabbitmq#checking-if-a-message-was-delayed.
They also mention that this property is an `integer`.
Plus it is not clear how that can be a `short`: https://github.com/spring-projects/spring-amqp/issues/2602.

We probably can go ahead and try to resolve any `Number` impl over there into an expected long.

What RabbitMQ broker version do you use?

**Comment by seanliu-oss** [comment]
I am using 3.12.12 broker:
![image](https://github.com/spring-projects/spring-amqp/assets/28421998/17475ac8-31b6-40ba-9a7b-79f6b7344503)

I understand the where -5000 is from on the queue, but it looks like when client retrieves it, it provides back a positive number, I am not sure how the spec says about this behavior.
When I trace into ContentHeaderPropertyReader#readTable, the input stream's buffer has following values:
[0, 60, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15, -96, -64, 10, 116, 101, 120, 116, 47, 112, 108, 97, 105, 110, 0, 0, 0, 11, 7, 120, 45, 100, 101, 108, 97, 121, 115, 19, -120, 36, 48, 56, 54, 54, 53, 102, 52, 55, 45, 100, 100, 99, 48, 45, 52, 55, 101, 56, 45, 57, 54, 98, 56, 45, 56, 51, 56, 51, 53, 51, 100, 100, 57, 54, 49, 98, 0, 0, 0, 0, 102, 4, 104, -29]
If I print it out, I get  13, -78 after x-delay, which is 0x1388, and translate into 5000 . I am not sure why in this case in specs, but it seems like it.
     00
<    3c
     00
     00
     00
     00
     00
     00
     00
     00
     00
     0f
     -60
     -40

    0a
t    74
e    65
x    78
t    74
/    2f
p    70
l    6c
a    61
i    69
n    6e
     00
     00
     00
    0b
     07
**x    78
-    2d
d    64
e    65
l    6c
a    61
y    79
s    73
     13**
     -78
$    24
0    30
8    38
6    36
6    36
5    35
f    66
4    34
7    37
-    2d
d    64
d    64
c    63
0    30
-    2d
4    34
7    37
e    65
8    38
-    2d
9    39
6    36
b    62
8    38
-    2d
8    38
3    33
8    38
3    33
5    35
3    33
d    64
d    64
9    39
6    36
1    31
b    62
     00
     00
     00
     00
f    66
     04
h    68
     -1d

**Comment by artembilan** [comment]
Yeah... I'm not very good in parsing HEX, but if whatever I suggested before about `Number` interaction in the `DefaultMessagePropertiesConverter` makes sense for you, I'll be more than happy to provide that fix.

Thanks

**Comment by seanliu-oss** [comment]
That would be great, thanks.
