### ISSUE TITLE
Fix RabbitMQ x-death header documentation

### ISSUE THREAD

**Issue by ansd** [spring-projects/spring-amqp#2688]
The Spring Cloud Stream RabbitMQ Binder Reference Guide recommends that the AMQP 0.9.1 client re-publishes a message with the `x-death` header it received from RabbitMQ in order to determine the number of times (`count`) the message was received and re-published to RabbitMQ, see https://github.com/rabbitmq/rabbitmq-server/issues/10709#issuecomment-2063152062

We consider this an anti-pattern or even bug because AMQP 0.9.1 headers prefixed with `x-` including `x-death` "belong" to the broker and are not meant to be specially parsed and interpreted by the broker when received from an AMQP 0.9.1 client.

Hence, as explained [here](https://github.com/rabbitmq/rabbitmq-server/issues/10709#issuecomment-1997083246), we recommend changing the [documentation](https://github.com/search?q=repo%3Aspring-cloud%2Fspring-cloud-stream-binder-rabbit%20x-death&type=code) to instead use some custom **non** x-header to determine how often a message was re-published from the client to the broker.

Starting with RabbitMQ 4.0, the current documented pattern by Spring Cloud Stream RabbitMQ Binder Reference Guide will break.

**Comment by artembilan** [comment]
I'm not fully sure what you find as a wrong recommendation. I don't see any sentence in that doc which says something like `re-publishes a message with the x-death header it received from RabbitMQ`.
It indeed looks like we rely on the `x-death` to determine the `count` and sometimes an original `exchange/routing-key`, but no where we say explicitly that this header has to be set by the client code.

I think we just followed [Dead Letter Exchanges](https://www.rabbitmq.com/docs/dlx#effects) docs to deal with expectations after DLX.

Thanks

**Comment by ansd** [comment]
Thanks @artembilan for the clarification.
I got misled by the comment from @dvovney in https://github.com/rabbitmq/rabbitmq-server/issues/10709#issuecomment-2063152062
I close this issue for now.

**Comment by samragu** [comment]
Starting with RabbitMQ 3.13, the _count_ parameter in _x-death_ header is no longer incremented. This breaks SCSt applications that relied on this header and parameter to keep track of retry attempts. Note that spring-amqp/SCSt already sets another header _x-exception-stacktrace_ with Java exception stacktrace that resulted in the message being dead lettered. We will need another similar header, for example, _x-retry-attempt_ to carry the retry attempt (i.e., number of times the message is published to DLQ). Note that RabbitMQ is discouraging usage of x- prefixed headers, so both x-exception-stacktrace and x-retry-attempt should be renamed to something else

**Comment by artembilan** [comment]
I see. Would it be OK to have them as something like `spring-exception-stacktrace` and `spring-retry-attempt` respectively?
We have a number of others in the `RepublishMessageRecoverer`:
```
	public static final String X_EXCEPTION_STACKTRACE = "x-exception-stacktrace";

	public static final String X_EXCEPTION_MESSAGE = "x-exception-message";

	public static final String X_ORIGINAL_EXCHANGE = "x-original-exchange";

	public static final String X_ORIGINAL_ROUTING_KEY = "x-original-routingKey";
```

**Comment by ansd** [comment]
@artembilan 
> Would you mind, please, confirm that x-death header is still going to be present in the consumed message?

Yes, the `x-death` header including its count field will be present in a consumed message (if this message got previously dead lettered).

The only thing that changes in RabbitMQ 3.13 is that RabbitMQ (upon receiving) won't interpret anymore the `x-death` header when a client (re)publishes a message.

**Comment by artembilan** [comment]
Yeah... Nothing to fix here.
