### ISSUE TITLE
AbstractAdaptableMessageListener throws NPE when basicAck with async @RabbitListener and batch consumer

### ISSUE THREAD

**Issue by lagoshny** [spring-projects/spring-amqp#2721]
**In what version(s) of Spring AMQP are you seeing this issue?**

3.1.5

**Describe the bug**

When use Kotlin suspend (or reactive) `RabbitListener` with `consumerBatch` and `AcknowledgeMode.MANUAL` error occurs

```
Operator called default onErrorDropped java.lang.NullPointerException: Cannot invoke \"org.springframework.amqp.core.Message.getMessageProperties()\" because \"request\" is null\n\tat org.springframework.amqp.rabbit.listener.adapter.AbstractAdaptableMessageListener.basicAck(AbstractAdaptableMessageListener.java:444)
```

**To Reproduce**

**Below fragments using Kotlin**

Configure `SimpleRabbitListenerContainerFactory` with settings:

```kt
        val factory = SimpleRabbitListenerContainerFactory()
        // ...
        factory.setConsumerBatchEnabled(true)
        factory.setDeBatchingEnabled(true)
        factory.setBatchSize(100)
        factory.setPrefetchCount(100)
        factory.setAcknowledgeMode(AcknowledgeMode.MANUAL)
```

Define rabbit listener like this:

```kt
    @RabbitListener(queues = ["some-queue"], )
    suspend fun receiveSensorMessage(messages: List<String>): Unit {
        service.handleMessages(messages)
    }
```

And after recieve messages and handled its you will get an error:

```
Operator called default onErrorDropped java.lang.NullPointerException: Cannot invoke \"org.springframework.amqp.core.Message.getMessageProperties()\" because \"request\" is null\n\tat org.springframework.amqp.rabbit.listener.adapter.AbstractAdaptableMessageListener.basicAck(AbstractAdaptableMessageListener.java:444)
```

After some research source code of `spring-amqp` I have explanation why it is happens:

When we enable batch then used [BatchMessagingMessageListenerAdapter](https://github.com/spring-projects/spring-amqp/blob/1bad8ed99118cfb0aff5d21c94dcf6890a6cec0c/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/BatchMessagingMessageListenerAdapter.java#L43)

It is invokes [invokeHandlerAndProcessResult](https://github.com/spring-projects/spring-amqp/blob/1bad8ed99118cfb0aff5d21c94dcf6890a6cec0c/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/BatchMessagingMessageListenerAdapter.java#L94) method with `amqpMessage` = `null` and after [invokeHandler](https://github.com/spring-projects/spring-amqp/blob/1bad8ed99118cfb0aff5d21c94dcf6890a6cec0c/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/MessagingMessageListenerAdapter.java#L225) we get result as `MonoOnAssembly` therefore we also call [handleResult](https://github.com/spring-projects/spring-amqp/blob/1bad8ed99118cfb0aff5d21c94dcf6890a6cec0c/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/MessagingMessageListenerAdapter.java#L227C4-L227C16) method where we [basicAck](https://github.com/spring-projects/spring-amqp/blob/1bad8ed99118cfb0aff5d21c94dcf6890a6cec0c/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/AbstractAdaptableMessageListener.java#L400) will be called with `request` as null (because above we pass it as `amqpMessage` = `null`).

**Expected behavior**

No error occurs while using suspend `RabbitListener` with `consumerBatch` and `AcknowledgeMode.MANUAL`

**Comment by artembilan** [comment]
Have just pushed the fix for the next version.
I don't consider it to be back-ported since technically we never advertised that batch mode would work with async returns.
Anyway thank you for the detailed report!
