### ISSUE TITLE
Add Support for `x-consistent-hash`

### ISSUE THREAD

**Issue by tillieferguson** [spring-projects/spring-amqp#2728]
**Expected Behavior**

Support for consistent hash exchange type, which is now supported by rabbit mq

**Current Behavior**

**Context**

**Comment by artembilan** [comment]
The contribution is welcome: https://github.com/spring-projects/spring-amqp/blob/main/CONTRIBUTING.adoc

**Comment by artembilan** [comment]
More info in: https://github.com/rabbitmq/rabbitmq-consistent-hash-exchange

**Comment by artembilan** [comment]
Well, it is possible even right now.
You just use a `CustomExchange` instance when declare it from the application context.
Although I still see a benefit in having a top-level API in the `ExchangeBuilder`.
