### ISSUE TITLE
An endless loop when adjust consumers in DirectReplyToMessageListenerContainer

### ISSUE THREAD

**Issue by AlNadraga** [spring-projects/spring-amqp#2760]
Version: 2.4.17

**Describe the bug**

When the application starts, a message is sent to another service. During the start, the Rabbitmq broker crashed and the application began to write endlessly to the log line until it ran out of disk space.  The line was written to the log is `DEBUG(org.springframework.amqp.rabbit.listener.DirectReplyToMessageListenerContainer): Consume from queue amq.rabbitmq.reply-to ignore, container stopping`

**To Reproduce**

Unfortunately, this problem has occurred twice in half a year and I can't say for sure how it can be reproduced. But as far as I understand, this happens in the method `DirectMessageListenerContainer#adjustConsumers` in the method inside the loop `while (this.consumersByQueue.get(queue) == null || this.consumersByQueue.get(queue).size() < newCount)` . If we put a breakpoint there and set the container (`this.active == false`), then we are stuck in an endless loop.

**Expected behavior**

If the container is not active, then as far as I understand, we should not try to specify the number of consumers. At least in this situation, the thread should not hang in an endless loop.

**Comment by artembilan** [comment]
Since you don't answer, I decided to go ahead and incorporate the fix we have talked before.
Thanks
