### ISSUE TITLE
HeadersExchange with binding criteria does not work when producers dont send headers

### ISSUE THREAD

**Issue by TomerMadmon** [spring-projects/spring-amqp#2781]
**In what version(s) of Spring AMQP are you seeing this issue?**

- Checked on version 3.1.6

**Describe the bug**

When using RabbitMQ's Headers Exchange with Spring AMQP, messages without any headers are not checked against header conditions (e.g., `x-priority`). As a result, messages that should be routed based on header values end up in queues with default or fallback routing behavior. Specifically, if a message has no headers, it may be routed to a queue that is only meant to handle messages with a specific header.

**To Reproduce**

1. Set up a RabbitMQ Headers Exchange with multiple queues bound to it.
2. Configure one queue to match messages with a specific header value (e.g., `x-priority = 1`).
3. Configure another queue to match messages with a different header value (e.g., `x-priority = 2`).
4. Send a message without any headers.
5. Observe that the message is routed to a queue that should only handle messages with specific headers.

**Expected behavior**

Messages without headers should not be routed to queues that are bound with header matching conditions. Instead, they should be handled according to default or fallback routing rules if such rules are defined.

**Sample**

### Bean creation
```java
    @Bean
    public Binding headersBinding(Queue highPriorityQueue, HeadersExchange headersExchange) {
        return BindingBuilder.bind(highPriorityQueue).to(headersExchange).where("x-priority").exists();
    }

```
### Producer
```java

 MessageProperties noHeaders = MessagePropertiesBuilder.newInstance().build();
            Message message1 = new Message(message.getBytes(StandardCharsets.UTF_8), noHeaders);
            rabbitTemplate.convertAndSend(HEADERS_LOGS,  "", message1 );
```
### Consumer
```java
    @RabbitListener(queues = RabbitMQAdvancedConfig.HIGH_PRIORITY_QUEUE)
    public void receiveMessageHP(String message) throws IOException {
        log.info("Message received {}",message);
    }
```

**Comment by artembilan** [comment]
I think that is how Headers Exchange works in AMQP and it has nothing to do with Spring.
See more info in docs: https://www.rabbitmq.com/tutorials/amqp-concepts#exchange-headers

> For "any" and "all", headers beginning with the string x- will not be used to evaluate matches. Setting "x-match" to "any-with-x" or "all-with-x" will also use headers beginning with the string x- to evaluate matches.

And also this StackOverflow question: https://stackoverflow.com/questions/75879463/rabbitmq-headers-exchange-routing-to-all-queues-instead-of-matching-headers.

Closing as `Works as Designed`
