### ISSUE TITLE
Question: what is the ETA of the 3.2.0 release?

### ISSUE THREAD

**Issue by n10v** [spring-projects/spring-amqp#2793]
Hello team!
Thanks a lot for your great work on this plugin <3
I'm having a question: what is the ETA of the 3.2.0 release? It contains really important bugfix (#2572).

Regards,
Albert

**Comment by artembilan** [comment]
This November.
Unfortunately we cannot back-port it since it is a bit of breaking change in the behavior.
Please, use Discussions next time for this kind of questions.
