### ISSUE TITLE
There is an EOL notification for Spring AMQP 3.1.x series for November

### ISSUE THREAD

**Issue by Harshdeep86** [spring-projects/spring-amqp#2807]
There is an EOL notification for Spring AMQP 3.1.x series for November. Is there any date when 3.2.x series will be released

**Comment by artembilan** [comment]
Same November: https://calendar.spring.io/.
See the milestones we have scheduled: https://github.com/spring-projects/spring-amqp/milestones.
Also, the Support page should give some clues:   https://spring.io/projects/spring-amqp#support.
The idea that previous version goes EOL exactly same day when new version goes GA.

Please, consider to ask similar questions in Discussions section next time.
Closing as `Invalid`.
