### ISSUE TITLE
Can we get a rabbit stream consumer instance?

### ISSUE THREAD

**Issue by laststem** [spring-projects/spring-amqp#2860]
**Expected Behavior**

I need a way to get the consumer instance created in the StreamListenerContainer.

**Current Behavior**

Unable to retrieve consumer instance created in StreamListenerContainer.

**Context**

[docs](https://rabbitmq.github.io/rabbitmq-stream-java-client/stable/htmlsingle/#consumer-manual-offset-tracking) says
```
The snippet above uses MessageHandler.Context#storeOffset() to store at the offset of the current message, but it is possible to store anywhere in the stream with MessageHandler.Context#consumer()#store(long) or simply Consumer#store(long).
```

A Consumer reference may be required for Manual offset tracking by `Consumer` instance.

How about creating a getter for consumers in StreamListenerContainer?

For example
```java
public class StreamListenerContainer {
  ...
  private final Collection<Consumer> consumers = new ArrayList<>();
  ...
  public Collection<Consumer> getConsumers() { return consumers; }
}
```

or How about providing a callback for Consumer creation in StreamRabbitListenerContainerFactory?

For example
```java
public interface ConsumerCreationCallback {
  public void onCreate(Consumer consumer);
}

public class StreamRabbitListenerContainerFactory {
  private ConsumerCreationCallback creationCallback;

  public void setConsumerCreationCallback(ConsumerCreationCallback creationCallback) { this.creationCallback = creationCallback; }

  public StreamListenerContainer createListenerContainer(RabbitListenerEndpoint endpoint) { 
    // add creation callback
   ...
  }
}

public class StreamListenerContainer {
  private ConsumerCreationCallback creationCallback;

  public void start() {
     ...
     Consumer consumer = this.builder.build();
     this.consumers.add(consumer);
     creationCallback.onCreate(consumer);
  }
}
```

**Comment by artembilan** [comment]
I wonder why this approach does not work for you: https://docs.spring.io/spring-amqp/reference/stream.html

```
@RabbitListener(id = "test", queues = "test.stream.queue2", containerFactory = "nativeFactory")
void nativeMsg(Message in, Context context) {
    ...
    context.consumer();
}
```

**Comment by laststem** [comment]
My application has a async flow, so i can't call `context.store()` or `context.consumer().store(offset)`.
```kotlin
private val queue = ConcurrentLinkedQueue<Any>()
fun listen(message: Message, ctx: MessageHandler.Context) {
    queue.add(message)
    // can't store offset because message cannot be completed because it is processed asynchronously.
    // ctx.store()
    // ctx.consumer.store(ctx.offset())
}
```

I can also temporarily pass context.consumer() to other classes and use it, but need to be careful because context.consumer() can change over time (by connection recreation).

If Spring AMQP provides a way to get the consumer, I don't have to go through the hassle of binding context.consumer() to another class periodically.

**Comment by laststem** [comment]
It seems that once a consumer instance is created, it is not recreated if there is a connection problem, but is restored within the stream library.
