### ISSUE TITLE
Can we make to use CAS instead of ReentrantLock in RabbitStreamTemplate.createOrGetProducer ?

### ISSUE THREAD

**Issue by laststem** [spring-projects/spring-amqp#2861]
**Expected Behavior**

Use CAS in createOrGetProducer.

**Current Behavior**

Always createOrGetProducer makes lock and unlock.

**Context**

There was a slight delay due to the lock in a high traffic environment.

**Comment by artembilan** [comment]
What is `CAS` please, and what exactly your idea how to fix?
Feel free to open pull request on the matter !
Thanks

**Comment by artembilan** [comment]
Fixed via: https://github.com/spring-projects/spring-amqp/commit/33da2a6158a49ff62a37cbebc5ac1e8ac5e73839
