### ISSUE TITLE
Programmatic Endpoint Registration setId

### ISSUE THREAD

**Issue by mmesar** [spring-projects/spring-amqp#2895]
I believe that documentation 
https://docs.spring.io/spring-amqp/reference/amqp/receiving-messages/async-annotation-driven/registration.html

is missing setId method call on SimpleRabbitListenerEndpoint object to work.

**Comment by artembilan** [comment]
Sure!
Feel free to provide that documentation improvement: https://github.com/spring-projects/spring-amqp/blob/main/CONTRIBUTING.adoc.

Although the logic is like this:
```
public void registerEndpoint(RabbitListenerEndpoint endpoint,
			@Nullable RabbitListenerContainerFactory<?> factory) {
		Assert.notNull(endpoint, "Endpoint must be set");
		Assert.hasText(endpoint.getId(), "Endpoint id must be set");
```
So, if something is missed, it will be reported back to the caller.
There are might be much more nuances which we don't mention in the docs, but they make it obvious when you run your application.
We definitely cannot cover all the possible use-cases in the reference doc.
