### ISSUE TITLE
delivery tag in the observations leading to too many timers generated -> leading to memory leak

### ISSUE THREAD

**Issue by jensbaitingerbosch** [spring-projects/spring-amqp#2914]
**In what version(s) of Spring AMQP are you seeing this issue?**

3.2.0

**Describe the bug**

When upgrading our app to the latest spring version we discovered that the new verison produces way more metrics then before. While the old version produced about 20k timelines in prometheus, the new one generates 200k per instance. The main problematic metrics are: 

- spring_rabbit_listener_seconds_bucket
- spring_rabbit_listener_active_seconds_bucket

which have not been in the older version 3.1.x

**To Reproduce**

Create an application, with message listeners, activate exporting of histogram buckets (e.g. by adding a meterFilter to the MeterRegistry)

Have Observations active (e.g. to trace the message processing even when they are processed async.)

```
public class MeterRegistryConfigurator implements BeanPostProcessor {

  @Override
  public Object postProcessAfterInitialization(@NotNull Object bean, @NotNull String beanName) {
    if (bean instanceof MeterRegistry meterRegistry) {

      var config = meterRegistry.config();
      config.meterFilter(new MeterFilter() {
        @Override
        public DistributionStatisticConfig configure(
            @NotNull Meter.Id id,
            @NotNull DistributionStatisticConfig config
        ) {
          return config.merge(DistributionStatisticConfig.builder()
              .percentilesHistogram(true)
              .build());
        }
      });
    }
    return bean;
  }
}
```

**Expected behavior**
A relatively small amount of timers are exported (max one per queue/error/listener(instace))

**Actual behaviour**

a new timer is created per delivery tag (which leads to an enormous amount of timers. 

error="none", messaging_destination_name=xxx.queue", messaging_rabbitmq_message_delivery_tag="1", spring_rabbit_listener_id="org.springframework.amqp.rabbit.RabbitListenerEndpointContainer#2"}

**Reference**

The [rabbit documentation](https://www.rabbitmq.com/docs/confirms) refers the delivery tag as 
> monotonically growing positive integers 

Therefore it is not suitable for a 'low cardinality key value'.

** Workaround **

One part of the issue can be solved by an observation filter (e.g. by post processing the observation registry)

```
    @Bean
    open fun observationFilerPostProcessor() =
        object : BeanPostProcessor {
            override fun postProcessAfterInitialization(
                bean: Any,
                beanName: String,
            ): Any {
                if (bean is ObservationRegistry) {
                    bean.observationConfig().observationFilter { context ->
                        if (context.name == "spring.rabbit.listener") {
                            // delivery tag is a growing integer value, therefore not really suitable for metric tags
                            context.removeLowCardinalityKeyValue("messaging.rabbitmq.message.delivery_tag")
                        }
                        context
                    }
                }
                return bean
            }
        }
 ```
 
It will still create long task timers with all the keyValues. This can be solved e.g. by adding this to your applications.yml (when you use spring)

 ```
 management:
    observations:
        long-task-timer:
            enabled: false
            ```

**Comment by artembilan** [comment]
Yes, it feels like a bug that this `messaging.rabbitmq.message.delivery_tag` has to be a high cardinality. If that is a case, please, consider to contribute the fix. I’m on vacation until next week.

**Comment by jensbaitingerbosch** [comment]
Update: I removed the workaround, as it does not work. The issue is, that the Filter is only applied on stopping the Observation. Though the `DefaultMeterObservationHandler` creates a `Timer.Sample` with all the Tags on starting the application.

**Comment by artembilan** [comment]
No problem, @jensbaitingerbosch !
We have a couple weeks before next bug fixes release: https://github.com/spring-projects/spring-amqp/milestone/242

**Comment by bpfoster** [comment]
For an additional point of reference, I think we are having the same issue after upgrading to Spring Boot 3.4.  Services saw a large jump in heap usage, many seeing OutOfMemoryExceptions.  Prometheus then began eating memory in multiples of what it had been using.

Until this is addressed, I am working around it by configuring a `RabbitListenerObservationConvention` that is the same as the `DefaultRabbitListenerObservationConvention` in [spring-rabbit 3.1.8](https://github.com/spring-projects/spring-amqp/blob/v3.1.8/spring-rabbit-stream/src/main/java/org/springframework/rabbit/stream/micrometer/RabbitStreamMessageReceiverContext.java#L81-L100).

**Comment by artembilan** [comment]
Sounds good, @bpfoster !

Thank you for sharing your experience!

Our bug-fixes plan is next Monday - December 16th.
So, not too far when we have the fix out-of-the-box.

**Comment by artembilan** [comment]
We release plan next Monday and since no one cracks this, I'm going to take care about it myself.
Thank you for the report anyway!
This is enough for a contribution as a thing.
