### ISSUE TITLE
Incompatibility between RabbitProperties from Spring Boot 3.4.0 and CachingConnectionFactory

### ISSUE THREAD

**Issue by oneiros-de** [spring-projects/spring-amqp#2917]
**In what version(s) of Spring AMQP are you seeing this issue?**

3.2.0

**Describe the bug**

In Spring Boot 3.4.0 [org.springframework.boot.autoconfigure.amqp.RabbitProperties#getAddresses()](https://docs.spring.io/spring-boot/api/java/org/springframework/boot/autoconfigure/amqp/RabbitProperties.html#getAddresses()) returns a `List<String>` while it previously returned a `String`.

This makes it incompatible with [AbstractConnectionFactory.setAddresses](https://docs.spring.io/spring-amqp/docs/3.2.0/api/org/springframework/amqp/rabbit/connection/AbstractConnectionFactory.html#setAddresses(java.lang.String)) which accepts a String.

With Spring Boot 3.3x and AMQP 3.2.0 one can write `cachingConnectionFactory.setAddresses(rabbitProperties.getAddresses());` which is impossible with 3.4.0

**Expected behavior**

Either make `setAddresses` compatible with the new RabbitProperties or add a new method that is.

**Comment by artembilan** [comment]
Not sure why would one use Spring Boot, but not its auto-configuration.
I mean that `CachingConnectionFactory` bean is really created by the `RabbitAutoConfiguration`, so no need to deal with your own custom beans.

As a workaround I see that it is easy to adjust your code:
```
cachingConnectionFactory.setAddresses(rabbitProperties.getAddresses().stream().collect(Collectors.joining(",")));
```

Either way, I'll introduce `AbstractConnectionFactory.setAddresses(List<String> addresses)` shortly.
