### ISSUE TITLE
Expose Network Recovery Interval and Automatic Connection Recovery in RabbitConnectionFactoryBean

### ISSUE THREAD

**Issue by coreyjv** [spring-projects/spring-amqp#379]
I opened an issue in Spring Boot to expose `networkRecoveryInterval` and `automaticRecovery` as part of the `RabbitAutoConfiguration.` @philwebb agreed that it would be a nice capability to have. However, before this can be done those properties need to be exposed on the `RabbitConnectionFactoryBean`. 

Can I submit a PR to expose these properties on the `RabbitConnectionFactoryBean`?

Issue:

https://github.com/spring-projects/spring-boot/issues/5031

**Comment by garyrussell** [comment]
Please see my comment on https://github.com/spring-projects/spring-boot/issues/5031

**Comment by garyrussell** [comment]
See https://github.com/spring-projects/spring-boot/issues/5031
