### ISSUE TITLE
AMQP Channel problem

### ISSUE THREAD

**Issue by pengliang530** [spring-projects/spring-amqp#394]
when using spring amqp in mutiple threads env, it create only one Channel, but Channel instances must not be shared between threads.

see https://www.rabbitmq.com/releases/rabbitmq-java-client/current-javadoc/com/rabbitmq/client/Channel.html please

**Comment by garyrussell** [comment]
>it create only one Channel,

That is not correct; each consumer (or publisher) gets its own channel; channels are cached however (default 1 only), so you will see consecutive publishing on different threads use the same channel.

If you are seeing concurrent use of the same channel, please explain the circumstances.

**Comment by pengliang530** [comment]
seems works as expected, thanks very much.
