### ISSUE TITLE
quick question...hopefully

### ISSUE THREAD

**Issue by born2snipe** [spring-projects/spring-amqp#420]
Maybe the method is poorly named or I maybe I don't fully understand the domain but....this logic looked suspicious to me:

https://github.com/spring-projects/spring-amqp/blob/master/spring-amqp/src/main/java/org/springframework/amqp/core/AcknowledgeMode.java#L32

Shouldn't the comparison be against AUTO instead of NONE?

**Comment by garyrussell** [comment]
It's a bit unfortunate, but correct.

In the RabbitMQ world, "auto ack" means no acks - i.e. the broker marks the message as delivered as soon as it is sent to the client.

In the Spring world (specifically JMS) `AUTO` ack means the listener container takes care of the ack when the listener returns normally (and nacks for exceptions).

So, when Spring AMQP was created, it was aligned more with spring-jms and `AUTO` means the container will send the acks, `MANUAL` means the user is responsible for acking and `NONE` means no acks (i.e. auto Ack in RabbitMQ-speak).

(This is my understanding, I wasn't here at the time).

I will, however, take this opportunity to add some javadocs there.
