### ISSUE TITLE
RabbitConnectionFactory should support JKS for SSL Keystore

### ISSUE THREAD

**Issue by habelson** [spring-projects/spring-amqp#436]
this is more of a feature request than a bug... 

Currently, "PKCS12" is the only supported type for the keystore, even though JKS is used for the truststore. It would be nice if the type was configurable, as JKS is a common format to use for Java Applications and it is somewhat inconvenient to have to convert to P12 just to use a secure rabbit connection.

I know I can easily override the class to implement this myself, I just thought it would be convenient if this was supported natively by a property similar to how keystore path and password are treated.

**Comment by artembilan** [comment]
Eh... Looks like it is just an omission.

I think we just have to provide a couple of setters (`setKey(Trust)StoreType()`) to have that configurable.

Feel free to [contribute](https://github.com/spring-projects/spring-amqp/wiki) that via Pull Request!

Meanwhile I think we don't have choice unless leave it as `PKCS12` by default for the current `1.6.2` and and change it to `JKS` in `2.0` already.

See https://jira.spring.io/browse/AMQP-626 for tracking.

**Comment by garyrussell** [comment]
As to why it's that way, we simply copied the Java example on the [rabbitmq page](https://www.rabbitmq.com/ssl.html).

**Comment by roasher** [comment]
Ok, we have setter now, but how can we use it?
I can't just define custom RabbitConnectionFactoryBean - in RabbitAutoConfiguration class there is @ConditionalOnMissingBean(ConnectionFactory.class) and RabbitConnectionFactoryBean is created through "new" - so it is mean that my bean won't be used unless I will create whole custom CachingConnectionFactory which I don't need. Why this is not in ssl properties like others?

**Comment by artembilan** [comment]
@roasher ,

The `RabbitAutoConfiguration` is in the [Spring Boot](https://github.com/spring-projects/spring-boot) project. Consider to request such an improvement there, please.

Right, you don't have choice unless build the whole `RabbitConnectionFactoryBean`. Although you still can reuse that `RabbitProperties`.
