### ISSUE TITLE
SHOULD raise exception when durable, exclusive queue (spring-amqp/spring-rabbit)

### ISSUE THREAD

**Issue by SehoNoh** [spring-projects/spring-amqp#510]
Hello there,

Thanks for spring-amqp/spring-rabbit for to easy using RabbitMQ, but I got a question.

The question is,
Why didn't raise a Exception when declare a queue with `durable: true` and `exclusive: true`.

in [RabbitMQ AMQP-0-9-1-ERRATA](https://www.rabbitmq.com/amqp-0-9-1-errata.html)

> 30 durable vs exclusive
>
> The spec does not define what happens if a client tries to declare a queue which is both durable and exclusive. RabbitMQ will treat a request to declare such a queue as a request for an exclusive transient queue.

According to above paragraph 
Although it will request with `durable: true` and `exclusive: true`, RabbitMQ will change to non-durable exclusive queue.

```
Queue queueForTest1 = new Queue("QUEUE_NAME", true, true, false);
Queue queueForTest2 = new Queue("QUEUE_NAME", true, false, false);
rabbitAdmin.declareQueue(queueForTest1);
rabbitAdmin.declareQueue(queueForTest2);
```

```
Channel shutdown: channel error; protocol method: #method<channel.close>(reply-code=406, reply-text=PRECONDITION_FAILED - inequivalent arg 'durable' for queue 'QUEUE_NAME' in vhost '/': received 'true' but current is 'false', class-id=50, method-id=10)
```

and I certainly checked this situation via above my test code. 

So I suggest.
It'd better that will raise a exception by spring-amqp/spring-rabbit, to prevent this situation which is declaring with `durable: true` and `exclusive: true`.

**Comment by artembilan** [comment]
Well, actually you have two different declarations for the same queue.
So, even if we throw `IllegalArgumentException`  and you'd fix inconsistency, your second `false` for the `exclusive` will lead to similar `PRECONDITION_FAILED`.

```
Queue queueForTest2 = new Queue(queueName, false, true, false);
```
makes your test to pass.

To be consistent with the RabbitMQ spec, I don't see reason to break that rule and throw unexpected  `IllegalArgumentException` , where all other clients just reconfigure request silently.

**Comment by SehoNoh** [comment]
yeah, I know that the second queue would better to replace with
```
Queue queueForTest2 = new Queue(queueName, false, true, false);
```
to pass the test or using like that
And you mean that we don't need to fix up the programmer's logical (I think it's logical) mistake?

Then, What about that write a log for caution to programmers at this situation?

**Comment by artembilan** [comment]
> What about that write a log for caution to programmers at this situation?

Well, I'd say that it is better to forward such a request to the RabbitMQ client directly.

Since `com.rabbitmq.client.Channel.queueDeclare()` doesn't throw any warnings, I don't see reason to overhead that on the Spring AMQP level.

When `amqp-client` will react somehow to that condition, Spring AMQP will propagate it transparently.

**Comment by SehoNoh** [comment]
I see, I exactly understand what you saying.
Thanks for your lecture, it helps me alot :)
