### ISSUE TITLE
RabbitMQ Java Client 4.0 is released

### ISSUE THREAD

**Issue by Hronom** [spring-projects/spring-amqp#512]
http://www.rabbitmq.com/blog/2016/11/24/rabbitmq-java-client-4-0-is-released/

Looks like a major release that contain useful features, any plan to upgrade?

**Comment by garyrussell** [comment]
We are about to release the first milestone of Spring AMQP 2.0 and it is based on the 4.0.0 client.

**Comment by garyrussell** [comment]
We will also be releasing 1.7.0 with Spring Boot 1.5 and it, too, will be compatible with 4.0.0.
