### ISSUE TITLE
ListenerExecutionFailedException.getFailedMessage() is always null

### ISSUE THREAD

**Issue by OrangeDog** [spring-projects/spring-amqp#535]
It is my understanding that `ErrorHandler` and `FatalExceptionStrategy` are supposed to have access to the `Message` via the `ListenerExecutionFailedException`.

However, nothing ever appears to fill it in.
I would expect `MessagingMessageListenerAdapter.invokeHandler` to be passing it in the exception constructors.

**Comment by garyrussell** [comment]
Yes; it's a bug; thanks for reporting; I will open a JIRA issue.

**Comment by garyrussell** [comment]
Yes; it's a bug; thanks for reporting; we will open a JIRA issue.

The oldwe POJO adapter populates it, but not the `@RabbitListener` adapter.

**Comment by artembilan** [comment]
See https://jira.spring.io/browse/AMQP-692

**Comment by OrangeDog** [comment]
Is there a release plan for 1.6.7?

**Comment by garyrussell** [comment]
It's not currently scheduled, but we can release it at any time if you need this fix urgently.

**Comment by garyrussell** [comment]
The 1.7 GA is scheduled for Thursday next week; my preference would be to release 1.6.7 at the same time, if that would work for you.

**Comment by OrangeDog** [comment]
Yes, the 19th should be fine.
