### ISSUE TITLE
The spring boot context identify the AsyncRabbitTemplate bean as RabbitTemplate bean

### ISSUE THREAD

**Issue by yosaku01** [spring-projects/spring-amqp#537]
I have used spring-boot-starter-amqp 1.4.2 RELEASE, the imported spring-amqp and spring-rabbit library is 1.6.5 RELEASE.

But when I create a bean having type org.springframework.amqp.rabbit.AsyncRabbitTemplate
@Bean(name="rabbitTemplate")
public AsyncRabbitTemplate getRabbitTemplate()
{
    	AsyncRabbitTemplate rabbitTemplate = 
    			new AsyncRabbitTemplate(getConnectionFactory(), 
    				        "sendExchange", 
    					"sendMessage",
    					"replyQueue");
    	rabbitTemplate.setReceiveTimeout(60000);
    	rabbitTemplate.setAutoStartup(true);
    	return rabbitTemplate;
}
The connectionFactory I used is a CachingConnectionFactory bean.

But when I get the "rabbitTemplate" bean from application context
AsyncRabbitTemplate rabbitTemplate =
                (AsyncRabbitTemplate) ApplicationContextUtil.getBean("rabbitTemplate");
I found the retrieved bean is the bean having org.springframework.amqp.rabbit.RabbitTemplate.
There is no inheritance relationship between RabbitTemplate and AsyncRabbitTemplate class, why the
spring container identify the created AsyncRabbitTemplate bean as RabbitTemplate bean?

**Comment by panchenko** [comment]
Looks like RabbitTemplate is also added to the context and "rabbitTemplate" would be a default name for it.
I would suggest using unique bean names and the `getBean(Class<T> requiredType)` method.

**Comment by yosaku01** [comment]
When I getBean by AsyncRabbitTemplate type and keep the name "rabbitTemplate", the following exception is thrown:
java.util.concurrent.ExecutionException: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.amqp.rabbit.AsyncRabbitTemplate' available
My source code is
AsyncRabbitTemplate rabbitTemplate =
                (AsyncRabbitTemplate) ApplicationContextUtil.getBean(AsyncRabbitTemplate.class);
But when I modify the bean name to "asyncRabbitTemplate", this exception is not thrown.

**Comment by yosaku01** [comment]
I have found the reason. In spring boot, the RabbitAutoConfiguration is enabled by default. So a rabbitTemplate bean is created by default. Though I redefined a rabbitTemplate bean, it is still overrided by 
the default RabbitTemplate bean.
But when I exclude RabbitAutoConfiguration in configuration, the above problems do not happen again.

**Comment by artembilan** [comment]
@panchenko ,

thank you for the assistance on the issue!

@yosaku01 ,

Your problem that by default, when several beans with the same name are configured, the last one wins.
In your case that is `RabbitTemplate` `@Bean` from the `RabbitAutoConfiguration`.
Therefore your one is overridden.
Yes, only a solution to declare your own bean with unique name, but still get a gain from the `RabbitAutoConfiguration`, e.g. `rabbitConnectionFactory` bean and so on.
