### ISSUE TITLE
MessagePostProcessor doesn't expose CorrelationData

### ISSUE THREAD

**Issue by OrangeDog** [spring-projects/spring-amqp#543]
The Javadoc for `CorrelationData.setId` says:

> One use case, however, is when it needs to be set in a MessagePostProcessor after a CorrelationData with a 'null' correlation id has been passed into a RabbitTemplate.

I have exactly that use case. However, there doesn't appear to be any way for a `MessagePostProcessor` to actually do this. Presumably there was supposed to be some kind of `public CorrelationData postProcessCorrelationData(CorrelationData data, Message message)` API?

**Comment by artembilan** [comment]
That `CorrelationData.setId()` is intended for internal use.
And Framework has only one place for that case - `AsyncRabbitTemplate.CorrelationMessagePostProcessor`

What is your use-case, please?

**Comment by garyrussell** [comment]
Interesting observation - I added that javadoc recently when I implemented the `AsyncRabbitTemplate` - as you can see, the MPP is stateful and gets a reference to the correlationId (each send gets its own MPP)...

```java
private final class CorrelationMessagePostProcessor<C> implements MessagePostProcessor {

	private final MessagePostProcessor userPostProcessor;

	private final CorrelationData correlationData;

	private final ParameterizedTypeReference<C> returnType;

	private volatile RabbitConverterFuture<C> future;

	CorrelationMessagePostProcessor(MessagePostProcessor userPostProcessor,
			CorrelationData correlationData, ParameterizedTypeReference<C> returnType) {
		this.userPostProcessor = userPostProcessor;
		this.correlationData = correlationData;
		this.returnType = returnType;
	}

	@Override
	public Message postProcessMessage(Message message) throws AmqpException {
		Message messageToSend = message;
		if (this.userPostProcessor != null) {
			messageToSend = this.userPostProcessor.postProcessMessage(message);
		}
		String correlationId = getOrSetCorrelationIdAndSetReplyTo(messageToSend);
		this.future = new RabbitConverterFuture<C>(correlationId, message);
		if (this.correlationData != null && this.correlationData.getId() == null) {
			this.correlationData.setId(correlationId);
			this.future.setConfirm(new SettableListenableFuture<>());
		}
		this.future.setReturnType(this.returnType);
		AsyncRabbitTemplate.this.pending.put(correlationId, this.future);
		return messageToSend;
	}

	private RabbitConverterFuture<C> getFuture() {
		return this.future;
	}

}
```

**Comment by OrangeDog** [comment]
Specifically, to generate `CorrelationData` from the `Message` in a uniform way, without having to add extra calls for every `send` call. I'm only using it for publisher confirms, not replies, so `AsyncRabbitTemplate` doesn't seem to be the right solution.

**Comment by artembilan** [comment]
It is done only for case, BTW:
```
CorrelationData correlationData = null;
if (this.enableConfirms) {
	correlationData = new CorrelationData(null);
}
```

**Comment by garyrussell** [comment]
I like the idea of a `CorrelationDataAwareMPP` - we could avoid having to create an MPP for each request.

**Comment by garyrussell** [comment]
https://jira.spring.io/browse/AMQP-697

**Comment by artembilan** [comment]
Right, now you have to do that manually in advance before calling:
```
public void convertAndSend(String exchange, String routingKey, final Object message,
			final MessagePostProcessor messagePostProcessor, CorrelationData correlationData) throws AmqpException {
```
or just 
```
convertAndSend(String routingKey, final Object object, CorrelationData correlationData)
```
At least that how it has been designed to use...

**Comment by OrangeDog** [comment]
@artembilan there's more detail in my explanation now, I want to make the correlation data after the message converter.
@garyrussell any chance of that making it for 1.6.7?

**Comment by garyrussell** [comment]
Not if we use a `default` method on MPP for the implementation (requires Java 8).

If we go with a sub-interface, we could backport to 1.6.x.

**Comment by OrangeDog** [comment]
Aside: in my use case, does anything bad happen if the correlation data id is `null`?

**Comment by garyrussell** [comment]
Nothing bad, as long as you handle getting null back in the `ConfirmCallback`.

**Comment by garyrussell** [comment]
Which, of course, is not very useful since you can't correlate which message the confirm is for 😄

**Comment by OrangeDog** [comment]
> you can't correlate which message the confirm is for
Well I can when the rest of the correlation data is the entire message.

**Comment by garyrussell** [comment]
Oh, sorry, I thought you meant the `CorrelationData` itself was null 😄

**Comment by garyrussell** [comment]
@OrangeDog This will be in the 1.6.7 release; the [master PR](https://github.com/spring-projects/spring-amqp/pull/544) is ready for review and I'll back port it after review/merge.

**Comment by OrangeDog** [comment]
Sorry, I should have had a look at the change sooner.
This still doesn't let you add a `Correlation` if one doesn't exist.

**Comment by garyrussell** [comment]
We can't really do that without adding a whole new interface and callback. You will need to add an empty correlation container to the send and update it in the MPP.

**Comment by OrangeDog** [comment]
> adding a whole new interface and callback

That is what I was asking for.

> some kind of `public CorrelationData postProcessCorrelationData(CorrelationData data, Message message)` API?

**Comment by garyrussell** [comment]
We could have done that (and I now see it in your original post where you "presumed" that was the intent of the javadoc, but the javadoc explicitly referenced `MessagePostProcessor` not some new interface.

To be honest, the original intent was something like this

```java 
final CorrelationData foo = ...
template.send(..., ..., m -> {
    // update message
    // foo.setSomething(...)
});
```

We're planning on releasing today so I don't think we can change direction at this point.

What is the objection to adding a container object before the send?

**Comment by OrangeDog** [comment]
> Specifically, to generate CorrelationData from the Message in a uniform way, without having to add extra calls for every send call.

There are lots of send calls in my codebase, you have to use the full `RabbitTemplate` interface and 4-ary method, and I'd rather not have to change every single one.

**Comment by garyrussell** [comment]
OK; you convinced me 😄 - we'll try to get it out today, but it may cause the release to be pushed to tomorrow.

**Comment by garyrussell** [comment]
https://github.com/spring-projects/spring-amqp/pull/548
