### ISSUE TITLE
RabbitMq management Rest Api connection issue with client using non public certificates

### ISSUE THREAD

**Issue by jmrt47** [spring-projects/spring-amqp#551]
Creating a RabbitManagementTemplate instance there is no way to add trusted certificates or to change the http client. The underlying class Client creates a rest template instance without any option to configure trusted certificates. The HttpClientBuilder used to create the HttpComponentsClientHttpRequestFactory used by the RestTemplate doesn't call useSystemProperties() method so default properties like javax.net.ssl.trustStore doesn't work too.

Is there a way I messed by now I couldn't see a way to trust the server certificate with the RabbitManagementTemplate.

**Comment by garyrussell** [comment]
Since the `RabbitManagementTemplate` is a lightweight wrapper around the `Client`, I suggest you raise this issue against [hop](https://github.com/rabbitmq/hop).

**Comment by artembilan** [comment]
M-m-m. I wonder why ctor like below isn't appropriate for you?
```
/**
   * Construct an instance with the provided url and credentials.
   * @param url the url e.g. "http://localhost:15672/api/".
   * @param username the user name.
   * @param password the password
   * @param sslContext ssl context for http client
   * @throws MalformedURLException for a badly formed URL.
   * @throws URISyntaxException for a badly formed URL.
   */
  public Client(URL url, String username, String password, SSLContext sslContext) throws MalformedURLException, URISyntaxException {
```

**Comment by jmrt47** [comment]
Thanks for your quick response, I used the latest version (1.4.3.RELEASE) of spring-boot-starter-amqp which includes spring-rabbit in version 1.6.6.RELEASE and this includes the http-client in version 1.0.0.RELEASE. This version of http-client doesn't has no constructor like mentioned by @artembilan.
Excluding http-client from spring-boot-start-amqp and add latest version manually solved the issue for me.
