### ISSUE TITLE
NoSuchMethodError: Assert.notNull(Object)

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-amqp#554]
Since [SPR-15196](https://jira.spring.io/browse/SPR-15196), `Assert.notNull(Object)` and other single arg methods are gone from Spring Framework 5.x, replaced with `String` or `Supplier<String>` as second arguments.

This method is used in `ValueExpression`.
This is unfortunately breaking the Spring Boot build. See spring-projects/spring-boot#8140

**Comment by artembilan** [comment]
See https://jira.spring.io/browse/AMQP-705
