### ISSUE TITLE
Wrong documentation for delayed message

### ISSUE THREAD

**Issue by fjmpaez911** [spring-projects/spring-amqp#580]
In the  [chapter](http://docs.spring.io/spring-amqp/reference/html/_reference.html#delayed-message-exchange)  of Reference Manual said:

properties.setXDelay(15000);

when this method doesn't exists.

The correct method is (setDelay):

/**
* Set the x-delay header.
* @param delay the delay.
* @since 1.6
*/
public void setDelay(Integer delay) {
if (delay == null || delay < 0) {
this.headers.remove(X_DELAY);
}
else {
this.headers.put(X_DELAY, delay);
}
}

**Comment by artembilan** [comment]
@fjmpaez911 ,

Please, consider contribution with the fix on the matter: https://github.com/spring-projects/spring-amqp/blob/master/CONTRIBUTING.adoc

**Comment by artembilan** [comment]
Fixed via https://github.com/spring-projects/spring-amqp/commit/abc4e5a66ba35d3f0881fc2d21fd29ef5b591e3d in `master`.
