### ISSUE TITLE
Extending Jackson2JsonMessageConverter

### ISSUE THREAD

**Issue by calvernaz** [spring-projects/spring-amqp#589]
I want to register a new module into the object mapper present in _Jackson2JsonMessageConverter_, but the documentation suggests two ways of doing it: 

- One is to configure the ObjectMapper and inject into _Jackson2JsonMessageConverter_. The documentation in the _setJsonObjectMapper_ suggest an alternative which is to extend the class and override the method _initializeJsonObjectMapper_

- The issue with extending the _Jackson2JsonMessageConverter_ is the lack of access to the ObjectMapper in the parent class, ending up like this:
```
public class JacksonMessageConverter extends Jackson2JsonMessageConverter {
    @Override
    protected void initializeJsonObjectMapper() {
        ObjectMapper objectMapper = new ObjectMapper();
        objectMapper.registerModule(new GuavaModule());
        objectMapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
        this.setJsonObjectMapper(objectMapper);
    }
}
```
So we still have to inject the ObjectMapper, besides overriding the method, it doesn't really look like an alternative.

Changing the ObjectMapper visibility to protected (or a getter) would give us the alternative.

**Comment by garyrussell** [comment]
Yes, it looks like an oversight; there should either be a getter or the mapper should be passed in as an argument to the method.
