### ISSUE TITLE
Cannot set another host name BrokerRunning 

### ISSUE THREAD

**Issue by SirWayne** [spring-projects/spring-amqp#592]
It's hard to set another hostname for the BrokerRunning rule.
For the connection factory it's possible to use a static block.

```
    @ClassRule
    public static BrokerRunning brokerRunning = BrokerRunning.isRunning();
    static {
        brokerRunning.setHostName("abc");
    }
```

but the host name for the management client is hardcoded

`
Client client = new Client("http://localhost:15672/api/", "guest", "guest");
`

**Comment by garyrussell** [comment]
Thanks for pointing this out - I raised it as a bug [AMQP-728](https://jira.spring.io/browse/AMQP-728).
