### ISSUE TITLE
Delivery mode lost when using RepublishMessageRecoverer

### ISSUE THREAD

**Issue by mdemarey** [spring-projects/spring-amqp#632]
Hi,

When using `RepublishMessageRecoverer`, delivery mode of the new message seems to be `NON_PERSISTENT` by default. When RabbitMQ broker restart, all messages get lost.
I've tried to override the `RepublishMessageRecoverer` by adding `message.getMessageProperties().setDeliveryMode(MessageDeliveryMode.PERSISTENT)`, and messages are now persistent.

Is it possible to add an option to choose delivery mode of the republished messages ?

Thanks

**Comment by artembilan** [comment]
That is there by default in the `MessageProperties`:
```
public static final MessageDeliveryMode DEFAULT_DELIVERY_MODE = MessageDeliveryMode.PERSISTENT;
...
private volatile MessageDeliveryMode deliveryMode = DEFAULT_DELIVERY_MODE;
```

Maybe your original message has arrive with the `NON_PERSISTENT` ?

**Comment by artembilan** [comment]
That exactly the reason the method exist for:
```
/**
	 * Subclasses can override this method to add more headers to the republished message.
	 * @param message The failed message.
	 * @param cause The cause.
	 * @return A {@link Map} of additional headers to add.
	 */
	protected Map<? extends String, ? extends Object> additionalHeaders(Message message, Throwable cause) {
		return null;
	}
```
So, you extend `RepublishMessageRecoverer` and override that method to specify any desired properties and/or headers.

**Comment by mdemarey** [comment]
Original message arrive with PERSISTENT, when debugging in the recover method, I can see the properties "receivedDeliveryMode=PERSISTENT", but "deliveryMode=null" so the republished message isn't persistent.

I tried to use additionalHeaders but it adds a header instead of a properties, message still arrive non persistent

**Comment by artembilan** [comment]
OK. I see what you mean. When we receive message in the container, when we receive message in the listener we map `deliverMode` into the `receivedDeliveryMode` and use exactly this message in the `RepublishMessageRecoverer`.

I think we have just missed the fact to remap `receivedDeliveryMode` back to the `deliverMode`  for consistency.

WDYT @garyrussell ?

Not sure what is your problem, @mdemarey , but for me this works well:
protected Map<? extends String, ? extends Object> additionalHeaders(Message message, Throwable cause) {
        message.getMessageProperties().setDeliveryMode(message.getMessageProperties().getReceivedDeliveryMode());
        return null;
}

See https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit/issues/53 for similar issue.

**Comment by mdemarey** [comment]
Yes indeed it works with your code sample, I was trying to add it in the headers, I will use this. It will be great to add the missing mapping.

Thanks!

**Comment by artembilan** [comment]
Well, to be honest that worked by default before https://jira.spring.io/browse/AMQP-589.
That old way we mapped received `deliveryMode` directly to the `deliveryMode` property - there was just no `receivedDeliveryMode` yet. Therefore the `RepublishMessageRecoverer` message has been send with the same `deliveryMode`.

**Comment by garyrussell** [comment]
We had to add `receivedDeliveryMode` to avoid unintended propagation of the inbound delivery mode to the outbound message.

I think it needs to be configurable on the republisher. For example, someone might want NON_PERSISTENT on the main queue, but PERSISTENT on the DLQ.

**Comment by artembilan** [comment]
I still think that `deliveryMode` in the message to send here in the `RepublishMessageRecoverer` should be default as it is specified by the `MessageProperties`:
```
public static final MessageDeliveryMode DEFAULT_DELIVERY_MODE = MessageDeliveryMode.PERSISTENT;
```
In other words we should set it to `PERSISTENT` if it is `null` like it is in the case of received message.

I don't mind to add the setter to let to override it, but at the same time the `additionalHeaders()` overriding is much flexible and may provide a logic per message basis.

**Comment by garyrussell** [comment]
Yes; that would make sense.
