### ISSUE TITLE
DirectMessageListenerContainer does not restart consumers after a lost connection has been recovered

### ISSUE THREAD

**Issue by Monofraps** [spring-projects/spring-amqp#637]
So we've been playing around with version spring-amqp/-rabbit 2.0.0 M5 and have a weird issue with `DirectMessageListenerContainer`s.

We use a `CachingConnectionFactory` with all values at their defaults. The `DirectMessageListenerContainer`s also have everything on default except missingQueuesFatal set to false.

To test connection and consumer recovery, we stop the RabbitMQ server (sends connection close because of shutdown). All `DirectMessageListenerContainer` (DMLC) detect the lost connection properly. However, once the server comes back up, there's always one DMLC which does not restart its consumers. 

I've been debugging a little:
It looks like the first DMLC to run the monitor task calls `DirectMessageListenerContainer#doConsumeFromQueue` from the consumer monitor task and still gets a connection object in [DirectMessageListenerContainer.java#L553](https://github.com/spring-projects/spring-amqp/blob/0d341a1bfa30ba612db6a372f1f37cdb0e1750ff/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/DirectMessageListenerContainer.java#L553) form the connection factory. This raises an Exception in [DirectMessageListenerContainer#L567](https://github.com/spring-projects/spring-amqp/blob/0d341a1bfa30ba612db6a372f1f37cdb0e1750ff/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/DirectMessageListenerContainer.java#L567) when creating a channel. This exception is caught in the monitor thread [DirectMessageListenerContainer.java#L416](https://github.com/spring-projects/spring-amqp/blob/0d341a1bfa30ba612db6a372f1f37cdb0e1750ff/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/DirectMessageListenerContainer.java#L416) which just logs an error. However, the consumer which failed to start is not added back to the list of `consumersToRestart`.

Let me know if you're having trouble reproducing this issue; I'll try to create a minimal example application then.

EDIT: Logs at https://gist.github.com/Monofraps/152a6d95d63252c4eae62f310a84c50a

**Comment by artembilan** [comment]
Thank you for heads up, @Monofraps !

Looks like I see what we are missing there.
So, we have this code so far:
```
try {
	channel = connection.createChannel(isChannelTransacted());
     ...
}
catch (AmqpApplicationContextClosedException e) {
	throw new AmqpConnectException(e);
}
catch (IOException e) {
	RabbitUtils.closeChannel(channel);
	RabbitUtils.closeConnection(connection);
        ...
        this.consumersToRestart.add(consumer);
        consumer = null;
}
```
But according your StackTrace we have there:
```
org.springframework.amqp.AmqpConnectException: java.net.ConnectException: Connection refused: connect
```
That's very close to what we would like, unless we have missed the fact that `java.net.ConnectException` (`IOException`) is wrapped to the `AmqpConnectException` by the `RabbitExceptionTranslator`:
```
protected final Connection createBareConnection() {
		try {
		...
		}
		catch (IOException | TimeoutException e) {
			throw RabbitExceptionTranslator.convertRabbitAccessException(e);
		}
	}
```

So, this is a good catch and I think there is no need in the application to reproduce.
Although we will be appreciate, if you are able to test the solution from your side when it comes to this issue as a BUILD-SNAPSHOT.

**Comment by artembilan** [comment]
@Monofraps ,

as you see the fix has been just pushed.

Give it 10-15 mins and BUILD-SNAPSHOT will be available for testing from your side.

**Comment by Monofraps** [comment]
Hi @artembilan and thank you for the quick reply. :)

I now see another issue. The consumer which should be added back to the list of consumers to restart [here](https://github.com/spring-projects/spring-amqp/blob/master/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/DirectMessageListenerContainer.java#L598) is initialized [here](https://github.com/spring-projects/spring-amqp/blob/master/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/DirectMessageListenerContainer.java#L571). However, the connect exception is thrown two lines earlier which leaves `consumer` at `null`. I suppose you could do the same as in [DirectMessageListenerContainer.java#L556](https://github.com/spring-projects/spring-amqp/blob/master/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/DirectMessageListenerContainer.java#L556).

So maybe something like 
```
Channel channel = null;
SimpleConsumer consumer = null;
try {
	channel = connection.createChannel(isChannelTransacted());
	channel.basicQos(getPrefetchCount());
	consumer = new SimpleConsumer(connection, channel, queue);
	channel.queueDeclarePassive(queue);
	consumer.consumerTag = channel.basicConsume(queue, getAcknowledgeMode().isAutoAck(),
			(getConsumerTagStrategy() != null
					? getConsumerTagStrategy().createConsumerTag(queue) : ""),
			false, isExclusive(), getConsumerArguments(), consumer);
}
catch (AmqpApplicationContextClosedException e) {
	throw new AmqpConnectException(e);
}
catch (IOException | AmqpConnectException e) {
	RabbitUtils.closeChannel(channel);
	RabbitUtils.closeConnection(connection);

	if (e.getCause() instanceof ShutdownSignalException
			&& e.getCause().getMessage().contains("in exclusive use")) {
		getExclusiveConsumerExceptionLogger().log(logger,
				"Exclusive consumer failure", e.getCause());
		publishConsumerFailedEvent("Consumer raised exception, attempting restart", false, e);
	}
	else if (e.getCause() instanceof ShutdownSignalException
			&& RabbitUtils.isPassiveDeclarationChannelClose((ShutdownSignalException) e.getCause())) {
		this.logger.error("Queue not present, scheduling consumer " + consumer + " for restart", e);
	}
	else if (this.logger.isWarnEnabled()) {
		this.logger.warn("basicConsume failed, scheduling consumer " + consumer + " for restart", e);
	}
	if(consumer == null) {
		this.consumersToRestart.add(new SimpleConsumer(null, null, queue));
	} else {
		this.consumersToRestart.add(consumer);
	}
	consumer = null;
}
```

**Comment by Monofraps** [comment]
I submitted my suggested change (which indeed fixes the consumer restart issues) as a PR

**Comment by mohitmanga** [comment]
@artembilan 
We have been facing the same issue currently. Only difference that we see in our case is that due to some network failure we are getting `java.net.SocketTimeoutException` which being converted into `org.springframework.amqp.AmqpIOException by RabbitExceptionTranslator.convertRabbitAccessException(e);`

DirectMessageListenerContainer#doConsumeFromQueue is only handling either of IOException | AmqpConnectException 
[DirectMessageListenerContainer.java#L661](https://github.com/spring-projects/spring-amqp/blob/1195658c6099a0faa459b0191057eea87927c3ac/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/DirectMessageListenerContainer.java#L661) as result of which AmqpIOException is preventing consumer from getting added back to  list of consumersToRestart

Stacktrace:
`[ERROR] 2018-11-26 08:19:52.501 [listenerContainer-consumerMonitor-1] [] DirectMessageListenerContainer:397 - Consumer canceled - channel closed SimpleConsumer [queue=task_result_queue, consumerTag=amq.ctag-3mWZ5wgYDuQJY2C1wn2aZA identity=5df5c0b2]
[INFO ] 2018-11-26 08:19:52.507 [listenerContainer-consumerMonitor-1] [] CachingConnectionFactory:447 - Attempting to connect to: [xxx:5672]
[ERROR] 2018-11-26 08:22:52.658 [listenerContainer-consumerMonitor-1] [] DirectMessageListenerContainer:416 - Cannot connect to server
org.springframework.amqp.AmqpIOException: java.net.SocketTimeoutException: connect timed out
        at org.springframework.amqp.rabbit.support.RabbitExceptionTranslator.convertRabbitAccessException(RabbitExceptionTranslator.java:71) ~[spring-rabbit-2.0.3.RELEASE.jar!/:2.0.3.RELEASE]`

**Comment by garyrussell** [comment]
Please open a new issue referencing this one, rather than commenting on an old, closed, issue.
