### ISSUE TITLE
correlation id missing when trying to communicate between different rabbitmq rpc library

### ISSUE THREAD

**Issue by campanagerald** [spring-projects/spring-amqp#657]
I am using spring amqp for my service written in Java, and my colleague created a service using nodejs and he is using amqplib-rpc. The problem is when I tried to request from spring amqp to amqplib-rpc it raise an error that "reply() cannot reply to a message without 'correlationId'". It said that spring amqp automatically creates a correlationid. In fact, its ok when I use spring amqp to spring amqp request

**Comment by garyrussell** [comment]
The client has to provide a correlation id.

When spring amqp is the client, it does that; your colleague needs to populate that property on the client side.

**Comment by campanagerald** [comment]
Thanks, by the way the spring amqp is the client. When the message received by the server the correlationId is undefined. Here's the content of the message.

{ fields:
{ consumerTag: 'amq.ctag-pWkDuqi5hdwByLbOHeLrxA',
deliveryTag: 1,
redelivered: false,
exchange: '',
routingKey: 'spring.to.node' },
properties:
{ contentType: 'text/plain',
contentEncoding: 'UTF-8',
headers: {},
deliveryMode: 2,
priority: 0,
correlationId: undefined,
replyTo: 'amq.rabbitmq.reply-to.g2dkABNyYWJiaXRAcmFiYml0bXEtc3J2AABkoQAAAAcD.CTev4IP5OKl7fAC8WDoAvw==',
expiration: undefined,
messageId: undefined,
timestamp: undefined,
type: undefined,
userId: undefined,
appId: undefined,
clusterId: undefined },
content: <Buffer 68 65 6c 6c 6f> }

**Comment by artembilan** [comment]
You see, there is `replyTo: 'amq.rabbitmq.reply-to.g2dkABNyYWJiaXRAcmFiYml0bXEtc3J2AABkoQAAAAcD.CTev4IP5OKl7fAC8WDoAvw==',` header. Exactly this is used by Spring AMQP for request-reply scenarios. 

We need to know what kind of communication protocol expects that lib to work out solution from the Spring AMQP perspective.

**Comment by campanagerald** [comment]
I already raised an issue to https://github.com/tjmehta/amqplib-rpc/issues/18

**Comment by artembilan** [comment]
Well, I think what missed in that tutorial is a sample how to configure fixed reply queue: https://docs.spring.io/spring-amqp/docs/1.7.3.RELEASE/reference/html/_reference.html#reply-listener. In this case I agree that `correlationId` is set in the request message.

**Comment by panchenko** [comment]
Saying it differently: it seems that amqplib-rpc does not support [Direct reply-to](https://www.rabbitmq.com/direct-reply-to.html) :-)
