### ISSUE TITLE
Correlation Id  spring apmq 1.7.x

### ISSUE THREAD

**Issue by igieon** [spring-projects/spring-amqp#662]
Hello this code look weird SimpleAmqpHeaderMapper.toHeaders
```Java
	@SuppressWarnings("deprecation")
			byte[] correlationId = amqpMessageProperties.getCorrelationId();
			if (correlationId != null && correlationId.length > 0) {
				headers.put(AmqpHeaders.CORRELATION_ID, correlationId);
			}
			String correlationIdString = amqpMessageProperties.getCorrelationIdString();
			if (StringUtils.hasText(correlationIdString)) {
				headers.put(AmqpHeaders.CORRELATION_ID, correlationId);
			}
```

second why is not there something like
```
if (StringUtils.hasText(correlationIdString)) {
				headers.put(AmqpHeaders.CORRELATION_ID, correlationIdString);
			}
```

**Comment by artembilan** [comment]
Well, that's just a bug. Simple copy/paste without testing evil.

Thank you for catching that out!

We will be glad to have a fix from you as a contribution.

**Comment by artembilan** [comment]
Fixed via: https://github.com/spring-projects/spring-amqp/commit/024a32c71bc419ac055d88851d861f9b231094f0

@igieon ,

Thank you very much for the contribution.
Looking forward for more!
