### ISSUE TITLE
Ability to configure auto-startup on a per @RabbitListener basis

### ISSUE THREAD

**Issue by dustinschultz** [spring-projects/spring-amqp#669]
This is a request for an Enhancement:

I brought this up via spring-boot https://github.com/spring-projects/spring-boot/issues/10437 and it was suggested to move it here.

`@RabbitListener`'s are configured to auto start by default. It's possible to disable auto-start but it's an all-or-nothing change via the Spring Boot property: `spring.rabbitmq.listener.auto-startup=false`. 

The ability to configure on a per `@RabbitListener` basis whether or not it auto-starts would be a useful feature (perhaps via an attribute (e.g. `autostartup=false`)

The only reasonably-clean (not really) way I could come up with was to configure a custom `containerFactory="rabbitContainerFactory"` on the `@RabbitListener` with an implementation like this:

```
@Bean
RabbitListenerContainerFactory<SimpleMessageListenerContainer> rabbitContainerFactory(ConnectionFactory rabbitConnectionFactory)
{
    SimpleRabbitListenerContainerFactory factory = new SimpleRabbitListenerContainerFactory()
    {
        @Override
        protected void initializeContainer(final SimpleMessageListenerContainer instance)
        {
            super.initializeContainer(instance);
            instance.setAutoStartup(false);
        }
    };

    factory.setConnectionFactory(rabbitConnectionFactory);
    return factory;
}
```

**Comment by garyrussell** [comment]
[AMQP-774](https://jira.spring.io/browse/AMQP-774).

**Comment by artembilan** [comment]
Does this work for you
```
/**
	 * If provided, the listener container for this listener will be added to a bean
	 * with this value as its name, of type {@code Collection<MessageListenerContainer>}.
	 * This allows, for example, iteration over the collection to start/stop a subset
	 * of containers.
	 * @return the bean name for the group.
	 * @since 1.5
	 */
	String group() default "";
```

?

**Comment by dustinschultz** [comment]
@artembilan I definitely looked at the `group` feature but unfortunately had no luck. 

The listener is already started by the time I get access to the `Collection<MessageListenerContainer>` and if there's items already in the queue, I run the risk of them being consumer before I can call `stop()`.

I tried getting access to the `Collection<MessageListenerContainer>` earlier in the process via the `ContextRefreshed` event but that hook is called _after_ a context refresh. Ideally ... something like a `BeforeContextRefresh` event would work but I couldn't find one.

**Comment by artembilan** [comment]
Let's try this!
````java
@Autowired
@Qualifier("myGroup")
Collection<AbstractMessageListenerContainer> containers;

@PostConstruct
public void setup() {
     this.containers.forEach(c -> c.setAutoStartup());
}
````

**Comment by dustinschultz** [comment]
Awesome! Thanks for the help guys and thanks for the awesome framework.
