### ISSUE TITLE
I found a bug in class RabbitManagementTemplate

### ISSUE THREAD

**Issue by zjcscut** [spring-projects/spring-amqp#671]
Hey guys, I found a bug in class `RabbitManagementTemplate`, column 194, method `deleteExchange(Exchange exchange)`. This method should call `this.rabbitClient.deleteExchange(DEFAULT_VHOST, exchange.getName())` but it does `this.rabbitClient.deleteQueue(DEFAULT_VHOST, exchange.getName())`. I found it for calling `deleteExchange(Exchange exchange)` but it did not make any effectiveness.

**Comment by artembilan** [comment]
Oops! That's good catch!
Would you mind to [contribute](https://github.com/spring-projects/spring-amqp/blob/master/CONTRIBUTING.adoc) the fix on the matter? 

Thank you!

**Comment by artembilan** [comment]
We have to release `2.0` today, maximum tomorrow, so I'm taking care about this one.

You always can come back to us with any other contributions!
