### ISSUE TITLE
Queues property is not correctly resolved on the @org.springframework.amqp.rabbit.annotation.RabbitListener class

### ISSUE THREAD

**Issue by novtor** [spring-projects/spring-amqp#672]
When the "queues" value is configured via application.yml with conditionals inside, it is not correctly resolved
[RabbitListenerIssue.zip](https://github.com/spring-projects/spring-amqp/files/1349143/RabbitListenerIssue.zip)

**Comment by novtor** [comment]
I think, the issue is in this file:
https://github.com/spring-projects/spring-amqp/blob/ffff7d7c12ca1eb12004f3b899f5c810e68999c8/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/annotation/RabbitListenerAnnotationBeanPostProcessor.java#L729

should be replaced by
if (!(resolvedValue.**contains**("#{") && value.**contains**("}"))) {

**Comment by garyrussell** [comment]
I don't think changing it `contains(()` is the right solution.

I think we should simply document that the SpEL evaluation is done after the property placeholder resolution and must match the pattern `^#{...}$`.

My 2c.
