### ISSUE TITLE
How can i capture event with java

### ISSUE THREAD

**Issue by kiakaku** [spring-projects/spring-amqp#678]
I'm following this document https://docs.spring.io/spring-amqp/reference/htmlsingle/#_event_consumption

But how i implement with java 

I'm trying to implement java application consume rabbit queue and want to stop consumer when container idle after x miliseconds

**Comment by artembilan** [comment]
Your question isn't clear. Look, the sample in the Reference Manual is like:
```
   @EventListener(condition = "event.listenerId == 'foo'")
    public void onApplicationEvent(ListenerContainerIdleEvent event) {
        ...
    }
```

This is indeed Java code.
And since you say:
> want to stop consumer when container idle

I really sure that you use Spring AMQP, not just plain AMQP Java Client.
So, fully unclear what is wrong with approach we suggest you.

Please, elaborate more

**Comment by kiakaku** [comment]
hi Artembilan
I don't write spring project, only using spring AMQP as a lib
so how can i init instance of Listener and register to listen event from my container

**Comment by garyrussell** [comment]
Spring AMQP depends on the `spring-context` jar - so you already have the listener on your classpath - you just have to use it.

**Comment by panchenko** [comment]
@kiakaku It seems to me the project [homepage](http://projects.spring.io/spring-amqp/) contains a pure java example.

**Comment by artembilan** [comment]
Good suggestion, @panchenko !

Only the problem that Spring AMQP components are fully based on Spring foundation.
And that sounds a bit awkward to use Spring components but be outside of Spring Dependency Injection Container.

The `AbstractMessageListenerContainer` implements `ApplicationEventPublisherAware` to be auto-wired with the `ApplicationEventPublisher`. But that is really possible only when your `AbstractMessageListenerContainer` is bean if fully configured `ApplicaitonContext`.

Right, you can, @kiakaku , inject your own `ApplicationEventPublisher` implementation to manually created `SimpleMessageListenerContainer`, but is that the right way to use Spring at all?
alongside with the `ApplicationEventPublisher` you have to ensure many other Spring container related options to be sure that it is going to work properly. Therefore the question is: what is the point to use Spring AMQP without Spring?

Thanks

**Comment by kiakaku** [comment]
@panchenko, thanks for your suggestion, I followed this example and i can listen and publish message
But now i want to check if container idle x seconds (no message in x seconds) then stop it. It seems i cannot do it with pure java

@artembilan. I just don't want to use spring because it seems heavy, if cannot use pure java i will consider use Spring :)

**Comment by kiakaku** [comment]
@artembilan 
I tried to use spring for capture ListenerContainerIdleEvent
But i get a little problem when condition is not correct
 Example:
```
    @EventListener(condition = "event.listenerId = 'metfone_mca_mo_listener'") // need double equal
    public void onApplicationEvent(ListenerContainerIdleEvent event){
        logger.info(event.getListenerId());
    }
```
Spring did not throws Exception or any message to notify me and container was restarted after idle-event-interval

`SimpleMessageListenerContainer:1099 - Restarting Consumer`

**Comment by artembilan** [comment]
Well, you don't need to use that `condition` if it looks for you so complicated.
You may move filtering logic into the `onApplicationEvent` directly.

The exception is thrown, but since the `SimpleMessageListenerContainer` is async by nature you don't get it in your main thread. Everything is happened on the listener thread. However I'm sure there is some ERROR logs on the matter anyway. Plust you can inject into the `SimpleMessageListenerContainer` some `ErrorHandler` to catch such an async exception.

This ticket is too long for being a bug or feature request.
This looks more like a support what we don't do from here on GH.

You should re-think your vision about Spring and read more book to understand how everything works there. Afterwards you won't have questions like this because everything will be in your application for free.

**Comment by kiakaku** [comment]
Thanks @artembilan
