### ISSUE TITLE
No consumer failed event in case of Error

### ISSUE THREAD

**Issue by mateuszmrozewski** [spring-projects/spring-amqp#680]
SimpleMessageListenerContainer does not emit an event in case of catching an Error:
https://github.com/spring-projects/spring-amqp/blob/master/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainer.java#L1060

On one hand it makes sense as in case of errors it might be hard to recover or even handle such an event. On the other hand my observation was that an OutOfMemory error caused shutdown of the consumer but my service kept running and would be able to handle the event.

Documentation is slightly misleading here:
"The containers publish application events whenever a listener (consumer) experiences a failure of some kind"

My questions are:
1. Would it make sense to emit an event in case of an Error?
2. If not, is there a way to get the list of active/failed consumers? I could use that to expose some health checks and metrics.

**Comment by garyrussell** [comment]
It's an omission; we should publish an event for that condition.

[Contributions](https://github.com/spring-projects/spring-amqp/blob/master/CONTRIBUTING.adoc) are welcome!

**Comment by mateuszmrozewski** [comment]
I reported that on JIRA now and hope to provide a PR soon.

https://jira.spring.io/browse/AMQP-782
