### ISSUE TITLE
RabbitListenerEndpointRegistry.isRunning violates the Lifecycle contract.

### ISSUE THREAD

**Issue by samuelbr** [spring-projects/spring-amqp#699]
Hello,

We are dealing with problem because RabbitListenerEndpointRegistry.isRunning returns true if any of registered MessageListenerContainer is started. 

In case when RabbitListenerEndpointRegistry contains started and not started containers then method isRunning returns true and method start is not called, so not started containers don't start.

It's possible to fix this problem.
Thanks,

**Comment by garyrussell** [comment]
That is by design; you can use `registry.getListenerContainers()` and iterate over them to manage containers individually.

**Comment by artembilan** [comment]
Closed with the status "Works as Designed".
See Gary's comment above.
