### ISSUE TITLE
Send & Receive with Temporary queues is create a noLocal consumer

### ISSUE THREAD

**Issue by sarah-micallef** [spring-projects/spring-amqp#712]
When connecting to Qpid, the reply message is not being received when using the send and receive methods of the `RabbitTemplate`. I suspect that this is because the consumer created to receive the replies is configured as `noLocal` (see https://github.com/spring-projects/spring-amqp/blob/1.7.x/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitTemplate.java#L1297).

This article (https://www.rabbitmq.com/interoperability.html#qpid-python-tests) points out that no-local consumers are not supported by RabbitMQ which explains why replies are received irrespective of the no-local property when using RabbitMQ.

Should the consumer created to receive the reply be configured with the `noLocal` property set to `false`?

**Comment by artembilan** [comment]
Related SO question: https://stackoverflow.com/q/49028292/2756547

**Comment by artembilan** [comment]
Confirmed via JavaDocs from the RabbitMQ Java Client on the matter:
https://github.com/rabbitmq/rabbitmq-java-client/blob/master/src/main/java/com/rabbitmq/client/Channel.java#L1129-L1130

```
* @param noLocal True if the server should not deliver to this consumer
* messages published on this channel's connection. Note that the RabbitMQ server does not support this flag.
```

I think we should make it `false` by default and expose something like `noLocalReplyConsumer` on the `RabbitTemplate` to let to retain the previous behavior.

Contributions are welcome!

**Comment by garyrussell** [comment]
Copying the SO dialog here...

Gary: 
>t's a bit unusual to have the server side running in the same application as the client side. That's the only way no-local should affect this scenario since, normally, the client-side doesn't publish the reply.

>We don't claim compatibility with QPID (certainly not AMQP 1.0) but I see QPID claims support for AMQP 0.9.x so feel free to open a JIRA Issue and we'll take a look as time permits.

Sarah:
>Thanks for your reply. This actually happened during a spring boot test which makes use of qpid as an embedded amqp broker. So in my case I have both the server and the client running within the same app. 

BTW, I was not aware that using an embedded QPID broker would work with Spring AMQP (never tried it) - we should explore that as a first class feature.

**Comment by sarah-micallef** [comment]
I have encountered this scenario during a spring boot test where I load qpid as an embedded broker. So, as was pointed out in the referred stackoverflow question, it is quite unlikely to have the server and clint running in the same app. Nonetheless, is there a particular reason why the consume is being configured to be no local?

I think setting it to false by default is a good option. Perhaps the send and receive method could be overloaded with an extra param to make the consumer no local?

**Comment by sarah-micallef** [comment]
Yeah qpid is actually really working well so far. I opted for qpid rather than embedded rabbit because the latter requires erlang to be installed as far as i know.
