### ISSUE TITLE
Implement capture-all @RabbitHandler

### ISSUE THREAD

**Issue by domainname** [spring-projects/spring-amqp#713]
I'm writing a listener, which listens to a queue. I only want to handle a few types of messages from the queue, and simple ignore other messages. Unfortunately, there is no way to write a capture-all handler. I'm looking forward to something like that.

Pseudo code:

>     @RabbitHandler
>     public void handle(ClassA msg) {
>         // do some work
>     }
> 
>     @RabbitHandler
>     public void handle(ClassB msg) {
>         // do some work
>     }
> 
>     @RabbitHandler
>     public void captureAllHandler(??? msg) {
>         // ignore all other msgs
>     }
>

**Comment by garyrussell** [comment]
This was added a couple of weeks ago; it will be in the 2.0.3 release - you can try it out with the 2.0.3.BUILD-SNAPSHOT from the spring snapshots repo.

[Documentation here](https://docs.spring.io/spring-amqp/docs/2.0.3.BUILD-SNAPSHOT/reference/html/_reference.html#annotation-method-selection).

```java
    @RabbitHandler(isDefault = true)
    public String defaultMethod(Object object) {
        ...
    }
```

**Comment by domainname** [comment]
Glad to hear that. Thanks @garyrussell.
