### ISSUE TITLE
MessagePostprocessor seems not to get called on reply

### ISSUE THREAD

**Issue by konraifen88** [spring-projects/spring-amqp#719]
I am trying to invoke an `MessagePostProcessor` to apply/verify a header before sending/after receiving an message.

I have managed to add the PostProcessor functionality for following situations:
* Before send (in publisher)
* After receive (in publisher)
* After receive (in consumer with an AdviceChain, but I do not think that this is the meant sollution)

But I am not able to set it up for sending reply. When looking into the code I can see that the reply is handled inside the `AbstractAdaptableMessageListener` where an `replyPostProcessor` is available.

But this `replyPostProcessor` never is set, so it is always null and because of that never executed.

Little bit more detail:
The `AbstractAdaptableMessageListener` is created in the `MethodRabbitListenerEndpoint.createMessageListener` method. After creating a new `MessagingMessageListenerAdapter` `replyToAddress`, `messageConverter` and `beanResolver` are set and the listener is returned. I think that here the `replyPostProcessor` also should be set, too.

But I do not have this great understanding of the code to say this for sure.

The version I am using is 1.7.6.RELEASE

**Comment by artembilan** [comment]
Yeah... Looks like this is an omission on the Framework side.

Has to be fixed.

As a workaround I suggest to return the whole `org.springframework.amqp.core.Message` from your `@RabbitListener` method.

Or extend `SimpleRabbitListenerContainerFactory` and in the end of overloaded `initializeContainer` call the `SimpleMessageListenerContainer.getListener()`, cast it to the `AbstractAdaptableMessageListener` and then inject `MessagePostProcessor`  via the mentioned `setReplyPostProcessor()`.

**Comment by garyrussell** [comment]
>After receive (in consumer with an AdviceChain, but I do not think that this is the meant sollution)

In 2.0 we added `setAfterReceivePostProcessors` to the container factory.

If we fix this (replyMPP) in 1.7.x, we should probably back port that too.

**Comment by konraifen88** [comment]
Thanks for the quick reply. For the moment I've managed to do my post processing during, or better before/after the message conversion. For that I've created my own `Jackson2JsonMessageConverter` and add/process my header in this step.

**Comment by garyrussell** [comment]
@konraifen88 - please open a [JIRA "Improvement" issue](https://jira.spring.io/browse/AMQP) against Spring AMQP; when that is implemented, we'd then need a change to Spring Boot, to auto configure them. They can probably be simple "marker" interfaces that extend `MessagePostProcessor`.

This would have to be a 2.1 feature (in both cases), I'm afraid, unless you feel the current situation is over-burdensome.

**Comment by konraifen88** [comment]
Thanks for the fast fix here. 

Like you told I opened up an improvement issue ([AMQP-803](https://jira.spring.io/browse/AMQP-803)).
