### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by jayzch** [spring-projects/spring-amqp#723]
> Caused by: java.lang.NullPointerException: null 	at 
> org.springframework.amqp.rabbit.connection.SimpleConnection.createChannel(SimpleConnection.java:59) 	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory$ChannelCachingConnectionProxy.createBareChannel(CachingConnectionFactory.java:1156) 	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory$ChannelCachingConnectionProxy.access$200(CachingConnectionFactory.java:1144) 	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.doCreateBareChannel(CachingConnectionFactory.java:585) 	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.createBareChannel(CachingConnectionFactory.java:568) 	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.getCachedChannelProxy(CachingConnectionFactory.java:538) 	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.getChannel(CachingConnectionFactory.java:520) 	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.access$1500(CachingConnectionFactory.java:94) 	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory$ChannelCachingConnectionProxy.createChannel(CachingConnectionFactory.java:1161) 	at org.springframework.amqp.rabbit.connection.ConnectionFactoryUtils$1.createChannel(ConnectionFactoryUtils.java:112) 	at org.springframework.amqp.rabbit.connection.ConnectionFactoryUtils.doGetTransactionalResourceHolder(ConnectionFactoryUtils.java:173) 	at org.springframework.amqp.rabbit.connection.ConnectionFactoryUtils.getTransactionalResourceHolder(ConnectionFactoryUtils.java:92) 	at org.springframework.amqp.rabbit.core.RabbitTemplate.doExecute(RabbitTemplate.java:1802) 	at org.springframework.amqp.rabbit.core.RabbitTemplate.execute(RabbitTemplate.java:1784) 	at org.springframework.amqp.rabbit.core.RabbitTemplate.send(RabbitTemplate.java:864) 	at org.springframework.amqp.rabbit.core.RabbitTemplate.convertAndSend(RabbitTemplate.java:927) 	at org.springframework.amqp.rabbit.core.RabbitTemplate.convertAndSend(RabbitTemplate.java:910) 	at 
>

**Comment by garyrussell** [comment]
That implies the underlying rabbit connection returned no channel, which should not be possible.

Please show your configuration. the code that exhibits this behavior, together with version information for all libraries.

**Comment by jayzch** [comment]
<spring-amqp.version>2.0.2.RELEASE</spring-amqp.version>
I changed different rabbit mq server 
![image](https://user-images.githubusercontent.com/5292764/37524384-a46dc7ea-2964-11e8-882c-27efa165987d.png)

![image](https://user-images.githubusercontent.com/5292764/37524397-a92754fe-2964-11e8-9da8-418161d57892.png)


And then I solve the problem  by setting `maxChannel` to 0.

But I think the framework should not   threw NullPointerException.

**Comment by artembilan** [comment]
Not clear, what you show to us, @jayzch .
That's why Gary asked about some code to reproduce.

Indeed, Framework should not throw NPE, but you see your comment is not readable and we can't understand that stack trace properly. If you could format it the standard console output way, that would be helpful. Anyway +1 for some code to reproduce. Otherwise neither we can help you, nor you for us to fix the problem if it is there.

Thank you for understanding.

**Comment by jayzch** [comment]
This problem occurs when  the  number of  RabbitMQ Server  channels  exceeds the limit    maxChannel

**Comment by artembilan** [comment]
OK! Let it be. But how to reproduce, please?
Why also don't edit the mentioned stack trace to help us to read it clearly?

**Comment by garyrussell** [comment]
It's a bit odd that the client returns null in this case rather than throwing an exception.

I think the assertion should be made regardless of whether a transaction is being used.

**Comment by garyrussell** [comment]
It is odd, indeed, but clear in the javadocs...

    /**
     * Create a new channel, using an internally allocated channel number.
     * If <a href="http://www.rabbitmq.com/api-guide.html#recovery">automatic connection recovery</a>
     * is enabled, the channel returned by this method will be {@link Recoverable}.
     *
     * @return a new channel descriptor, or null if none is available
     * @throws IOException if an I/O problem is encountered
     */
    Channel createChannel() throws IOException;
