### ISSUE TITLE
remove spring-web

### ISSUE THREAD

**Issue by matejsp** [spring-projects/spring-amqp#736]
Remove"org.springframework:spring-web" as a dependency.
Why is there even a need for spring-web being used as depedency? 
I have excluded it and only one test fails. Perhaps it should have test scope?

**Comment by artembilan** [comment]
The `spring-web` is a foundation for the `com.rabbitmq:http-client`, which is used from the `RabbitManagementTemplate`.

Not sure what is the problem though. If you don't need it, just exclude.

**Comment by garyrussell** [comment]
Agreed.

**Comment by artembilan** [comment]
According the latest changes in the RabbitMQ Hop the Spring Web is `optional` already: https://github.com/rabbitmq/hop/issues/124.

We need to go ahead and remove (move to test scope) such a dependency from Spring Rabbit.
