### ISSUE TITLE
RabbitListener annotation: Messages are treated several times with several application instances

### ISSUE THREAD

**Issue by kris2kris** [spring-projects/spring-amqp#747]
We have an instance of rabbitmq in a docker container and we have several instances of our application in some containers which are pulling the same queue.
We are using the annotation `@RabbitListener` to pull the queue, the problem is that each instance of our application succeed to read the same message from the queue but the expected behaviour is that if a listener is reading one message the other listener cannot read it.

**Comment by panchenko** [comment]
Might be you actually have multiple queues bound to the same same exchange, so each message sent to that exchange is duplicated into every queue?

**Comment by kris2kris** [comment]
No it is a direct exchange and there is only one queue configured for the exchange

**Comment by artembilan** [comment]
Time to share a simple reproducible project with us? Generally speaking it’s impossible with the single queue.

**Comment by kris2kris** [comment]
I try to reproduce the problem locally in a sample project but the two consumers are always read exactly half of the messages (even if the spring boot jar is running inside a docker container).
There is probably another problem on my side.
Thank you
