### ISSUE TITLE
RabbitListener annotation support for errorHandler and returnExceptions

### ISSUE THREAD

**Issue by tyronzerafa** [spring-projects/spring-amqp#759]
The `errorHandler` and `returnExceptions` values are not being set in the listener with class-level RabbitListener annotations. These values are being set and used correctly with method-level RabbitListener annotations.

**Comment by garyrussell** [comment]
Thanks; confirmed; moved [to JIRA - AMQP-818](https://jira.spring.io/browse/AMQP-818).
