### ISSUE TITLE
Support for existng lazy beans 

### ISSUE THREAD

**Issue by kalvarez2** [spring-projects/spring-amqp#777]
When an application has beans that are lazy and of type Collection, the beans get created even though the application does not require them. 

This is a problem because if the bean would otherwise not be used, it might not be able to set up correctly. Making the lazy bean return null by default, actually produces a NPE on initialize()

**Comment by kalvarez2** [comment]
I am not using Rabbit directly but indirectly on SCDF, using spring-cloud-starter-stream-rabbit (Kafka is giving me problems under load and am trying Rabbit out) our code base has collections of beans... I am currently disabling those beans with conditions so that Rabbit does not find them...  good to know there is a fix on Rabbit directly, but is not the default behavior on scdf.

**Comment by kalvarez2** [comment]
Maybe adding a catch on the initialize() try/finally to ignore beans that have issues would be a good idea?

**Comment by garyrussell** [comment]
You can modify the admin that boot creates in your stream apps to set the boolean.
