### ISSUE TITLE
Why not support RocketMQ

### ISSUE THREAD

**Issue by maskleo** [spring-projects/spring-amqp#791]
How do I make Spring integrate RocketMQ as easy as the current rabbitmq?

**Comment by artembilan** [comment]
Please, don’t duplicate your question in different places related to Spring AMQP project. I hope I have answered you on Gitter:
https://gitter.im/spring-projects/spring-amqp?at=5b6a5398e8698a2dca20e6e1

**Comment by artembilan** [comment]
However, please, look at this: https://github.com/apache/rocketmq-externals/tree/master/rocketmq-spring-boot-starter

**Comment by maskleo** [comment]
@artembilan  Thanks.
