### ISSUE TITLE
RabbitListenerEndpointRegistry removal of listeners support

### ISSUE THREAD

**Issue by dpzx** [spring-projects/spring-amqp#796]
There's no way to  remove a listener container from the registry for garbage collection.
The method needs to be implemented or the member field "listenerContainers" should be changed to protected so people who needs this functionality can subclass and implement it themselves.

**Comment by garyrussell** [comment]
Please explain your use case in more detail; it's not clear why you would want to dynamically remove the infrastructure for a statically defined `@RabbitListener`.

It's not as simple as just removing the container from the registry.

**Comment by dpzx** [comment]
@garyrussell We have a distributed queue service application where we are using RabbitListenerEndpointRegistry to dynamically create MessageListenerContainer that exclusively consume from a queue on demand. Once there are no more messages to be process, we listen to the idle event and then shutdown the container and want to remove the reference to that container so that it can be eligible for garbage collection.
