### ISSUE TITLE
Wrong consumer canceled using direct-reply-to

### ISSUE THREAD

**Issue by gasserus** [spring-projects/spring-amqp#804]
For short period of time two parallel requests are sent, which lead to two parallel consumers.
Afterwards I send requests which need only one consumer (the other consumer switches to idle) for at least `>idle time`.
After this time one consumer is canceled. Instead of canceling the idle consumer the running consumer is canceled. The request never gets an answer and after the reply timeout the consumer returns null.

In the PR #703 you mentioned `In the end it doesn't matter which consumers remain in the container`.
Looking at the adjustConsumers method in DirectMessageListenerContainer there is written that always the first consumer is canceled instead of the idled.
**Shouldn't only the idled consumers be removed or do I miss something?**

The remote procedure call (RPC) szenario is used with direct-reply-to (https://docs.spring.io/spring-amqp/reference/htmlsingle/#direct-reply-to).
No dedicated reply queue is used.

Library:
* spring-boot-starter-amqp 2.0.4.RELEASE
* spring-amqp 2.0.5.RELEASE

**Comment by artembilan** [comment]
How about to use a `DirectReplyToMessageListenerContainer` instead?

I see @garyrussell agreed to consider this as a bug, but maybe meanwhile there is some workaround with another component...

Thanks for the report!

**Comment by garyrussell** [comment]
@artembilan the bug *is* in the DRTMLC.
