### ISSUE TITLE
Upgrade to RabbitMQ Java Client 5.4.1

### ISSUE THREAD

**Issue by Piom** [spring-projects/spring-amqp#816]
The Gradle build configuration contains the dependency of the latest version.
But for maven it refers to version 5.1.2.

**Comment by garyrussell** [comment]
5.4.1 is on master (for the upcoming 2.1 release).

The 2.0.x version uses 5.1.2 which is the latest 5.1.x version.

Spring version dependency rules don't allow us to upgrade to a new minor version on an existing branch, only point release upgrades - we could upgrade to 5.1.3, for example, if it becomes available, but not to 5.2.0 or later.

You are free to override the version if you wish, but we don't test such scenarios.

Is there some specific reason you need a later client version?

**Comment by Piom** [comment]
Thank you, Gary.
You are right, I did not know about Spring version dependency rules.
There is no obvious need, I was noticed that there is a discrepancy in the version.
