### ISSUE TITLE
headers exchange declaration ignores "name" property

### ISSUE THREAD

**Issue by Scip88** [spring-projects/spring-amqp#824]
When Logger declares an exchange of type "Headers" , it is declared with name "headers" instead of provided name

**Comment by garyrussell** [comment]
Which appender? Please show your configuration.

**Comment by Scip88** [comment]
Sorry for poor informations 

### Log4j2 Appender.

class: **org.springframework.amqp.rabbit.log4j2.AmqpAppender**
line: **718-720**

`else if ("headers".equals(this.exchangeType)) {`
`	x = new HeadersExchange(this.exchangeType, this.durable, this.autoDelete);`
`}`


**Correct Code** is
`else if ("headers".equals(this.exchangeType)) {`
`	x = new HeadersExchange(this.exchangeName, this.durable, this.autoDelete);`
`}`

**Comment by garyrussell** [comment]
Ah - ok; thanks - copy/paste syndrome 😦 .

**Comment by Scip88** [comment]
you're welcome.
next time i try to do a pull request
