### ISSUE TITLE
RabbitTemplate multiple converters feature request

### ISSUE THREAD

**Issue by eduanb** [spring-projects/spring-amqp#827]
Would it be possible to add support for multiple message converters to a single RabbitTemplate similar to the Spring RestTemplate which has `setMessageConverters(List<HttpMessageConverter<?>> messageConverters)`? 

I'm working on a project which is currently in the process of migrating from XML to JSON and require a converter for both. This is already possible for `@RabbitListener` methods using a `ContentTypeDelegatingMessageConverter`. I know I could just create two RabbitTemplate beans but it is not ideal. 

Thanks

**Comment by garyrussell** [comment]
How do you propose selecting one converter or the other at runtime? i.e. how will the template know which one to use?

If you have a solution for that, in the meantime, you can create a simple `CompositeMessageConverter` that delegates to the other converters based on some condition.

**Comment by eduanb** [comment]
Looking at the implementation of `org.springframework.http.converter.HttpMessageConverter` it has `canRead` and `canWrite` methods that `RestTemplate` leavereges when deciding which converter to use. Since `org.springframework.amqp.support.converter.MessageConverter` does not have something like that it is not possible.

For my specific case, I ended up with a custom converter. It was simple to implement because I already had a list of `classesToBeBound` for the Jaxb2Marshaller. Like this:

`   @Bean
    public Set<Class<?>> classesToBeBound()
    {
        return ImmutableSet.of(A.class, B.class, C.class);
    }

    @Bean
    public Jaxb2Marshaller jaxbMarshaller(Set<Class<?>> classesToBeBound)
    {
        Jaxb2Marshaller marshaller = new Jaxb2Marshaller();
        marshaller.setClassesToBeBound(classesToBeBound.toArray(new Class[0]));
        return marshaller;
    }

    @Bean
    public MarshallingMessageConverter marshallingMessageConverter(Jaxb2Marshaller jaxbMarshaller)
    {
        MarshallingMessageConverter messageConverter = new MarshallingMessageConverter();
        messageConverter.setMarshaller(jaxbMarshaller);
        messageConverter.setUnmarshaller(jaxbMarshaller);
        messageConverter.setContentType(MessageProperties.CONTENT_TYPE_XML);
        return messageConverter;
    }

    @Bean
    public Jackson2JsonMessageConverter jackson2JsonMessageConverter()
    {
        return new Jackson2JsonMessageConverter();
    }


    @Bean
    @Qualifier("customDelegatingConverter")
    public MessageConverter customDelegatingConverter(Set<Class<?>> classesToBeBound, Jackson2JsonMessageConverter jackson2JsonMessageConverter, MarshallingMessageConverter marshallingMessageConverter)
    {
        return new MessageConverter()
        {
            @Override
            public Message toMessage(Object object, MessageProperties messageProperties) throws MessageConversionException
            {
                return classesToBeBound.contains(object.getClass()) ?
                       marshallingMessageConverter.toMessage(object, messageProperties) : jackson2JsonMessageConverter.toMessage(object, messageProperties);
            }
        };
    }

    @Bean
    public RabbitTemplate rabbitTemplate(CachingConnectionFactory connectionFactory, @Qualifier("customDelegatingConverter") MessageConverter customDelegatingConverter)
    {
        RabbitTemplate template = new RabbitTemplate(connectionFactory);
        template.setMessageConverter(customDelegatingConverter);
        return template;
    }`

Since it is not really possible I'm closing. Thanks
