### ISSUE TITLE
Configuring of shutdownTimeout

### ISSUE THREAD

**Issue by vbeskrovnov** [spring-projects/spring-amqp#833]
Is there any way to configure value of `org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer#shutdownTimeout` ? 
Can we add the property for this field?

Or it would be better to discuss this in https://github.com/spring-projects/spring-boot project?

**Comment by artembilan** [comment]
Yes, better Spring Boot, since configuration properties are managed there.

Thanks

**Comment by garyrussell** [comment]
Actually, no; first step is here - we would need to expose it via the container factory first.
