### ISSUE TITLE
Broken Queue behavior in SpringBoot 2.x

### ISSUE THREAD

**Issue by arcuri82** [spring-projects/spring-amqp#835]
Hi,
 I am upgrading a project from SpringBoot 1.5 to 2.x
I have a test case demonstrating the use of `Queue` and `@RabbitListener`. This works fine in 1.5, but it started failing once upgraded to 2.x

What I am doing (for didactic reasons) is to send N jobs to RabbitMQ on a queue, with 1 job being time consuming, whereas the other N-1 jobs are very quick. 
Given 2 `@RabbitListener` listeners (let's call them A and B) on such queue, one will execute the most expensive job, whereas the other will do all the remaining N-1 meanwhile.

This works in SpringBoot 1.5, but does not in 2.x (eg tried 1.5.17 and 2.0.6). By debugging this issue, it seems that the jobs are split evenly between A and B, which sounds very inefficient (ie, one listener is waiting doing nothing while there are available jobs on the queue).

Is this intentional or a bug? In the former case, how to restore the same behavior as in 1.5?

A test case to reproduce this issue can be found [here](https://github.com/arcuri82/testing_security_development_enterprise_systems/blob/master/advanced/amqp/distributed-work/src/test/kotlin/org/tsdes/spring/amqp/distributedwork/WorkerDockerTest.kt). It requires Docker, as using TestContainers to start RabbitMQ automatically.

**Comment by garyrussell** [comment]
On advice from the RabbitMQ team; the default prefetch count was increased from 1 to 250. See the "What's New?"...

https://docs.spring.io/spring-amqp/docs/2.0.0.RELEASE/reference/html/_introduction.html#_prefetch_default_value

**Prefetch default value**

The prefetch default value used to be 1, which could lead to under-utilization of efficient consumers. The default prefetch value is now 250, which should keep consumers busy in most common scenarios and thus improve throughput.

> ** Important**
>There are nevertheless scenarios where the prefetch value should be low: for example, with large messages, especially if the processing is slow (messages could add up to a large amount of memory in the client process), and if strict message ordering is necessary (the prefetch value should be set back to 1 in this case). Also, with low-volume messaging and multiple consumers (including concurrency within a single listener container instance), you may wish to reduce the prefetch to get a more even distribution of messages across consumers.

So, in your case, the first instance will have up to 249 "small" messages in his prefetch.

**Comment by arcuri82** [comment]
thanks! `spring.rabbitmq.listener.simple.prefetch = 1` fixed the issue. the change to the defaults to 250 makes a lot of sense. Somehow, I missed that part in the documentation explaining it.
