### ISSUE TITLE
DirectMessageListenerContainer silently fails to removeQueue if RabbitMQ connection unavailable

### ISSUE THREAD

**Issue by alowrey** [spring-projects/spring-amqp#837]
I'm running into an issue with the _DirectMessageListenerContainer_ [removeQueueNames](https://github.com/spring-projects/spring-amqp/blob/master/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/DirectMessageListenerContainer.java#L290) method, where if _isRunning_ returns false, then upon restart the consumer will be re-connected to even though its remove method was called. An example flow is:

1. Queue 1 is added via DirectMessageListenerContainer
2. AMQP connection dies (I know this should rarely, if ever, happen, but it does)
3. Queue 1 is removed via DirectMessageListenerContainer. Since isRunning() returns false, the consumer isn't removed from the _consumerByQueue_ map. No indication is given this was the case.
4. AMQP connection is restarted, queue consumer that was removed in step 3 is incorrectly reconnected to.

It seems like the fix is to still remove the consumer from the _consumersByQueue_ map in the case isRunning() returns false. That way, on re-connecting to RabbitMQ, the consumers map doesn't contain removed queues.

**Comment by garyrussell** [comment]
Yes; I can see it's a problem if you remove queues while the container is stopped.

However, what makes you believe that losing the connection causes the container to stop? It keeps trying to reconnect.

**Comment by garyrussell** [comment]
Actually, no, when the container is stopped, `consumersByQueue` is `clear()`ed. 

Can you provide a sample that exhibits the behavior you describe?

**Comment by alowrey** [comment]
Thanks for the quick response. In my case I don't think the container has stopped, it's just trying to reconnect, like you mentioned in your first comment, so `consumersByQueue` isn't actually cleared. If it helps, here's what the logs look like after I call `removeQueues` on queue 1, assuming queues 1 and 2 are currently active:

> October 23rd 2018, 09:03:00.427 | local.class | removing queue 1
> October 23rd 2018, 09:03:04.467 | CachingConnectionFactory | Attempting to connect to: [my-rabbit-mq.com:5672]
> October 23rd 2018, 09:03:04.474 | CachingConnectionFactory | Created new connection: rabbitConnectionFactory#3f1c5af9:11681/SimpleConnection@77e1bc8d [delegate=amqp://admin@10.0.0.0/, localPort= 54176]
> October 23rd 2018, 09:03:04.479 | DirectMessageListenerContainer | SimpleConsumer [queue=1, consumerTag=amq.ctag-mx4mASMBKw62VaJG6_VcpQ identity=7a2be969] started
> October 23rd 2018, 09:03:04.482 | DirectMessageListenerContainer | SimpleConsumer [queue=2, consumerTag=amq.ctag-FMcijcOVy_lEIhBcNTBGWQ identity=469690f0] started

I'll try to create an example, that's a bit tricky though since it requires the connection to be dropped/error out between the app and RabbitMQ.

**Comment by garyrussell** [comment]
I reproduced it; it's not related to `consumersByQueue`; it's the scheduled tasks to restart the consumers.

**Comment by alowrey** [comment]
Awesome, thanks for the quick fix @garyrussell !

**Comment by alowrey** [comment]
I'm currently on 2.0.3, so if it's possible to release a new 2.0.x version I could pull in I'd really appreciate it. Not super urgent, but it'd be nice to have a released version with the fix in the next week or so if possible. Let me know!

**Comment by garyrussell** [comment]
I scheduled them for Wednesday Nov 7.
