### ISSUE TITLE
Unable to successfully stop tomcat server

### ISSUE THREAD

**Issue by Kmegumi** [spring-projects/spring-amqp#841]
if i had execute the method of amqpTemplate.convertAndSend, when i stop the tomcat server,I will find the exception a thread named [pool-3-thread-1] has failed to stop it, but i cannot find which thread pool own it，this is my amqp configurations and used demo

![c436a89b-2b6c-4cc5-ae3f-6345d08345ff](https://user-images.githubusercontent.com/26270054/47833813-d1101780-ddd7-11e8-9b90-36de64c06455.png)
![9361ed8d-5f9a-489c-934c-b271eb376750](https://user-images.githubusercontent.com/26270054/47833824-db321600-ddd7-11e8-88f5-625a6f9f3664.png)

![b7b57c63-80de-44fd-a738-c59d32b29b22](https://user-images.githubusercontent.com/26270054/47833830-e08f6080-ddd7-11e8-9c1b-9eb4286f923e.png)

![716f5ce8-1d06-4e3e-b4c3-23d01a4c4d47](https://user-images.githubusercontent.com/26270054/47833939-55629a80-ddd8-11e8-9f12-56941ba49491.png)

**Comment by artembilan** [comment]
You need to consider to add a `ThreadPoolTaskExecutor` `@Bean` and inject it into the `ConnectionFactory` bean.

The Tomcat is very sensitive to the threads which are not closed properly during application shutdown.

**Comment by garyrussell** [comment]
If the `ApplicationContext` is `close()` d properly, these threads will terminate, This should happen automatically if the context is managed by the web container and properly configured.

**Comment by Kmegumi** [comment]
I have found, if I had set the property publisherConfirms be true, when execute the method doCreateBareChannel will encapsulation the channel to be PublisherCallbackChannelImpl,if we not add ThreadPoolTaskExecutor into CachingConnectionFactory the SingleThreadExecutor in PublisherCallbackChannelImpl will not shutdown properly, Can we shutdown it properly in the destroy phase?

**Comment by garyrussell** [comment]
Yes; we should shut that one down (or use a daemon thread).

**Comment by artembilan** [comment]
I'll take it.
