### ISSUE TITLE
Improve Integration Testability with an In-memory AMQP Broker

### ISSUE THREAD

**Issue by fbutter** [spring-projects/spring-amqp#850]
As a developer using spring-amqp I want to be able to write integration tests with an in-memory AMQP broker like Apache Qpid. This is currently not possible due to the way spring-amqp handles the listener. I found this problem while writing integration tests, using a RabbitTemplate and a Qpid broker. To describe the problem in detail, I'll explain the setup in which I ran into this problem first. Next the expected behaviour followed by the actual behaviour.

# Setup
## Production Code:
- `spring-boot-starter-amqp` which brings the transitive dependency to `spring-amqp`.
- One Spring service "Foo" with method "bar". "bar" is used as AMQP receiver, annotated with `@RabbitListener`
- "Foo" has a service reference, used to process the received result.

```
@Service
public class Foo {

   private final DomainService service;

   @RabbitListener( ... )
   public void bar( DomainEvent payload ) {
      ....
      service.doSomething( payload );
   }
}
```

## Test Code
- Two Spring Boot Integration tests which creates one new context each.
- Apache Qpid in-memory AMQP broker.
- The first test `TestWithDomainService `uses the `DomainService` to further process the domain event.
- The second test `TestWithSpyDomainService` uses a spy instance of `DomainService` to assert the passed event.
- In both tests a domain event is send to the receiver using a `RabbitTemplate` and the in-memory AMQP broker.

Note: The fact, that one has a Spy Bean and the other not dosn't mather. The key is that both uses a different instance of DomainService.

```
...
@DisplayName( "Foo" )
class TestWithDomainService {

   @Autowired
   private RabbitTemplate rabbitTemplate;


   @Autowired
   private DomainService domainService;

   @Test
   @DisplayName( "should receive domain event with context containing real service" )
   void should....() {

      rabbitTemplate.convertAndSend( ... );

      assertDomainServiceReceivedEvent();
   }
}

...
@DisplayName( "Foo" )
class TestWithSpyDomainService {

   @Autowired
   private RabbitTemplate rabbitTemplate;

   @SpyBean
   private DomainService domainService;

   @Test
   @DisplayName( "should receive domain event with context containing spy service" )
   void should() {

      rabbitTemplate.convertAndSend( ... );

      assertDomainServiceReceivedEvent();
   }
}
```

# Expected Behaviour
- `TestWithDomainService` sends a domain event to Foo#bar. Foo#bar receives the domain event.
- `TestWithSpyDomainService` sends a domain event to Foo#bar. Foo#bar receives the domain event.

# Actual Behaviour
- `TestWithDomainService` sends a domain event to Foo#bar. Foo#bar is called.
- `TestWithSpyDomainService` sends a domain event to Foo#bar. Foo#bar is not called.
- It does not matter which test runs first. The first one will succeed, the second one will fail. Always.

# Root Cause Analysis
* The first test is executed, a new spring context starts, a new Bean of type Foo is instantiated. Foo holds a reference to DomainService.
* The RabbitListenerAnnotationBeanPostProcessor finds the listener, annotated with @RabbitListener. In this case "Foo#bar".
* spring-amqp polls the Qpid Broker and passes the domain event to the listener thread (SimpleMessageListenerContainer), containing the reference to the method "Foo#bar".
* The assertion in the test succeeds.
* The container is rebuild since TestWithSpyDomainService forces the context to use a cglib created Spy Bean of type DomainService. A new Bean of type Foo is instantiated. Foo holds a reference to the created SpyBean.
* The RabbitListenerAnnotationBeanPostProcessor processes the new instance of Foo too. RabbitListenerAnnotationBeanPostProcessor gets again a reference to the new listener method and passes it to a new thread.
* spring-amqp polls the Qpid Broker again and passes the domain event to the **first** listener thread. Since spring-amqp passes the event to the first listener, the event is passed to the first instance of Foo, holding the reference to DomainService, not to the second instance of Foo, holding a reference to the SpyBean.

The Problem is, that since RabbitListenerAnnotationBeanPostProcessor gets a reference to the listener method and passes it to a new thread. Consequently the service it is not managed by spring anymore. Further it will not be deconstructed by the Garbage Collector since the thread holds a reference to the service. When starting different contexts within different tests, n threads, holing references to n services of the same instance.

**Comment by garyrussell** [comment]
Spring framework caches test application contexts across test classes for reuse.

Since you are not using that feature and the application context has live tasks (listener container threads), you need to add `@DirtiesContext` to each test case to shut down the application contexts (and thus the listener containers).

It's also good practice to use unique queues for different test cases.

**Comment by fbutter** [comment]
I created a minimal example and proved, that is is a configuration issue on our side. It works without forcing the context to reload by using {{@DirtiesContext}}.

Thank you for your support.

**Comment by dtodo1paco** [comment]
Hi @fbutter , how did you finally implement the integration tests ? Can you share an example? Thanks in advance
