### ISSUE TITLE
Can not connect rabbitmq while i do not register consumer method

### ISSUE THREAD

**Issue by ProgrammerAndPumpkin** [spring-projects/spring-amqp#852]
I build my web application with org.springframework.boot 2.1.0.RELEASE.
### description
When i used annotations to declar rabbitmq beans,i find that if i do not declar any consumer(write a method with the @RabbitListener and @RabbitHandler annotations),my application can not connect to rabbitmq. It also can not declar  exchange or queue. 
### guess
I think rabbitmq connection might binding with @RabbitListener and @RabbitHandler annotations, so it can not work without @RabbitListener and @RabbitHandler.
 
waiting for your reply,thanks!

**Comment by garyrussell** [comment]
Your question is not clear; show an example and any exceptions you are getting.

There is **no** requirement to use `@RabbotListener`.

The connection is not established (and queues etc. declared) until something tries to open a connection, this can be a listener container, (with or without a `@RabbitListener`) or a `RabbitTemplate`, or anything that calls `createConnection()` on the `CachingConnectionFactory`.

**Comment by ProgrammerAndPumpkin** [comment]
thanks for your reply. From your message, i know if i did not open any connecttion, the beans that i declared were not register into rabbitmq. The @RabbotListener can create connection. so,if i do not declar any method with @RabbotListener.I just need explicit open connection in my code.I will try it, thanks again.

**Comment by ProgrammerAndPumpkin** [comment]
Dear Gary Russell, i have tried, your syggestion works well. Thanks for your help.
