### ISSUE TITLE
doc improvement on "Very, Very Quick"

### ISSUE THREAD

**Issue by wlund-pivotal** [spring-projects/spring-amqp#861]
I went to plug this:

`Very, Very Quick
Using plain, imperative Java to send and receive a message:

```java
ConnectionFactory connectionFactory = new CachingConnectionFactory();
AmqpAdmin admin = new RabbitAdmin(connectionFactory);
admin.declareQueue(new Queue("myqueue"));
AmqpTemplate template = new RabbitTemplate(connectionFactory);
template.convertAndSend("myqueue", "foo");
String foo = (String) `template.receiveAndConvert("myqueue");`
```
 in my workspace and got a compile error on admin.declareQueue. 

I wanted to check if this was a correct fix or whether I'm doing it wrong:

```java
ConnectionFactory connectionFactory = new CachingConnectionFactory();
AmqpAdmin admin = new RabbitAdmin(connectionFactory);
**admin.declareQueue(QueueBuilder.durable("myqueue").build());**
AmqpTemplate template = new RabbitTemplate(connectionFactory);
template.convertAndSend("myqueue", "foo");
String foo = (String) template.receiveAndConvert("myqueue");
```

**Comment by garyrussell** [comment]
Hi Wayne, 

You shouldn't have to use a builder.

Perhaps you imported the wrong `Queue` object. The one you need is `import org.springframework.amqp.core.Queue`; you probably imported `org.springframework.amqp.rabbit.annotation.Queue`.

We'll clarify the docs.

**Comment by wlund-pivotal** [comment]
You’re right.  Works with the correct import.

Wayne Lund
wlund@pivotal.io
916-296-1893 | twitter: @wxlund
