### ISSUE TITLE
Invalid @NonNullApi and null return

### ISSUE THREAD

**Issue by knalli** [spring-projects/spring-amqp#871]
Hi,

I have noticed an invalid nullable situation within spring-rabbit's API.

At least the method `org.springframework.amqp.rabbit.core.RabbitAdmin#getQueueProperties` is nullable (I think it was nullable alway as I'm using this for explicit queue management on startup for years) as the code clearly shows (in the local exception handling) as well as the documentation clearly states 

```
Returns 3 properties {@link #QUEUE_NAME}, {@link #QUEUE_MESSAGE_COUNT},
{@link #QUEUE_CONSUMER_COUNT}, or null if the queue doesn't exist.
```

However, the package contains a `@NonNullApi` also. And as I had understand this correctly, either this one is not correct, or there is a `@Nullable` missing, or the code should not return `null`. 

The issue got into my attention as IntelliJ hints about a redundant null check. Fortunately, I have checked this.

**Comment by artembilan** [comment]
This is bug. The method and its contract in the `AmqpAdmin` has to be marked with the `@Nullable`.

Feel free to provide a fix on the matter!
Also we won't mind if you review all other `AmqpAdmin` methods for similar flaw.

Thanks!

**Comment by knalli** [comment]
Sure. PR is there. I'm hoping this was right for this project and I had not missing some (non technical).

btw: I have noticed the same issue with `org.springframework.amqp.rabbit.core.ChannelCallback#doInRabbit´. It is defined not to return `null`, but this is done a lot.

**Comment by artembilan** [comment]
That one has to be fixed as well. There is no obligation from end-user to return something specific from that lambda implementation.
More over I found usage like this:
```
execute(channel -> {
	channel.queueDeclarePassive(Address.AMQ_RABBITMQ_REPLY_TO);
	return null;
});
```

So, this one has to be `@Nullable` as well. See `OperationsCallback` with similar signature.

Thanks
