### ISSUE TITLE
Fix TransactionManager Regression

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-amqp#883]
https://github.com/spring-projects/spring-amqp/commit/24521d89374aab8dfcb7f62ed1693582df7356b1#r31980633

Incorrect null check in `RabbitTransactionManager.afterPropertiesSet()`.

As a work-around; create a subclass and override `afterPropertiesSet()`.

**Comment by BarelyCool** [comment]
Looks like you guys beat me to the fix! Thanks for the quick response
