### ISSUE TITLE
Enhancement request: expose messagesPerAck in DirectMessageListenerContainer as being settable in DirectRabbitListenerContainerFactory 

### ISSUE THREAD

**Issue by sudr** [spring-projects/spring-amqp#893]
Looks like among the properties in DirectMessageListenerContainer that are typically of interest for configurability the messagesPerAck is not available to be configured when using DirectRabbitListenerContainerFactory. Looks like we can extend DirectRabbitListenerContainerFactory to make this available. But seems like a good candidate to be baked into the existing DirectRabbitListenerContainerFactory.

https://github.com/spring-projects/spring-amqp/blob/454e30e1b871d16963488b8142428b6f2abe807c/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/DirectRabbitListenerContainerFactory.java#L30

**Comment by artembilan** [comment]
Sounds like a good candidate for contribution, @sudr : https://github.com/spring-projects/spring-amqp/blob/master/CONTRIBUTING.adoc !

**Comment by sudr** [comment]
Thanks. I'll submit a PR for this change.

**Comment by garyrussell** [comment]
Actually, we added this for additional attributes that are not currently exposed...

```
	/**
	 * A {@link Consumer} that is invoked to enable setting other container properties not
	 * exposed  by this container factory.
	 * @param configurer the configurer;
	 * @since 2.1.1
	 */
	public void setContainerConfigurer(Consumer<C> configurer) {
		this.containerConfigurer = configurer;
	}
```

But, by adding an explicit property, it can then be configured when using Spring Boot in the `application.properties/yml`.

**Comment by sudr** [comment]
That helps. I am on a 2.0.x version currently which is why I didn't see this capability. But agreed it solves my use case. I will submit a PR as suggested for this enhancement to support the Spring Boot application.properties/yml method of configuration.
