### ISSUE TITLE
Spring-rabbit: error appears after set  some long expiration in seconds for key.

### ISSUE THREAD

**Issue by eifanin** [spring-projects/spring-amqp#932]
Hi!
I have a problem with next method:
Class: org.springframework.data.redis.connection.RedisStringCommands
Method: 	setEx(byte[] key, long seconds, byte[] value)
Library: spring-rabbit:1.6.3.RELEASE, spring-rabbit:2.1.4.RELEASE(tested only on these versions, but the problem may be relevant for other versions between the above.)
Scenario 1:
1. call the following code:
RedisTemplate.opsForValue().set(key, object,  1552566657611L, TimeUnit.SECONDS);
   
Expected: No errors. Object stored
Actual: No errors. Object stored. Timeout value changed by data type overflow(long -> int in setEx method) changed from 1552566657611L to 2083463755.   

Scenario 2:
1. call the following code:
RedisTemplate.opsForValue().set(key, object, 1552652402377L, TimeUnit.SECONDS);
   
Expected: No errors. Object stored
Actual: Object not stored. Timeout value changed by data type overflow(long -> int in setEx method) changed from 1552652402377L to -2125758775. Error appears:
org.springframework.dao.InvalidDataAccessApiUsageException:ERR invalid expire time in setex; 
nested exception is redis.clients.jedis.exceptions.JedisDataException: ERR invalid expire time in setex Object stored. 

Data type overflow:
long lTime1 = 1552566657611L;
long lTime2 = 1552652402377L;
int iTime1 = (int) lTime1;
int iTime2 = (int) lTime2;
System.out.println("lTime1: " + lTime1 + ", iTime1: " + iTime1 + "; lTime2: " + lTime2 + ", iTime2: " + iTime2);
lTime1: 1552566657611, iTime1: 2083463755; 
lTime2: 1552652402377, iTime2: -2125758775

Depending on the long value method stores data or not.
Could you solve this problem?
![screen](https://user-images.githubusercontent.com/22024256/54535297-e5277080-4996-11e9-9e3c-50fcb2763e21.png)

**Comment by garyrussell** [comment]
Exactly what does this redis question have to do with the Spring AMQP project?

**Comment by garyrussell** [comment]
Exactly what does this redis question have to do with the Spring AMQP project?

Perhaps you meant to open it in [spring-data-redis](https://github.com/spring-projects/spring-data-redis)?

**Comment by eifanin** [comment]
Yes, I did not choose the project correctly. 
Excuse me
