### ISSUE TITLE
Problems after upgrading to spring integration 5.0

### ISSUE THREAD

**Issue by bojanv55** [spring-projects/spring-amqp#935]
We are using "<spring.integration.version>5.0.8.RELEASE</spring.integration.version>" in combination with "<spring.version>5.0.9.RELEASE</spring.version>".

The problem we are facing is that there are a lot of messages in Unacked state on channels that are without consumers. Java shows that this socket connection is still open, but I guess somehow ListenerContainer is not running.

When we restart the component, all messages are sent to dead-letter queue. 

I know that this is not that much info, but wanted to ask if you already experienced this issues before?

![image](https://user-images.githubusercontent.com/1422698/49744438-09d7c200-fc9d-11e8-9da0-178187df0211.png)

**Comment by garyrussell** [comment]
Moved from SI https://github.com/spring-projects/spring-integration/issues/2658
