### ISSUE TITLE
Reduce logging regarding new connections

### ISSUE THREAD

**Issue by andrei-ivanov** [spring-projects/spring-amqp#946]
**Affects Version(s):** 2.1.4

---
Enhancement request: reduce logging level for new connections from _info_ to _debug_:
```
INFO  [o.s.a.r.c.CachingConnectionFactory] - Attempting to connect to: [rabbitmq:5672]
INFO  [o.s.a.r.c.CachingConnectionFactory] - Created new connection: rabbitConnectionFactory#5ec10ab1:0/SimpleConnection@5d4284e5 [delegate=amqp://guest@172.22.0.5:5672/, localPort= 33888]
```

It seems overkill to get trivial successful events on an _info_ level.

**Comment by andrei-ivanov** [comment]
And maybe the ones that log the `BAD_URI` in `AbstractConnectionFactory` should be switched from _info_ to _warn_

**Comment by garyrussell** [comment]
Unfortunately the first log ("Attempting...") was specifically added to help debug bad configuration; many people asked for it.

We can add a switch to control the level though, but we will have to leave the default at INFO.

**Comment by andrei-ivanov** [comment]
Hmm, that's weird, imagine how it would look like in case of JDBC connections :|

**Comment by garyrussell** [comment]
But, generally, there is only one shared connection; even with `CacheMode.CONNECTION` there should not be that many connections opened so I don't really understand why it's an issue.

**Comment by garyrussell** [comment]
But, generally, there is only one shared connection; even with `CacheMode.CONNECTION` there should not be that many connections opened so I don't really understand why it's an issue.

Why can't you just increase the logging level to WARN for that logger?

**Comment by andrei-ivanov** [comment]
Hmm, I was just experimenting with it and thought there will be more connections, that's why I gave the JDBC example and I've created the ticket because I like sane defaults 🙂

But you're right, if it's just one, it should be fine.
Sorry for the noise.
