### ISSUE TITLE
@RabbitListener randomly chooses method to execute

### ISSUE THREAD

**Issue by arnogeismar** [spring-projects/spring-amqp#966]
**Affected version**: 1.5.10-RELEASE
**Issue:** The @RabbitListener executes the wrong method and does not provide a startup exception when two candidates are found, rather it randomly chooses one of the methods to execute when a message is put on the queue.

I created a demo spring boot application to illustrate the bug:
https://github.com/arnogeismar/bugdemo

**Comment by garyrussell** [comment]
This is working as designed - you have 2 listener beans, `Parent` and `Child` (both are `@Component`s) - so you get 2 listener containers each consuming from the same queue. The broker will distribute the messages across all the consumers; hence the apparent "random" distribution.

**Comment by arnogeismar** [comment]
That explains it thank you
