### ISSUE TITLE
IBM JVM compatibility

### ISSUE THREAD

**Issue by nirtol** [spring-projects/spring-amqp#979]
## Bug report

Hi,
I'm using the latest version of spring-amqp with IBM JVM with ssl enabled which causes NoSuchAlgorithmException: SunX509 KeyManagerFactory not available

Since the use of sunX509 is hard-coded in RabbitConnectionFactoryBean. I guess should be replaced with TrustManagerFactory.getDefaultAlgorithm()

The issue is also described in:
https://stackoverflow.com/questions/55630983/spring-amqp-compatibility-with-ibm-jvm

Thanks

**Comment by artembilan** [comment]
Fixed via: https://github.com/spring-projects/spring-amqp/commit/e3d37e86cdb51aae3704cff4f132c20ed4e14df0
